### PR TITLE
Fix Value of RE macro

### LINKED ISSUE #499: Value of RE macro rate switching does not work
**Describe the bug**
Running the Value of RE macro with rate option "3. Different rate structure" results in error:

```
Macro did not finish.
[107] operand to sizeof must be a array, string, or table type
```

**To Reproduce**
1. Create PVWatts / Residential case.
2. Click **Macros** and go to Value of RE System macro.
3. For Rate option, choose *3. Different rate structure.*
4. Click **Run macro**.
5. Follow prompts to download rate for zip code 59102.

**Expected behavior**
Macro should show a dialog with two utility companies for zip=59102 and finish without error.

**Operating System and Version**
- SAM 2020.11.29

**Additional context**
This is caused by the  urdb_list_rates() function not working. Need to fix URDB ask query in invoke.cpp.

### PR DESCRIPTION
**Pull request by cpaulgilman**
Fixes #499

### CODE REVIEW

File: src/invoke.cpp [hunk 1]
```diff
@@ -2087,7 +2087,7 @@ void fcall_nsrdbquery(lk::invoke_t &cxt)
 	//Create the wind data object
 	NSRDBDialog dlgNSRDB(SamApp::Window(), "Advanced NSRDB Download");
 	dlgNSRDB.CenterOnParent();
-	int code = dlgNSRDB.ShowModal(); //shows the dialog and makes it so you can't interact with other parts until window is closed
+	int code = dlgNSRDB.ShowModal(); //shows the dialog and makes it szo you can't interact with other parts until window is closed
```
Comment (brtietz) [inline src/invoke.cpp:2090]: typo in comment

**Comment by cpaulgilman** [comment]
Typo fixed in https://github.com/NREL/SAM/commit/f5106549fc8000ded99f3f16d9dbe0e32d61f0dd

File: src/urdb.h [hunk 2]
```diff
@@ -128,8 +128,6 @@ class OpenEI
 	bool QueryUtilityCompanies(wxArrayString &names, wxString *err=NULL);
 	// search by zip code per email from Jay Huggins 1/9/15
 	bool QueryUtilityCompaniesbyZipcode(const wxString &zipcode, wxArrayString &names, wxString *err=NULL);
-	// resolve aliases in database per email from Jay Huggins 1/9/15
-	bool ResolveUtilityName(const wxString &name, wxString *urdb_name, wxString *err=NULL);
```
Comment (sjanzou) [inline src/urdb.h:132]: @cpaulgilman, is this no longer needed to resolve things like XCEL to CO Public Service, etc.? Does the search bring up the correct utilities? This was originally used to resolve multiple names for the same utility to a master utility name that actually contained all the rates. The other names were just aliases.

**Review by sjanzou — COMMENTED** [review]
Please check that the alias name resolving (e.g. XCEL to Co Public Service Co of Colorado.
image

**Comment by cpaulgilman** [comment]
Good point. I'll fix that. Thanks!
-------- Original message --------From: sjanzou <notifications@github.com> Date: 1/16/21  2:50 AM  (GMT-08:00) To: NREL/SAM <SAM@noreply.github.com> Cc: Paul Gilman <cpaulgilman@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [NREL/SAM] Fix Value of RE macro (#501) 
@sjanzou commented on this pull request.

Please check that the alias name resolving (e.g. XCEL to Co Public Service Co of Colorado.


In src/urdb.h:
> @@ -128,8 +128,6 @@ class OpenEI
 	bool QueryUtilityCompanies(wxArrayString &names, wxString *err=NULL);
 	// search by zip code per email from Jay Huggins 1/9/15
 	bool QueryUtilityCompaniesbyZipcode(const wxString &zipcode, wxArrayString &names, wxString *err=NULL);
-	// resolve aliases in database per email from Jay Huggins 1/9/15
-	bool ResolveUtilityName(const wxString &name, wxString *urdb_name, wxString *err=NULL);

@cpaulgilman, is this no longer needed to resolve things like XCEL to CO Public Service, etc.? Does the search bring up the correct utilities? This was originally used to resolve multiple names for the same utility to a master utility name that actually contained all the rates. The other names were just aliases.

**Comment by brtietz** [comment]
@cpaulgilman I wanted to check in and make sure there were additional commits planned to fix the issue Steve pointed out. Let me know when this is ready for a second review.

**Comment by cpaulgilman** [comment]
@brtietz Thanks for checking in -- please do wait until I commit changes in response to @sjanzou's comments before reviewing this pull request.

File: src/urdb.h (hunk 2 above)
Comment (cpaulgilman) [reply src/urdb.h:132]: @sjanzou Utility name aliases work without the `ResolveUtilityName()` function. Not sure if the API changed since 2015 or if I am missing something. I added the utility name to the URDB Download Window so you can see the full utility company name after choosing a rate to verify the correct utility:

image

Comment (sjanzou) [reply src/urdb.h:132]: Great, the other troublesome utility was PG&E (Pacific Gas and Electric, Pacific Gas, Pacific Light) - are these resolved correctly?
I think after that and the painful UI merging - everything looks good to me!

File: src/invoke.cpp [hunk 3]
```diff
@@ -2377,29 +2377,23 @@ void fcall_urdb_list_utilities_by_zip_code(lk::invoke_t &cxt)
...
-	// first resolve aliases
-	if (!api.ResolveUtilityName(utility, &urdb_utility_name))
-	{
-		cxt.result().assign(-1);
-		return;
-	}
-
-	if (api.QueryUtilityRates(urdb_utility_name, ratelist))
-	{
+    if (api.QueryUtilityRates(utility, ratelist))
```
Comment (sjanzou) [inline src/invoke.cpp:2387]: Great that this is no longer necessary!

**Review by sjanzou — APPROVED** [review]
Lots of fun merging ahead!

File: src/urdb.h (hunk 2 above)
Comment (cpaulgilman) [reply src/urdb.h:132]: Here are ones that I tried that work: PG&E, PGE, Xcel. Pacific Gas and Electric, Pacific Gas, Pacific Light do not work (just typing "Pacific" gives a list of utility names that might match). The functionality in SAM is consistent with the URDB website "Browse rates by utility name" at https://openei.org/wiki/Utility_Rate_Database.

**Review by brtietz — APPROVED** [review]

File: deploy/runtime/defaults/Dish Stirling_Commercial.txt [hunk 4]
```diff
@@ -1,5 +1,5 @@
 1
-401
+402
 A_absorber
 1
```
[the remark this answers is not in the document]
Comment (cpaulgilman) [reply deploy/runtime/defaults/Dish Stirling_Commercial.txt:4]: I don't know...the same question goes for retired defaults. As of now they are out of date, so if we brought retired configs out of retirement, we would have to update the defaults as part of the process.
