### PR TITLE
Fix NSRDB Advanced Download TMY/TDY/TGY check boxes and file names

### LINKED ISSUE #1831: Advanced NSRDB downloads TMY displayed incorrectly
### Describe the bug

For the Advanced NSRDB downloads, TMY files in the list appear as "...-tmy_60_" with no year appended, and TMY auto select checkbox is not enabled.

image

### To Reproduce

1. On the Location and Resource page, check **Advanced download** and click **Download and add to library**.
2. Type "Denver, CO" for the location.
3. Click **Find**.

### Operating System and Version

 - macOS Sonoma 14.6
 - SAM 2023.12.17 r2 release candidate

### PR DESCRIPTION
**Pull request by cpaulgilman**
Fix #1831 

## Description

Year parameter returned by https://developer.nrel.gov/docs/solar/nsrdb/nsrdb_data_query/ may be a number (1998) or a string ("tmy-2020"). This PR checks the data type correctly before using it to control check box enabling and file names in NSRDB Advanced Download window.

To test:

1. Build Private version of SAM or edit private.h to add NREL Developer API key and email address.
2. Create a solar case and use NSRDB Advanced Window to generate list of available files. Check boxes for TMY, TGY, and TDY should be enabled and work correctly when those files are available, and file names for TMY, TGY, and TDY files should have strings like "tmy", "tmy-2020", "tgy-2021" appended as appropriate.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change modifies variables in existing compute modules. Please see [Checking for PySAM Incompatible API Changes](https://github.com/NREL/SAM/wiki/Checking-for-PySAM-Incompatible-API-Changes).

## Checklist:

If you have added a new compute module in a SSC pull request related to this one, be sure to check the [Process Requirements](https://github.com/NREL/SAM/wiki/Compute-modules-in-SAM).

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/nsrdb.cpp [hunk 1]
```diff
@@ -668,8 +669,12 @@ void NSRDBDialog::GetResources()
 			wxString displayName = output_list[i_outputs]["displayName"].GetString();
 
 			wxString year, interval;
+			// year may be a number like 2018 or a string like "tmy-2020"
 			if (links_list[i_links]["year"].IsInt())
-				year = wxString::Format("%d",links_list[i_links]["year"].GetInt());
+				year = wxString::Format("%d", links_list[i_links]["year"].GetInt());
+			else
+				year = links_list[i_links]["year"].GetString();
+			// interval should be a number like 5, 15, 30, 60
```
Comment (sjanzou) [inline src/nsrdb.cpp:677]: Thanks for updating for both integer and string values - working for me...

**Review by sjanzou — APPROVED** [review]
