### PR TITLE
Fix URDB rate downloads for Utility Companies with more than 500 rates #1848

### LINKED ISSUE #1848: Georgia Power PLL-11 Rate does not download tiers properly from URDB
### Describe the bug

https://apps.openei.org/IURDB/rate/view/5f73585d5457a3dc0b692d6f#3__Energy is a rate with mixed tiers, some with kWh and some with kWh/kW. SAM's URDB download code fails to pull the tiers for this rate

### To Reproduce

1. Open a behind the meter model such as PVWatts-Commercial
2. Download the rate linked above
3. Max usage tiers do not match the URDB implementation

### Expected behavior

Max usage tiers should match the URDB implementation

### Additional context

Tested on 2023.12.17r2. I expect this would have worked circa 2021 based on previous projects, but haven't tested it.

### PR DESCRIPTION
**Pull request by sjanzou**
Note that this issue also has export config and sam_api updates for the latest develop branch of ssc.

The issue was with Utilities with more than 500 rates - the RapidJSON array was asserting when going beyond 500 rates. The OpenEI::QueryUtilityRates method has been rewritten.

To test, randomly go through utility companies retrieving rates.

For example, Arizona Public Service Co has 241 rates
image

PG&E has 1196 rates
image

### CODE REVIEW

File: src/urdb.cpp [hunk 1]
```diff
@@ -384,102 +380,84 @@ bool OpenEI::QueryUtilityRates(const wxString &name, std::vector<RateInfo> &rate
...
-	if (reader.HasMember(L"items")) {
-		if (reader[L"items"].IsArray()) {
+	// change from UTF8 to UTF16 encoding to address unicode characters per SAM GitHub issue 1848
+	rapidjson::GenericDocument < rapidjson::UTF16<> > reader;
+	bool retrieve_rates = true;
+	bool ret = true;
+	// up to maxlimit rates added to rates vector
 
-			auto item_list = reader[L"items"].GetArray();
+	while (retrieve_rates) {
```
Comment (brtietz) [inline src/urdb.cpp:391]: This can create an infinite loop if `ret` gets flipped to false. (tested with "Tonopah Irrigation District")
I'd recommend changing this to `while (retrieve_rates && ret)`

**Review by brtietz — DISMISSED** [review]
This fixes the issue with PG&E, but creates a new issue if the utility has no valid rates. See comments in code for recommended fix.

**Comment by sjanzou** [comment]
Fix with suggested change from @brtietz 

Tested Tonopah
image

Arizona Public Service Co (with Unicode characters)
image

PG&E with 1196 rates
image

PGE with 311 rates
image

**Comment by cpaulgilman** [comment]
I wrote this LK script to test all utilities: [urdb-test.zip](https://github.com/user-attachments/files/17344627/urdb-test.zip)

SAM crashes when loading rates for "City of Buhl, Minnesota (Utility Company":

image

**Comment by sjanzou** [comment]
Run all 3970 utilities with script from @cpaulgilman without issue

0 of 3970: 3 Phases Energy Services has 1 rates
1 of 3970: 4-County Electric Power Assn has 2 rates
2 of 3970: A & N Electric Coop (Virginia) has 3 rates
3 of 3970: Accent Energy Holdings, LLC has 4 rates
4 of 3970: Accent Energy Holdings, LLC (New York) has 5 rates
5 of 3970: Accent Energy Holdings, LLC (Texas) has 6 rates
6 of 3970: Access Energy Coop has 7 rates
7 of 3970: ACE has 8 rates
8 of 3970: Adams Electric Coop has 9 rates
9 of 3970: Adams Electric Cooperative Inc has 10 rates
10 of 3970: Adams Rural Electric Coop, Inc has 11 rates
11 of 3970: Adams-Columbia Electric Coop has 12 rates
12 of 3970: Adrian Public Utilities Comm has 13 rates
13 of 3970: AEP Generating Company has 14 rates
14 of 3970: AEP Ohio has 15 rates
15 of 3970: AEP Texas Central Company has 16 rates
16 of 3970: AEP Texas North Company has 17 rates
17 of 3970: AES Eastern Energy LP has 18 rates
18 of 3970: AGC Division of APG Inc has 19 rates
19 of 3970: Agralite Electric Coop has 20 rates
20 of 3970: Aguila Irrigation District has 21 rates
21 of 3970: Agway Energy Services, LLC has 22 rates
22 of 3970: Aiken Electric Coop Inc has 23 rates
23 of 3970: Aitkin Public Utilities Comm has 24 rates
24 of 3970: Ajo Improvement Co has 25 rates
25 of 3970: Ak-Chin Electric Utility Authority has 26 rates
26 of 3970: Akiachak Native Community Electric Co has 27 rates
27 of 3970: Alabama Municipal Elec Authority has 28 rates
28 of 3970: Alabama Power Co has 29 rates
29 of 3970: Alamo Power District No 3 has 30 rates
30 of 3970: Alaska Electric & Energy Coop has 31 rates
31 of 3970: Alaska Electric Light&Power Co has 32 rates
32 of 3970: Alaska Energy Authority has 33 rates
33 of 3970: Alaska Power and Telephone Co has 34 rates
34 of 3970: Alaska Village Elec Coop, Inc has 35 rates
35 of 3970: Albany Water Gas & Light Comm has 36 rates
36 of 3970: Albemarle Electric Member Corp has 37 rates
37 of 3970: Albertville Municipal Utils Bd has 38 rates
38 of 3970: Alcorn County Elec Power Assn has 39 rates
39 of 3970: Alder Mutual Light Co, Inc has 40 rates
40 of 3970: Alfalfa Electric Coop, Inc has 41 rates
41 of 3970: Alfalfa Electric Coop, Inc (Kansas) has 42 rates
42 of 3970: Alger-Delta Coop Electric Assn has 43 rates
43 of 3970: Algoma Utility Comm has 44 rates
44 of 3970: Allamakee-Clayton El Coop, Inc has 45 rates
45 of 3970: Allegheny Electric Coop Inc has 46 rates
46 of 3970: Allegheny Energy Supply Co LLC has 47 rates
47 of 3970: Allegheny Energy Supply Co LLC (Maryland) has 48 rates
48 of 3970: Alliance Power Co LLC has 49 rates
49 of 3970: Alliance Star Energy LLC has 50 rates
50 of 3970: Alpena Power Co has 51 rates
51 of 3970: Altamaha Electric Member Corp has 52 rates
52 of 3970: Amana Society Service Co has 53 rates
53 of 3970: Ambit Energy, L.P. has 54 rates
54 of 3970: Ambit Energy, L.P. (Maryland) has 55 rates
55 of 3970: Ambit Energy, L.P. (New York) has 56 rates
56 of 3970: Ameren Energy Marketing has 57 rates
57 of 3970: Ameren Energy Marketing (Illinois) has 58 rates
58 of 3970: Ameren Illinois Company has 59 rates
59 of 3970: Ameren Missouri has 60 rates
60 of 3970: American Electric Power Co., Inc. has 61 rates
61 of 3970: American Mun Power-Ohio, Inc has 62 rates
62 of 3970: American PowerNet has 63 rates
63 of 3970: American PowerNet (District of Columbia) has 64 rates
64 of 3970: American PowerNet (Maine) has 65 rates
65 of 3970: American PowerNet (Maryland) has 66 rates
66 of 3970: American PowerNet (New Jersey) has 67 rates
67 of 3970: American Samoa Power Authority has 68 rates
68 of 3970: American Transmission Systems Inc has 69 rates
69 of 3970: AmeriPower LLC has 70 rates
70 of 3970: Amicalola Electric Member Corp has 71 rates
71 of 3970: Amigo Energy has 72 rates
72 of 3970: Anadarko Public Works Auth has 73 rates
73 of 3970: Anaheim Public Utilities has 74 rates
74 of 3970: Anaheim Utilities has 75 rates
75 of 3970: Anchorage Municipal Light and Power has 76 rates
76 of 3970: Aniak Light & Power Co Inc has 77 rates
77 of 3970: Anoka Electric Coop has 78 rates
78 of 3970: Anthracite Power & Light has 79 rates
79 of 3970: Anza Electric Coop Inc has 80 rates
80 of 3970: AP Holdings LLC has 81 rates
81 of 3970: AP Holdings LLC (New York) has 82 rates
82 of 3970: APN Starfirst, L.P. has 83 rates
83 of 3970: APN Starfirst, L.P. (Illinois) has 84 rates
84 of 3970: APN Starfirst, L.P. (Ohio) has 85 rates
85 of 3970: APN Starfirst, L.P. (Texas) has 86 rates
86 of 3970: APNA Energy has 87 rates
87 of 3970: Appalachian Electric Coop has 88 rates
88 of 3970: Appalachian Power Co has 89 rates
89 of 3970: Appalachian Power Co (Virginia) has 90 rates
90 of 3970: Appalachian Power Co (West Virginia) has 91 rates
91 of 3970: Applied Energy Inc has 92 rates
92 of 3970: Aquila Inc has 93 rates
93 of 3970: Aquila Inc (Missouri) has 94 rates
94 of 3970: Arab Electric Coop Inc has 95 rates
95 of 3970: ARCO Products Co-Watson has 96 rates
96 of 3970: Arizona Electric Pwr Coop Inc has 97 rates
97 of 3970: Arizona Power Authority has 98 rates
98 of 3970: Arizona Public Service Co has 99 rates
99 of 3970: Ark Valley Elec Coop Assn, Inc has 100 rates
100 of 3970: Arkansas Electric Coop Corp has 101 rates
101 of 3970: Arkansas River Power Authority has 102 rates
102 of 3970: Arkansas Valley Elec Coop Corp has 103 rates
103 of 3970: Arrowhead Electric Coop, Inc has 104 rates
104 of 3970: Ashley Chicot Elec Coop, Inc has 105 rates
105 of 3970: Associated Electric Coop, Inc has 106 rates
106 of 3970: Atchison-Holt Electric Coop has 107 rates
107 of 3970: Atchison-Holt Electric Coop (Iowa) has 108 rates
108 of 3970: Athens Utility Board has 109 rates
109 of 3970: Atlantic City Electric Co has 110 rates
110 of 3970: Atlantic Municipal Utilities has 111 rates
111 of 3970: Atmautluak Tribal Utilities has 112 rates
112 of 3970: Auburn Board of Public Works has 113 rates
113 of 3970: Austin Energy has 114 rates
114 of 3970: Avista Corp has 115 rates
115 of 3970: Avista Corp (Idaho) has 116 rates
116 of 3970: Avista Corp (Montana) has 117 rates
117 of 3970: Avista Turbine Power, Inc has 118 rates
118 of 3970: Backyard Farms Energy, LLC has 119 rates
119 of 3970: Badger Power Marketing Auth has 120 rates
120 of 3970: Bagley Public Utilities Comm has 121 rates
121 of 3970: Bailey County Elec Coop Assn has 122 rates
122 of 3970: Baldwin County El Member Corp has 123 rates
123 of 3970: Baltimore Gas & Electric Co has 124 rates
124 of 3970: Bamberg Board of Public Works has 125 rates
125 of 3970: Bancroft Municipal Utilities has 126 rates
126 of 3970: Bandera Electric Coop, Inc has 127 rates
127 of 3970: Bangor Hydro-Electric Co has 128 rates
128 of 3970: Barbourville Utility Comm has 129 rates
129 of 3970: BARC Electric Coop Inc has 130 rates
130 of 3970: Barron Electric Coop has 131 rates
131 of 3970: Barrow Utils & Elec Coop, Inc has 132 rates
132 of 3970: Barry Electric Coop has 133 rates
133 of 3970: Bartholomew County Rural E M C has 134 rates
134 of 3970: Bartlett Electric Coop, Inc has 135 rates
135 of 3970: Barton County Elec Coop, Inc has 136 rates
136 of 3970: Barton Village, Inc (Utility Company) has 137 rates
137 of 3970: Basin Electric Power Coop has 138 rates
138 of 3970: Basin Electric Power Coop (South Dakota) has 139 rates
139 of 3970: Bath Electric Gas & Water Sys has 140 rates
140 of 3970: Bayfield Electric Coop, Inc has 141 rates
141 of 3970: Bayfield Electric Coop, Inc (Michigan) has 142 rates
142 of 3970: Beaches Energy Services has 143 rates
143 of 3970: Bear Valley Electric Service has 144 rates
144 of 3970: Beartooth Electric Coop, Inc has 145 rates
145 of 3970: Beartooth Electric Coop, Inc (Wyoming) has 146 rates
146 of 3970: Beauregard Electric Coop, Inc has 147 rates
147 of 3970: Beaver City Corporation (Utility Company) has 148 rates
148 of 3970: Bedford Rural Elec Coop, Inc has 149 rates
149 of 3970: Beltrami Electric Coop, Inc has 150 rates
150 of 3970: Benton County has 151 rates
151 of 3970: Benton Rural Electric Assn has 152 rates
152 of 3970: Berkeley Electric Coop Inc has 153 rates
153 of 3970: Bethel Utilities Corp has 154 rates
154 of 3970: BGE has 155 rates
155 of 3970: Big Bend Electric Coop, Inc has 156 rates
156 of 3970: Big Country Electric Coop, Inc has 157 rates
157 of 3970: Big Flat Electric Coop Inc has 158 rates
158 of 3970: Big Horn County Elec Coop, Inc has 159 rates
159 of 3970: Big Horn Rural Electric Co has 160 rates
160 of 3970: Big Rivers Electric Corp has 161 rates
161 of 3970: Big Sandy Rural Elec Coop Corp has 162 rates
162 of 3970: Birch Creek Village Elec Util has 163 rates
163 of 3970: Blachly-Lane Cnty Coop El Assn has 164 rates
164 of 3970: Black Diamond Power Co has 165 rates
165 of 3970: Black Hills Electric Coop, Inc has 166 rates
166 of 3970: Black Hills Power Inc has 167 rates
167 of 3970: Black Hills Power Inc (Montana) has 168 rates
168 of 3970: Black Hills Power Inc (Wyoming) has 169 rates
169 of 3970: Black Hills/Colorado Elec.Utility Co. LP has 170 rates
170 of 3970: Black River Electric Coop has 171 rates
171 of 3970: Black River Electric Coop, Inc has 172 rates
172 of 3970: Black Warrior Elec Member Corp has 173 rates
173 of 3970: Block Island Power Co has 174 rates
174 of 3970: Bloom Energy 2009 PPA has 175 rates
175 of 3970: Bloomer Electric & Water Co has 176 rates
176 of 3970: Blue Earth-Nicollet-Faribault has 177 rates
177 of 3970: Blue Grass Energy Coop Corp has 178 rates
178 of 3970: Blue Ridge Elec Member Corp has 179 rates
179 of 3970: Blue Ridge Electric Coop Inc has 180 rates
180 of 3970: Blue Ridge Mountain E M C has 181 rates
181 of 3970: Blue Ridge Mountain E M C (North Carolina) has 182 rates
182 of 3970: Blue Star Energy Services has 183 rates
183 of 3970: Blue Star Energy Services (Maryland) has 184 rates
184 of 3970: Blue Star Energy Services (Pennsylvania) has 185 rates
185 of 3970: Bluebonnet Electric Coop, Inc has 186 rates
186 of 3970: Bluerock Energy, Inc. has 187 rates
187 of 3970: BlueStar has 188 rates
188 of 3970: Bluestem Electric Coop Inc has 189 rates
189 of 3970: Board of Water Electric & Communications has 190 rates
190 of 3970: Bolivar Energy Authority has 191 rates
191 of 3970: Bon Homme Yankton El Assn, Inc has 192 rates
192 of 3970: Bonneville Power Admin has 193 rates
193 of 3970: Bonneville Power Admin (Idaho) has 194 rates
194 of 3970: Bonneville Power Admin (Montana) has 195 rates
195 of 3970: Bonneville Power Admin (Washington) has 196 rates
196 of 3970: Boone County Rural EMC has 197 rates
197 of 3970: Boone Electric Coop has 198 rates
198 of 3970: Boone Valley Electric Coop has 199 rates
199 of 3970: Borough of Berlin, Pennsylvania (Utility Company) has 200 rates
200 of 3970: Borough of Blakely, Pennsylvania (Utility Company) has 201 rates
201 of 3970: Borough of Butler, New Jersey (Utility Company) has 202 rates
202 of 3970: Borough of Catawissa, Pennsylvania (Utility Company) has 203 rates
203 of 3970: Borough of Chambersburg, Pennsylvania (Utility Company) has 204 rates
204 of 3970: Borough of Duncannon, Pennsylvania (Utility Company) has 205 rates
205 of 3970: Borough of East Conemaugh, Pennsylvania (Utility Company) has 206 rates
206 of 3970: Borough of Ellwood City, Pennsylvania (Utility Company) has 207 rates
207 of 3970: Borough of Ephrata, Pennsylvania (Utility Company) has 208 rates
208 of 3970: Borough of Girard, Pennsylvania (Utility Company) has 209 rates
209 of 3970: Borough of Goldsboro, Pennsylvania (Utility Company) has 210 rates
210 of 3970: Borough of Grove City, Pennsylvania (Utility Company) has 211 rates
211 of 3970: Borough of Hatfield, Pennsylvania (Utility Company) has 212 rates
212 of 3970: Borough of Kutztown, Pennsylvania (Utility Company) has 213 rates
213 of 3970: Borough of Lansdale, Pennsylvania (Utility Company) has 214 rates
214 of 3970: Borough of Lavallette, New Jersey (Utility Company) has 215 rates
215 of 3970: Borough of Lehighton, Pennsylvania (Utility Company) has 216 rates
216 of 3970: Borough of Lewisberry, Pennsylvania (Utility Company) has 217 rates
217 of 3970: Borough of Madison, New Jersey (Utility Company) has 218 rates
218 of 3970: Borough of Middletown, Pennsylvania (Utility Company) has 219 rates
219 of 3970: Borough of Mifflinburg, Pennsylvania (Utility Company) has 220 rates
220 of 3970: Borough of Milltown, New Jersey (Utility Company) has 221 rates
221 of 3970: Borough of New Wilmington, Pennsylvania (Utility Company) has 222 rates
222 of 3970: Borough of Olyphant, Pennsylvania (Utility Company) has 223 rates
223 of 3970: Borough of Park Ridge, New Jersey (Utility Company) has 224 rates
224 of 3970: Borough of Pemberton, New Jersey (Utility Company) has 225 rates
225 of 3970: Borough of Perkasie, Pennsylvania (Utility Company) has 226 rates
226 of 3970: Borough of Pitcairn, Pennsylvania (Utility Company) has 227 rates
227 of 3970: Borough of Quakertown, Pennsylvania (Utility Company) has 228 rates
228 of 3970: Borough of Royalton, Pennsylvania (Utility Company) has 229 rates
229 of 3970: Borough of Schuylkill Haven, Pennsylvania (Utility Company) has 230 rates
230 of 3970: Borough of Smethport, Pennsylvania (Utility Company) has 231 rates
231 of 3970: Borough of South River, New Jersey (Utility Company) has 232 rates
232 of 3970: Borough of St Clair, Pennsylvania (Utility Company) has 233 rates
233 of 3970: Borough of Summerhill, Pennsylvania (Utility Company) has 234 rates
234 of 3970: Borough of Tarentum, Pennsylvania (Utility Company) has 235 rates
235 of 3970: Borough of Wampum, Pennsylvania (Utility Company) has 236 rates
236 of 3970: Borough of Watsontown, Pennsylvania (Utility Company) has 237 rates
237 of 3970: Borough of Weatherly, Pennsylvania (Utility Company) has 238 rates
238 of 3970: Borough of Zelienople, Pennsylvania (Utility Company) has 239 rates
239 of 3970: Boston Edison Company has 240 rates
240 of 3970: Bowie-Cass Electric Coop, Inc has 241 rates
241 of 3970: Bozrah Light & Power Company has 242 rates
242 of 3970: BP Energy Company has 243 rates
243 of 3970: BP Energy Company (Washington) has 244 rates
244 of 3970: Brainerd Public Utilities has 245 rates
245 of 3970: Brazos Electric Power Coop Inc has 246 rates
246 of 3970: Brazos River Authority has 247 rates
247 of 3970: Bremen Electric Light & Power Co has 248 rates
248 of 3970: Bridger Valley Elec Assn, Inc has 249 rates
249 of 3970: Bridger Valley Elec Assn, Inc (Utah) has 250 rates
250 of 3970: Brigham City Corporation (Utility Company) has 251 rates
251 of 3970: Brilliant Energy, LLC has 252 rates
252 of 3970: Bristol Virginia Utilities has 253 rates
253 of 3970: Broad River Electric Coop, Inc has 254 rates
254 of 3970: Broad River Electric Coop, Inc (North Carolina) has 255 rates
255 of 3970: Brodhead Water & Lighting Comm has 256 rates
256 of 3970: Brown County Rural Elec Assn has 257 rates
257 of 3970: Brown-Atchison E C A Inc has 258 rates
258 of 3970: Brownsville Public Utilities Board has 259 rates
259 of 3970: Brunswick Electric Member Corp has 260 rates
260 of 3970: Buckeye Power, Inc has 261 rates
261 of 3970: Buckeye Rural Elec Coop, Inc has 262 rates
262 of 3970: Buckeye Water C&D District has 263 rates
263 of 3970: Burke-Divide Electric Coop Inc has 264 rates
264 of 3970: Burt County Public Power Dist has 265 rates
265 of 3970: Butler County Rural Elec Coop has 266 rates
266 of 3970: Butler Public Power District has 267 rates
267 of 3970: Butler Rural El Coop Assn, Inc has 268 rates
268 of 3970: Butler Rural Electric Coop Inc has 269 rates
269 of 3970: Butte Electric Coop, Inc has 270 rates
270 of 3970: BWL has 271 rates
271 of 3970: C & L Electric Coop Corp has 272 rates
272 of 3970: Caddo Electric Coop, Inc has 273 rates
273 of 3970: Cairo Public Utility Company has 274 rates
274 of 3970: Calhoun County Elec Coop Assn has 275 rates
275 of 3970: California Department of Water Resources has 276 rates
276 of 3970: Callaway Electric Cooperative has 277 rates
277 of 3970: Calpine Corp-Agnews has 278 rates
278 of 3970: Calpine Energy Services LP has 279 rates
279 of 3970: Calpine Power America LLC has 280 rates
280 of 3970: Calpine Power America LLC (California) has 281 rates
281 of 3970: Calpine Power America LLC (Maine) has 282 rates
282 of 3970: Calpine Power Management LLC has 283 rates
283 of 3970: Cam Wal Electric Coop, Inc has 284 rates
284 of 3970: Canadian Valley Elec Coop, Inc has 285 rates
285 of 3970: Canby Utility Board has 286 rates
286 of 3970: Caney Fork Electric Coop, Inc has 287 rates
287 of 3970: Caney Valley El Coop Assn, Inc has 288 rates
288 of 3970: Cannelton Utilities has 289 rates
289 of 3970: Canoochee Electric Member Corp has 290 rates
290 of 3970: Canton Municipal Utilities has 291 rates
291 of 3970: Cape Hatteras Elec Member Corp has 292 rates
292 of 3970: Capital Electric Coop, Inc has 293 rates
293 of 3970: Carbon Power & Light, Inc has 294 rates
294 of 3970: Cardinal Cogen Inc has 295 rates
295 of 3970: Cargill Power Markets LLC has 296 rates
296 of 3970: Carroll County (Utility Company) has 297 rates
297 of 3970: Carroll County REMC has 298 rates
298 of 3970: Carroll Electric Coop Corp has 299 rates
299 of 3970: Carroll Electric Coop, Inc has 300 rates
300 of 3970: Carroll Electric Member Corp has 301 rates
301 of 3970: Carrollton Board of Public Wks has 302 rates
302 of 3970: Carteret-Craven El Member Corp has 303 rates
303 of 3970: Cascade Municipal Utilities has 304 rates
304 of 3970: Cass County Electric Coop Inc has 305 rates
305 of 3970: Cass Electric Coop has 306 rates
306 of 3970: Cavalier Rural Elec Coop, Inc has 307 rates
307 of 3970: CECG Maine, LLC has 308 rates
308 of 3970: CECG Maine, LLC (Maine) has 309 rates
309 of 3970: Cedar Falls Utilities has 310 rates
310 of 3970: Cedar-Knox Public Power Dist has 311 rates
311 of 3970: Cedarburg Light & Water Comm has 312 rates
312 of 3970: CEMC has 313 rates
313 of 3970: CenterPoint Energy has 314 rates
314 of 3970: CenterPoint Energy Houston Electric, LLC has 315 rates
315 of 3970: Central Alabama Electric Coop has 316 rates
316 of 3970: Central Electric Coop Inc has 317 rates
317 of 3970: Central Electric Coop, Inc has 318 rates
318 of 3970: Central Electric Coop, Inc (Pennsylvania) has 319 rates
319 of 3970: Central Electric Membership Corporation has 320 rates
320 of 3970: Central Electric Power Assn has 321 rates
321 of 3970: Central Electric Power Coop has 322 rates
322 of 3970: Central Electric Pwr Coop, Inc has 323 rates
323 of 3970: Central Florida Elec Coop, Inc has 324 rates
324 of 3970: Central Georgia El Member Corp has 325 rates
325 of 3970: Central Hudson Gas & Elec Corp has 326 rates
326 of 3970: Central Illinois Light Co has 327 rates
327 of 3970: Central Iowa Power Cooperative has 328 rates
328 of 3970: Central Lincoln People's Utility District has 329 rates
329 of 3970: Central Maine Power Co has 330 rates
330 of 3970: Central Minnesota Municipal Power Agency has 331 rates
331 of 3970: Central Missouri Elec Coop Inc has 332 rates
332 of 3970: Central Montana E Pwr Coop Inc has 333 rates
333 of 3970: Central Nebraska Pub P&I Dist has 334 rates
334 of 3970: Central New Mexico El Coop, Inc has 335 rates
335 of 3970: Central Power Elec Coop, Inc has 336 rates
336 of 3970: Central Rural Electric Cooperative, Inc has 337 rates
337 of 3970: Central Texas Elec Coop, Inc has 338 rates
338 of 3970: Central Valley Elec Coop, Inc has 339 rates
339 of 3970: Central Vermont Pub Serv Corp has 340 rates
340 of 3970: Central Virginia Electric Coop has 341 rates
341 of 3970: Central Wisconsin Elec Coop has 342 rates
342 of 3970: Champion Energy Services has 343 rates
343 of 3970: Champion Energy Services (Illinois) has 344 rates
344 of 3970: Champion Energy Services (Ohio) has 345 rates
345 of 3970: Champion Energy Services (Pennsylvania) has 346 rates
346 of 3970: Channel Energy Center has 347 rates
347 of 3970: Chariton Valley Elec Coop, Inc has 348 rates
348 of 3970: Charles Mix Electric Assn, Inc has 349 rates
349 of 3970: Cherokee County Elec Coop Assn has 350 rates
350 of 3970: Cherokee Electric Coop has 351 rates
351 of 3970: Cherry-Todd Electric Coop, Inc has 352 rates
352 of 3970: Cherryland Electric Coop Inc has 353 rates
353 of 3970: Cheyenne Light Fuel & Power Co has 354 rates
354 of 3970: Chickasaw Electric Coop, Inc has 355 rates
355 of 3970: Chillicothe Municipal Utils has 356 rates
356 of 3970: Chimney Rock Public Power Dist has 357 rates
357 of 3970: Chippewa Valley Electric Coop has 358 rates
358 of 3970: Chitina Electric Inc has 359 rates
359 of 3970: Choctaw Electric Coop Inc has 360 rates
360 of 3970: Choctawhatche Elec Coop, Inc has 361 rates
361 of 3970: Choptank Electric Coop, Inc has 362 rates
362 of 3970: Chugach Electric Assn Inc has 363 rates
363 of 3970: Cimarron Electric Coop has 364 rates
364 of 3970: CinCap IV, LLC has 365 rates
365 of 3970: CinCap V LLC has 366 rates
366 of 3970: Cinergy Capital & Trading, Inc has 367 rates
367 of 3970: Cirro Corporation has 368 rates
368 of 3970: Citizens Electric Co has 369 rates
369 of 3970: Citizens Electric Corporation has 370 rates
370 of 3970: City & Borough of Sitka (Utility Company) has 371 rates
371 of 3970: City & County of San Francisco (Utility Company) has 372 rates
372 of 3970: City of Abbeville, Louisiana (Utility Company) has 373 rates
373 of 3970: City of Abbeville, South Carolina (Utility Company) has 374 rates
374 of 3970: City of Aberdeen, Mississippi (Utility Company) has 375 rates
375 of 3970: City of Acworth, Georgia (Utility Company) has 376 rates
376 of 3970: City of Ada, Minnesota (Utility Company) has 377 rates
377 of 3970: City of Adel, Georgia (Utility Company) has 378 rates
378 of 3970: City of Afton, Iowa (Utility Company) has 379 rates
379 of 3970: City of Akron, Iowa (Utility Company) has 380 rates
380 of 3970: City of Akutan, Alaska (Utility Company) has 381 rates
381 of 3970: City of Alachua, Florida (Utility Company) has 382 rates
382 of 3970: City of Alameda, California (Utility Company) has 383 rates
383 of 3970: City of Albany, Illinois (Utility Company) has 384 rates
384 of 3970: City of Albany, Missouri (Utility Company) has 385 rates
385 of 3970: City of Albemarle, North Carolina (Utility Company) has 386 rates
386 of 3970: City of Albion, Idaho (Utility Company) has 387 rates
387 of 3970: City of Alcoa Utilities, Tennessee has 388 rates
388 of 3970: City of Alexander City, Alabama (Utility Company) has 389 rates
389 of 3970: City of Alexandria, Louisiana (Utility Company) has 390 rates
390 of 3970: City of Alexandria, Minnesota (Utility Company) has 391 rates
391 of 3970: City of Algona, Iowa (Utility Company) has 392 rates
392 of 3970: City of Allendale, Illinois (Utility Company) has 393 rates
393 of 3970: City of Alliance, Nebraska (Utility Company) has 394 rates
394 of 3970: City of Alma, Kansas (Utility Company) has 395 rates
395 of 3970: City of Alpha, Minnesota (Utility Company) has 396 rates
396 of 3970: City of Alta Vista, Iowa (Utility Company) has 397 rates
397 of 3970: City of Alta, Iowa (Utility Company) has 398 rates
398 of 3970: City of Altamont, Illinois (Utility Company) has 399 rates
399 of 3970: City of Altamont, Kansas (Utility Company) has 400 rates
400 of 3970: City of Alton, Iowa (Utility Company) has 401 rates
401 of 3970: City of Altus, Oklahoma (Utility Company) has 402 rates
402 of 3970: City of Alvarado, Minnesota (Utility Company) has 403 rates
403 of 3970: City of Ames, Iowa (Utility Company) has 404 rates
404 of 3970: City of Amherst, Ohio (Utility Company) has 405 rates
405 of 3970: City of Amory, Mississippi (Utility Company) has 406 rates
406 of 3970: City of Anaheim, California (Utility Company) has 407 rates
407 of 3970: City of Andalusia, Alabama (Utility Company) has 408 rates
408 of 3970: City of Anderson, Indiana (Utility Company) has 409 rates
409 of 3970: City of Anita, Iowa (Utility Company) has 410 rates
410 of 3970: City of Anoka, Minnesota (Utility Company) has 411 rates
411 of 3970: City of Ansley, Nebraska (Utility Company) has 412 rates
412 of 3970: City of Anthon, Iowa (Utility Company) has 413 rates
413 of 3970: City of Anthony, Kansas (Utility Company) has 414 rates
414 of 3970: City of Aplington, Iowa (Utility Company) has 415 rates
415 of 3970: City of Arapahoe, Nebraska (Utility Company) has 416 rates
416 of 3970: City of Arcadia, Kansas (Utility Company) has 417 rates
417 of 3970: City of Arcadia, Wisconsin (Utility Company) has 418 rates
418 of 3970: City of Arcanum, Ohio (Utility Company) has 419 rates
419 of 3970: City of Argyle, Wisconsin (Utility Company) has 420 rates
420 of 3970: City of Arlington, Minnesota (Utility Company) has 421 rates
421 of 3970: City of Arlington, South Dakota (Utility Company) has 422 rates
422 of 3970: City of Arma, Kansas (Utility Company) has 423 rates
423 of 3970: City of Ashland, Kansas (Utility Company) has 424 rates
424 of 3970: City of Ashland, Oregon (Utility Company) has 425 rates
425 of 3970: City of Aspen, Colorado (Utility Company) has 426 rates
426 of 3970: City of Athens, Alabama (Utility Company) has 427 rates
427 of 3970: City of Atka, Alaska (Utility Company) has 428 rates
428 of 3970: City of Attica, Kansas (Utility Company) has 429 rates
429 of 3970: City of Auburn, Indiana (Utility Company) has 430 rates
430 of 3970: City of Auburn, Iowa (Utility Company) has 431 rates
431 of 3970: City of Augusta, Arkansas (Utility Company) has 432 rates
432 of 3970: City of Augusta, Kansas (Utility Company) has 433 rates
433 of 3970: City of Aurelia, Iowa (Utility Company) has 434 rates
434 of 3970: City of Aurora, South Dakota (Utility Company) has 435 rates
435 of 3970: City of Austin, Minnesota (Utility Company) has 436 rates
436 of 3970: City of Ava, Missouri (Utility Company) has 437 rates
437 of 3970: City of Axtell, Kansas (Utility Company) has 438 rates
438 of 3970: City of Aztec, New Mexico (Utility Company) has 439 rates
439 of 3970: City of Azusa, California (Utility Company) has 440 rates
440 of 3970: City of Badger, South Dakota (Utility Company) has 441 rates
441 of 3970: City of Baldwin City, Kansas (Utility Company) has 442 rates
442 of 3970: City of Bandon, Oregon (Utility Company) has 443 rates
443 of 3970: City of Bangor, Wisconsin (Utility Company) has 444 rates
444 of 3970: City of Banning, California (Utility Company) has 445 rates
445 of 3970: City of Bardstown, Kentucky (Utility Company) has 446 rates
446 of 3970: City of Bardwell, Kentucky (Utility Company) has 447 rates
447 of 3970: City of Barnesville, Georgia (Utility Company) has 448 rates
448 of 3970: City of Barnesville, Minnesota (Utility Company) has 449 rates
449 of 3970: City of Barron, Wisconsin (Utility Company) has 450 rates
450 of 3970: City of Bartlett, Texas (Utility Company) has 451 rates
451 of 3970: City of Bartow, Florida (Utility Company) has 452 rates
452 of 3970: City of Bastrop, Texas (Utility Company) has 453 rates
453 of 3970: City of Batavia, Illinois (Utility Company) has 454 rates
454 of 3970: City of Battle Creek, Nebraska (Utility Company) has 455 rates
455 of 3970: City of Baudette, Minnesota (Utility Company) has 456 rates
456 of 3970: City of Bay City, Michigan (Utility Company) has 457 rates
457 of 3970: City of Bayard, Nebraska (Utility Company) has 458 rates
458 of 3970: City of Beatrice, Nebraska (Utility Company) has 459 rates
459 of 3970: City of Beaver City, Nebraska (Utility Company) has 460 rates
460 of 3970: City of Bedford, Virginia (Utility Company) has 461 rates
461 of 3970: City of Belleville, Kansas (Utility Company) has 462 rates
462 of 3970: City of Bellevue, Iowa (Utility Company) has 463 rates
463 of 3970: City of Bellville, Texas (Utility Company) has 464 rates
464 of 3970: City of Beloit, Kansas (Utility Company) has 465 rates
465 of 3970: City of Benham, Kentucky (Utility Company) has 466 rates
466 of 3970: City of Benkelman, Nebraska (Utility Company) has 467 rates
467 of 3970: City of Bennettsville, South Carolina (Utility Company) has 468 rates
468 of 3970: City of Benson, Minnesota (Utility Company) has 469 rates
469 of 3970: City of Benton, Arkansas (Utility Company) has 470 rates
470 of 3970: City of Benton, Kentucky (Utility Company) has 471 rates
471 of 3970: City of Bentonville, Arkansas (Utility Company) has 472 rates
472 of 3970: City of Berea Municipal Utility, Kentucky has 473 rates
473 of 3970: City of Beresford, South Dakota (Utility Company) has 474 rates
474 of 3970: City of Bessemer Utilities, Alabama has 475 rates
475 of 3970: City of Bethany, Missouri (Utility Company) has 476 rates
476 of 3970: City of Big Stone City, South Dakota (Utility Company) has 477 rates
477 of 3970: City of Bigelow, Iowa (Utility Company) has 478 rates
478 of 3970: City of Bigelow, Minnesota (Utility Company) has 479 rates
479 of 3970: City of Biggs, California (Utility Company) has 480 rates
480 of 3970: City of Biwabik, Minnesota (Utility Company) has 481 rates
481 of 3970: City of Black River Falls, Wisconsin (Utility Company) has 482 rates
482 of 3970: City of Blackwell, Oklahoma (Utility Company) has 483 rates
483 of 3970: City of Blaine, Washington (Utility Company) has 484 rates
484 of 3970: City of Blakely, Georgia (Utility Company) has 485 rates
485 of 3970: City of Blanding, Utah (Utility Company) has 486 rates
486 of 3970: City of Bloomfield, Iowa (Utility Company) has 487 rates
487 of 3970: City of Blooming Prairie, Minnesota (Utility Company) has 488 rates
488 of 3970: City of Blountstown, Florida (Utility Company) has 489 rates
489 of 3970: City of Blue Earth, Minnesota (Utility Company) has 490 rates
490 of 3970: City of Blue Hill, Nebraska (Utility Company) has 491 rates
491 of 3970: City of Blue Mound, Kansas (Utility Company) has 492 rates
492 of 3970: City of Bluffton, Indiana (Utility Company) has 493 rates
493 of 3970: City of Boerne, Texas (Utility Company) has 494 rates
494 of 3970: City of Bonners Ferry, Idaho (Utility Company) has 495 rates
495 of 3970: City of Boscobel, Wisconsin (Utility Company) has 496 rates
496 of 3970: City of Boulder, Nevada (Utility Company) has 497 rates
497 of 3970: City of Bountiful, Utah (Utility Company) has 498 rates
498 of 3970: City of Bowie, Texas (Utility Company) has 499 rates
499 of 3970: City of Bowling Green, Kentucky (Utility Company) has 500 rates
500 of 3970: City of Bowling Green, Ohio (Utility Company) has 501 rates
501 of 3970: City of Brady, Texas (Utility Company) has 502 rates
502 of 3970: City of Breckenridge, Minnesota (Utility Company) has 503 rates
503 of 3970: City of Breda, Iowa (Utility Company) has 504 rates
504 of 3970: City of Breese, Illinois (Utility Company) has 505 rates
505 of 3970: City of Brenham, Texas (Utility Company) has 506 rates
506 of 3970: City of Brewster, Minnesota (Utility Company) has 507 rates
507 of 3970: City of Bridgeport Utilities, Nebraska has 508 rates
508 of 3970: City of Bridgeport, Texas (Utility Company) has 509 rates
509 of 3970: City of Bristol, Tennessee (Utility Company) has 510 rates
510 of 3970: City of Broken Bow, Nebraska (Utility Company) has 511 rates
511 of 3970: City of Bronson, Kansas (Utility Company) has 512 rates
512 of 3970: City of Brookings, South Dakota (Utility Company) has 513 rates
513 of 3970: City of Brooklyn, Iowa (Utility Company) has 514 rates
514 of 3970: City of Brownfield, Texas (Utility Company) has 515 rates
515 of 3970: City of Brownsville, Tennessee (Utility Company) has 516 rates
516 of 3970: City of Brownton, Minnesota (Utility Company) has 517 rates
517 of 3970: City of Brundidge, Alabama (Utility Company) has 518 rates
518 of 3970: City of Bryan, Ohio (Utility Company) has 519 rates
519 of 3970: City of Bryan, Texas (Utility Company) has 520 rates
520 of 3970: City of Bryant, South Dakota (Utility Company) has 521 rates
521 of 3970: City of Buffalo, Iowa (Utility Company) has 522 rates
522 of 3970: City of Buffalo, Minnesota (Utility Company) has 523 rates
523 of 3970: City of Buford, Georgia (Utility Company) has 524 rates
524 of 3970: City of Buhl, Minnesota (Utility Company) has 525 rates
525 of 3970: City of Burbank Water and Power, California (Utility Company) has 526 rates
526 of 3970: City of Burke, South Dakota (Utility Company) has 527 rates
527 of 3970: City of Burley, Idaho (Utility Company) has 528 rates
528 of 3970: City of Burlingame, Kansas (Utility Company) has 529 rates
529 of 3970: City of Burlington, Colorado (Utility Company) has 530 rates
530 of 3970: City of Burlington, Kansas (Utility Company) has 531 rates
531 of 3970: City of Burlington, Oklahoma (Utility Company) has 532 rates
532 of 3970: City of Burlington-Electric, Vermont (Utility Company) has 533 rates
533 of 3970: City of Burnet, Texas (Utility Company) has 534 rates
534 of 3970: City of Burt, Iowa (Utility Company) has 535 rates
535 of 3970: City of Burwell, Nebraska (Utility Company) has 536 rates
536 of 3970: City of Bushnell, Florida (Utility Company) has 537 rates
537 of 3970: City of Bushnell, Illinois (Utility Company) has 538 rates
538 of 3970: City of Butler, Missouri (Utility Company) has 539 rates
539 of 3970: City of Cabool, Missouri (Utility Company) has 540 rates
540 of 3970: City of Cairo, Georgia (Utility Company) has 541 rates
541 of 3970: City of Caldwell, Texas (Utility Company) has 542 rates
542 of 3970: City of Caledonia, Minnesota (Utility Company) has 543 rates
543 of 3970: City of Calhoun, Georgia (Utility Company) has 544 rates
544 of 3970: City of Caliente, Nevada (Utility Company) has 545 rates
545 of 3970: City of California, Missouri (Utility Company) has 546 rates
546 of 3970: City of Callender, Iowa (Utility Company) has 547 rates
547 of 3970: City of Cambridge, Nebraska (Utility Company) has 548 rates
548 of 3970: City of Camden, South Carolina (Utility Company) has 549 rates
549 of 3970: City of Cameron, Missouri (Utility Company) has 550 rates
550 of 3970: City of Camilla, Georgia (Utility Company) has 551 rates
551 of 3970: City of Campbell, Missouri (Utility Company) has 552 rates
552 of 3970: City of Carlisle, Iowa (Utility Company) has 553 rates
553 of 3970: City of Carlyle, Illinois (Utility Company) has 554 rates
554 of 3970: City of Carmi, Illinois (Utility Company) has 555 rates
555 of 3970: City of Cartersville, Georgia (Utility Company) has 556 rates
556 of 3970: City of Carthage, Missouri (Utility Company) has 557 rates
557 of 3970: City of Cascade Locks, Oregon (Utility Company) has 558 rates
558 of 3970: City of Casey, Illinois (Utility Company) has 559 rates
559 of 3970: City of Castroville, Texas (Utility Company) has 560 rates
560 of 3970: City of Cavalier, North Dakota (Utility Company) has 561 rates
561 of 3970: City of Cawker City, Kansas (Utility Company) has 562 rates
562 of 3970: City of Celina, Ohio (Utility Company) has 563 rates
563 of 3970: City of Center, Colorado (Utility Company) has 564 rates
564 of 3970: City of Central City, Nebraska (Utility Company) has 565 rates
565 of 3970: City of Centralia, Kansas (Utility Company) has 566 rates
566 of 3970: City of Centralia, Missouri (Utility Company) has 567 rates
567 of 3970: City of Centralia, Washington (Utility Company) has 568 rates
568 of 3970: City of Ceylon, Minnesota (Utility Company) has 569 rates
569 of 3970: City of Chanute, Kansas (Utility Company) has 570 rates
570 of 3970: City of Chapman, Kansas (Utility Company) has 571 rates
571 of 3970: City of Chappell, Nebraska (Utility Company) has 572 rates
572 of 3970: City of Charlevoix, Michigan (Utility Company) has 573 rates
573 of 3970: City of Chaska, Minnesota (Utility Company) has 574 rates
574 of 3970: City of Chattahoochee, Florida (Utility Company) has 575 rates
575 of 3970: City of Chattanooga, Georgia (Utility Company) has 576 rates
576 of 3970: City of Chattanooga, Tennessee (Utility Company) has 577 rates
577 of 3970: City of Chefornak, Alaska (Utility Company) has 578 rates
578 of 3970: City of Cheney, Washington (Utility Company) has 579 rates
579 of 3970: City of Cherryville, North Carolina (Utility Company) has 580 rates
580 of 3970: City of Chetopa, Kansas (Utility Company) has 581 rates
581 of 3970: City of Chewelah, Washington (Utility Company) has 582 rates
582 of 3970: City of Chickamauga, Georgia (Utility Company) has 583 rates
583 of 3970: City of Chicopee, Massachusetts (Utility Company) has 584 rates
584 of 3970: City of Chignik, Alaska (Utility Company) has 585 rates
585 of 3970: City of Cimarron, Kansas (Utility Company) has 586 rates
586 of 3970: City of Claremore, Oklahoma (Utility Company) has 587 rates
587 of 3970: City of Clarksville, Tennessee (Utility Company) has 588 rates
588 of 3970: City of Clay Center, Kansas (Utility Company) has 589 rates
589 of 3970: City of Cleveland, Ohio (Utility Company) has 590 rates
590 of 3970: City of Cleveland, Tennessee (Utility Company) has 591 rates
591 of 3970: City of Clewiston, Florida (Utility Company) has 592 rates
592 of 3970: City of Clinton, Tennessee (Utility Company) has 593 rates
593 of 3970: City of Clintonville, Wisconsin (Utility Company) has 594 rates
594 of 3970: City of Cody, Wyoming (Utility Company) has 595 rates
595 of 3970: City of Coffeyville, Kansas (Utility Company) has 596 rates
596 of 3970: City of Coggon, Iowa (Utility Company) has 597 rates
597 of 3970: City of Colby, Kansas (Utility Company) has 598 rates
598 of 3970: City of Coleman, Texas (Utility Company) has 599 rates
599 of 3970: City of College Park, Georgia (Utility Company) has 600 rates
600 of 3970: City of College Station, Texas (Utility Company) has 601 rates
601 of 3970: City of Collins, Mississippi (Utility Company) has 602 rates
602 of 3970: City of Collinsville, Oklahoma (Utility Company) has 603 rates
603 of 3970: City of Colman, South Dakota (Utility Company) has 604 rates
604 of 3970: City of Colorado Springs, Colorado (Utility Company) has 605 rates
605 of 3970: City of Colton, California (Utility Company) has 606 rates
606 of 3970: City of Columbia City, Indiana (Utility Company) has 607 rates
607 of 3970: City of Columbia, Missouri (Utility Company) has 608 rates
608 of 3970: City of Columbiana, Ohio (Utility Company) has 609 rates
609 of 3970: City of Columbus, Mississippi (Utility Company) has 610 rates
610 of 3970: City of Columbus, Ohio (Utility Company) has 611 rates
611 of 3970: City of Columbus, Wisconsin (Utility Company) has 612 rates
612 of 3970: City of Comanche, Oklahoma (Utility Company) has 613 rates
613 of 3970: City of Commerce, Georgia (Utility Company) has 614 rates
614 of 3970: City of Concord, North Carolina (Utility Company) has 615 rates
615 of 3970: City of Cookeville, Tennessee (Utility Company) has 616 rates
616 of 3970: City of Coon Rapids, Iowa (Utility Company) has 617 rates
617 of 3970: City of Cordell, Oklahoma (Utility Company) has 618 rates
618 of 3970: City of Cornell, Wisconsin (Utility Company) has 619 rates
619 of 3970: City of Corning, Iowa (Utility Company) has 620 rates
620 of 3970: City of Corona, California (Utility Company) has 621 rates
621 of 3970: City of Corwith, Iowa (Utility Company) has 622 rates
622 of 3970: City of Coulee Dam, Washington (Utility Company) has 623 rates
623 of 3970: City of Courtland, Alabama (Utility Company) has 624 rates
624 of 3970: City of Covington, Georgia (Utility Company) has 625 rates
625 of 3970: City of Covington, Indiana (Utility Company) has 626 rates
626 of 3970: City of Covington, Tennessee (Utility Company) has 627 rates
627 of 3970: City of Crane, Missouri (Utility Company) has 628 rates
628 of 3970: City of Crete, Nebraska (Utility Company) has 629 rates
629 of 3970: City of Croswell, Michigan (Utility Company) has 630 rates
630 of 3970: City of Crystal Falls, Michigan (Utility Company) has 631 rates
631 of 3970: City of Cuba City, Wisconsin (Utility Company) has 632 rates
632 of 3970: City of Cuba, Missouri (Utility Company) has 633 rates
633 of 3970: City of Cuero, Texas (Utility Company) has 634 rates
634 of 3970: City of Cumberland, Wisconsin (Utility Company) has 635 rates
635 of 3970: City of Curtis, Nebraska (Utility Company) has 636 rates
636 of 3970: City of Cushing, Oklahoma (Utility Company) has 637 rates
637 of 3970: City of Custar, Ohio (Utility Company) has 638 rates
638 of 3970: City of Cuyahoga Falls, Ohio (Utility Company) has 639 rates
639 of 3970: City of Danville, Iowa (Utility Company) has 640 rates
640 of 3970: City of Danville, Virginia (Utility Company) has 641 rates
641 of 3970: City of David City, Nebraska (Utility Company) has 642 rates
642 of 3970: City of Dayton, Iowa (Utility Company) has 643 rates
643 of 3970: City of Dayton, Tennessee (Utility Company) has 644 rates
644 of 3970: City of Deaver, Wyoming (Utility Company) has 645 rates
645 of 3970: City of Declo, Idaho (Utility Company) has 646 rates
646 of 3970: City of Delta, Colorado (Utility Company) has 647 rates
647 of 3970: City of Denison, Iowa (Utility Company) has 648 rates
648 of 3970: City of Denton, Texas (Utility Company) has 649 rates
649 of 3970: City of Denver, Iowa (Utility Company) has 650 rates
650 of 3970: City of Deshler, Nebraska (Utility Company) has 651 rates
651 of 3970: City of Detroit Lakes, Minnesota (Utility Company) has 652 rates
652 of 3970: City of Detroit, Michigan (Utility Company) has 653 rates
653 of 3970: City of Dickson, Tennessee (Utility Company) has 654 rates
654 of 3970: City of Dighton, Kansas (Utility Company) has 655 rates
655 of 3970: City of Dike, Iowa (Utility Company) has 656 rates
656 of 3970: City of Doerun, Georgia (Utility Company) has 657 rates
657 of 3970: City of Dothan, Alabama (Utility Company) has 658 rates
658 of 3970: City of Douglas, Georgia (Utility Company) has 659 rates
659 of 3970: City of Dover, Delaware (Utility Company) has 660 rates
660 of 3970: City of Dover, Ohio (Utility Company) has 661 rates
661 of 3970: City of Dowagiac, Michigan (Utility Company) has 662 rates
662 of 3970: City of Drain, Oregon (Utility Company) has 663 rates
663 of 3970: City of Due West, South Carolina (Utility Company) has 664 rates
664 of 3970: City of Duncan, Oklahoma (Utility Company) has 665 rates
665 of 3970: City of Dunnell, Minnesota (Utility Company) has 666 rates
666 of 3970: City of Durant, Iowa (Utility Company) has 667 rates
667 of 3970: City of Durant, Mississippi (Utility Company) has 668 rates
668 of 3970: City of Dyersburg, Tennessee (Utility Company) has 669 rates
669 of 3970: City of Dysart, Iowa (Utility Company) has 670 rates
670 of 3970: City of Eagle River, Wisconsin (Utility Company) has 671 rates
671 of 3970: City of Earlville, Iowa (Utility Company) has 672 rates
672 of 3970: City of East Grand Forks, Minnesota (Utility Company) has 673 rates
673 of 3970: City of East Point, Georgia (Utility Company) has 674 rates
674 of 3970: City of Easton, Missouri (Utility Company) has 675 rates
675 of 3970: City of Eaton Rapids, Michigan (Utility Company) has 676 rates
676 of 3970: City of Edgar, Nebraska (Utility Company) has 677 rates
677 of 3970: City of Edmond, Oklahoma (Utility Company) has 678 rates
678 of 3970: City of Eitzen, Minnesota (Utility Company) has 679 rates
679 of 3970: City of El Dorado Springs, Missouri (Utility Company) has 680 rates
680 of 3970: City of Elba, Alabama (Utility Company) has 681 rates
681 of 3970: City of Elberton, Georgia (Utility Company) has 682 rates
682 of 3970: City of Elbow Lake, Minnesota (Utility Company) has 683 rates
683 of 3970: City of Eldorado, Oklahoma (Utility Company) has 684 rates
684 of 3970: City of Electra, Texas (Utility Company) has 685 rates
685 of 3970: City of Elfin Cove, Alaska (Utility Company) has 686 rates
686 of 3970: City of Elizabeth City, North Carolina (Utility Company) has 687 rates
687 of 3970: City of Elizabethton, Tennessee (Utility Company) has 688 rates
688 of 3970: City of Elk Point, South Dakota (Utility Company) has 689 rates
689 of 3970: City of Elk River, Minnesota (Utility Company) has 690 rates
690 of 3970: City of Elkhorn, Wisconsin (Utility Company) has 691 rates
691 of 3970: City of Ellaville, Georgia (Utility Company) has 692 rates
692 of 3970: City of Ellensburg, Washington (Utility Company) has 693 rates
693 of 3970: City of Ellinwood, Kansas (Utility Company) has 694 rates
694 of 3970: City of Ellsworth, Iowa (Utility Company) has 695 rates
695 of 3970: City of Elroy, Wisconsin (Utility Company) has 696 rates
696 of 3970: City of Elsmore, Kansas (Utility Company) has 697 rates
697 of 3970: City of Elwood, Kansas (Utility Company) has 698 rates
698 of 3970: City of Ely, Minnesota (Utility Company) has 699 rates
699 of 3970: City of Enterprise, Kansas (Utility Company) has 700 rates
700 of 3970: City of Enterprise, Utah (Utility Company) has 701 rates
701 of 3970: City of Ephraim, Utah (Utility Company) has 702 rates
702 of 3970: City of Erath, Louisiana (Utility Company) has 703 rates
703 of 3970: City of Erie, Kansas (Utility Company) has 704 rates
704 of 3970: City of Escanaba, Michigan (Utility Company) has 705 rates
705 of 3970: City of Escondido, California (Utility Company) has 706 rates
706 of 3970: City of Estelline, South Dakota (Utility Company) has 707 rates
707 of 3970: City of Estherville, Iowa (Utility Company) has 708 rates
708 of 3970: City of Etowah, Tennessee (Utility Company) has 709 rates
709 of 3970: City of Eudora, Kansas (Utility Company) has 710 rates
710 of 3970: City of Eugene, Oregon (Utility Company) has 711 rates
711 of 3970: City of Evansville, Wisconsin (Utility Company) has 712 rates
712 of 3970: City of Evergreen, Alabama (Utility Company) has 713 rates
713 of 3970: City of Fairbank, Iowa (Utility Company) has 714 rates
714 of 3970: City of Fairburn, Georgia (Utility Company) has 715 rates
715 of 3970: City of Fairbury, Nebraska (Utility Company) has 716 rates
716 of 3970: City of Fairfax, Minnesota (Utility Company) has 717 rates
717 of 3970: City of Fairfield, Illinois (Utility Company) has 718 rates
718 of 3970: City of Fairhope, Alabama (Utility Company) has 719 rates
719 of 3970: City of Fairview, Oklahoma (Utility Company) has 720 rates
720 of 3970: City of Faith, South Dakota (Utility Company) has 721 rates
721 of 3970: City of Fallon, Nevada (Utility Company) has 722 rates
722 of 3970: City of Falls City, Nebraska (Utility Company) has 723 rates
723 of 3970: City of Falmouth, Kentucky (Utility Company) has 724 rates
724 of 3970: City of Farmer City, Illinois (Utility Company) has 725 rates
725 of 3970: City of Farmersville, Texas (Utility Company) has 726 rates
726 of 3970: City of Farmington, Missouri (Utility Company) has 727 rates
727 of 3970: City of Farmington, New Mexico (Utility Company) has 728 rates
728 of 3970: City of Farnhamville, Iowa (Utility Company) has 729 rates
729 of 3970: City of Fayette, Missouri (Utility Company) has 730 rates
730 of 3970: City of Fayetteville, Tennessee (Utility Company) has 731 rates
731 of 3970: City of Fennimore, Wisconsin (Utility Company) has 732 rates
732 of 3970: City of Flandreau, South Dakota (Utility Company) has 733 rates
733 of 3970: City of Flatonia, Texas (Utility Company) has 734 rates
734 of 3970: City of Flora, Illinois (Utility Company) has 735 rates
735 of 3970: City of Florence, Alabama (Utility Company) has 736 rates
736 of 3970: City of Floresville, Texas (Utility Company) has 737 rates
737 of 3970: City of Floydada, Texas (Utility Company) has 738 rates
738 of 3970: City of Fonda, Iowa (Utility Company) has 739 rates
739 of 3970: City of Fontanelle, Iowa (Utility Company) has 740 rates
740 of 3970: City of Forest City, Iowa (Utility Company) has 741 rates
741 of 3970: City of Forest Grove, Oregon (Utility Company) has 742 rates
742 of 3970: City of Forsyth, Georgia (Utility Company) has 743 rates
743 of 3970: City of Fort Collins, Colorado (Utility Company) has 744 rates
744 of 3970: City of Fort Meade, Florida (Utility Company) has 745 rates
745 of 3970: City of Fort Morgan, Colorado (Utility Company) has 746 rates
746 of 3970: City of Fort Pierre, South Dakota (Utility Company) has 747 rates
747 of 3970: City of Fosston, Minnesota (Utility Company) has 748 rates
748 of 3970: City of Fountain, Colorado (Utility Company) has 749 rates
749 of 3970: City of Frankfort, Indiana (Utility Company) has 750 rates
750 of 3970: City of Frankfort, Kentucky (Utility Company) has 751 rates
751 of 3970: City of Franklin, Kentucky (Utility Company) has 752 rates
752 of 3970: City of Franklin, Nebraska (Utility Company) has 753 rates
753 of 3970: City of Franklin, Virginia (Utility Company) has 754 rates
754 of 3970: City of Frederick, Oklahoma (Utility Company) has 755 rates
755 of 3970: City of Fredericksburg, Iowa (Utility Company) has 756 rates
756 of 3970: City of Fredericksburg, Texas (Utility Company) has 757 rates
757 of 3970: City of Fredericktown, Missouri (Utility Company) has 758 rates
758 of 3970: City of Fredonia, Arizona (Utility Company) has 759 rates
759 of 3970: City of Fredonia, Kansas (Utility Company) has 760 rates
760 of 3970: City of Fremont, Nebraska (Utility Company) has 761 rates
761 of 3970: City of Friend, Nebraska (Utility Company) has 762 rates
762 of 3970: City of Fulton, Kentucky (Utility Company) has 763 rates
763 of 3970: City of Fulton, Missouri (Utility Company) has 764 rates
764 of 3970: City of Gaffney, South Carolina (Utility Company) has 765 rates
765 of 3970: City of Galion, Ohio (Utility Company) has 766 rates
766 of 3970: City of Gallatin, Missouri (Utility Company) has 767 rates
767 of 3970: City of Gallatin, Tennessee (Utility Company) has 768 rates
768 of 3970: City of Gallup, New Mexico (Utility Company) has 769 rates
769 of 3970: City of Galt, Missouri (Utility Company) has 770 rates
770 of 3970: City of Galva, Kansas (Utility Company) has 771 rates
771 of 3970: City of Garden City, Kansas (Utility Company) has 772 rates
772 of 3970: City of Gardner, Kansas (Utility Company) has 773 rates
773 of 3970: City of Garland, Texas (Utility Company) has 774 rates
774 of 3970: City of Garnett, Kansas (Utility Company) has 775 rates
775 of 3970: City of Garrett, Indiana (Utility Company) has 776 rates
776 of 3970: City of Gas City, Indiana (Utility Company) has 777 rates
777 of 3970: City of Gastonia, North Carolina (Utility Company) has 778 rates
778 of 3970: City of Geary, Oklahoma (Utility Company) has 779 rates
779 of 3970: City of Geneseo, Illinois (Utility Company) has 780 rates
780 of 3970: City of Geneva, Illinois (Utility Company) has 781 rates
781 of 3970: City of Georgetown, South Carolina (Utility Company) has 782 rates
782 of 3970: City of Georgetown, Texas (Utility Company) has 783 rates
783 of 3970: City of Gering, Nebraska (Utility Company) has 784 rates
784 of 3970: City of Giddings, Texas (Utility Company) has 785 rates
785 of 3970: City of Gilbert, Minnesota (Utility Company) has 786 rates
786 of 3970: City of Gillette, Wyoming (Utility Company) has 787 rates
787 of 3970: City of Gilman City, Missouri (Utility Company) has 788 rates
788 of 3970: City of Giltner, Nebraska (Utility Company) has 789 rates
789 of 3970: City of Girard, Kansas (Utility Company) has 790 rates
790 of 3970: City of Gladstone, Michigan (Utility Company) has 791 rates
791 of 3970: City of Glasco, Kansas (Utility Company) has 792 rates
792 of 3970: City of Glasgow, Kentucky (Utility Company) has 793 rates
793 of 3970: City of Glen Elder, Kansas (Utility Company) has 794 rates
794 of 3970: City of Glendale, California (Utility Company) has 795 rates
795 of 3970: City of Glenwood Springs, Colorado (Utility Company) has 796 rates
796 of 3970: City of Glidden, Iowa (Utility Company) has 797 rates
797 of 3970: City of Goldsmith, Texas (Utility Company) has 798 rates
798 of 3970: City of Goldthwaite, Texas (Utility Company) has 799 rates
799 of 3970: City of Gonzales, Texas (Utility Company) has 800 rates
800 of 3970: City of Goodland, Kansas (Utility Company) has 801 rates
801 of 3970: City of Gothenburg, Nebraska (Utility Company) has 802 rates
802 of 3970: City of Graettinger, Iowa (Utility Company) has 803 rates
803 of 3970: City of Grafton, North Dakota (Utility Company) has 804 rates
804 of 3970: City of Granbury, Texas (Utility Company) has 805 rates
805 of 3970: City of Grand Haven, Michigan (Utility Company) has 806 rates
806 of 3970: City of Grand Island, Nebraska (Utility Company) has 807 rates
807 of 3970: City of Grand Junction, Iowa (Utility Company) has 808 rates
808 of 3970: City of Grand Marais, Minnesota (Utility Company) has 809 rates
809 of 3970: City of Granite Falls, Minnesota (Utility Company) has 810 rates
810 of 3970: City of Granite, Oklahoma (Utility Company) has 811 rates
811 of 3970: City of Grant, Nebraska (Utility Company) has 812 rates
812 of 3970: City of Grantville, Georgia (Utility Company) has 813 rates
813 of 3970: City of Green Cove Springs, Florida (Utility Company) has 814 rates
814 of 3970: City of Greendale, Indiana (Utility Company) has 815 rates
815 of 3970: City of Greeneville, Tennessee (Utility Company) has 816 rates
816 of 3970: City of Greenfield, Indiana (Utility Company) has 817 rates
817 of 3970: City of Greenfield, Iowa (Utility Company) has 818 rates
818 of 3970: City of Greensburg, Kansas (Utility Company) has 819 rates
819 of 3970: City of Greenville,, Texas (Utility Company) has 820 rates
820 of 3970: City of Gridley, California (Utility Company) has 821 rates
821 of 3970: City of Griffin, Georgia (Utility Company) has 822 rates
822 of 3970: City of Groton, South Dakota (Utility Company) has 823 rates
823 of 3970: City of Grove City, Minnesota (Utility Company) has 824 rates
824 of 3970: City of Gunnison, Colorado (Utility Company) has 825 rates
825 of 3970: City of Guttenberg, Iowa (Utility Company) has 826 rates
826 of 3970: City of Hagerstown, Indiana (Utility Company) has 827 rates
827 of 3970: City of Hallettsville, Texas (Utility Company) has 828 rates
828 of 3970: City of Halstad, Minnesota (Utility Company) has 829 rates
829 of 3970: City of Hamilton, Ohio (Utility Company) has 830 rates
830 of 3970: City of Hampton, Georgia (Utility Company) has 831 rates
831 of 3970: City of Hannibal, Missouri (Utility Company) has 832 rates
832 of 3970: City of Harbor Springs, Michigan (Utility Company) has 833 rates
833 of 3970: City of Harlan, Iowa (Utility Company) has 834 rates
834 of 3970: City of Harmony, Minnesota (Utility Company) has 835 rates
835 of 3970: City of Harriman, Tennessee (Utility Company) has 836 rates
836 of 3970: City of Harrisonburg, Virginia (Utility Company) has 837 rates
837 of 3970: City of Harrisonville, Missouri (Utility Company) has 838 rates
838 of 3970: City of Hart Hydro, Michigan (Utility Company) has 839 rates
839 of 3970: City of Hartford, Alabama (Utility Company) has 840 rates
840 of 3970: City of Hartley, Iowa (Utility Company) has 841 rates
841 of 3970: City of Hartselle, Alabama (Utility Company) has 842 rates
842 of 3970: City of Hastings, Nebraska (Utility Company) has 843 rates
843 of 3970: City of Haven, Kansas (Utility Company) has 844 rates
844 of 3970: City of Hawarden, Iowa (Utility Company) has 845 rates
845 of 3970: City of Healdsburg, California (Utility Company) has 846 rates
846 of 3970: City of Hearne, Texas (Utility Company) has 847 rates
847 of 3970: City of Hebron, Nebraska (Utility Company) has 848 rates
848 of 3970: City of Hecla, South Dakota (Utility Company) has 849 rates
849 of 3970: City of Helper, Utah (Utility Company) has 850 rates
850 of 3970: City of Hemphill, Texas (Utility Company) has 851 rates
851 of 3970: City of Hempstead, Texas (Utility Company) has 852 rates
852 of 3970: City of Henning, Minnesota (Utility Company) has 853 rates
853 of 3970: City of Herington, Kansas (Utility Company) has 854 rates
854 of 3970: City of Hermann, Missouri (Utility Company) has 855 rates
855 of 3970: City of Hermiston, Oregon (Utility Company) has 856 rates
856 of 3970: City of Herndon, Kansas (Utility Company) has 857 rates
857 of 3970: City of Hertford, North Carolina (Utility Company) has 858 rates
858 of 3970: City of Heyburn, Idaho (Utility Company) has 859 rates
859 of 3970: City of Hickman, Kentucky (Utility Company) has 860 rates
860 of 3970: City of Hickman, Nebraska (Utility Company) has 861 rates
861 of 3970: City of Higginsville, Missouri (Utility Company) has 862 rates
862 of 3970: City of Highland, Illinois (Utility Company) has 863 rates
863 of 3970: City of Highlands, North Carolina (Utility Company) has 864 rates
864 of 3970: City of Hill City, Kansas (Utility Company) has 865 rates
865 of 3970: City of Hillsboro, Kansas (Utility Company) has 866 rates
866 of 3970: City of Hillsboro, North Dakota (Utility Company) has 867 rates
867 of 3970: City of Hingham, Massachusetts (Utility Company) has 868 rates
868 of 3970: City of Hinton, Iowa (Utility Company) has 869 rates
869 of 3970: City of Hogansville, Georgia (Utility Company) has 870 rates
870 of 3970: City of Hoisington, Kansas (Utility Company) has 871 rates
871 of 3970: City of Holdrege, Nebraska (Utility Company) has 872 rates
872 of 3970: City of Holland, Michigan (Utility Company) has 873 rates
873 of 3970: City of Holly Springs, Mississippi (Utility Company) has 874 rates
874 of 3970: City of Holton, Kansas (Utility Company) has 875 rates
875 of 3970: City of Holyoke, Colorado (Utility Company) has 876 rates
876 of 3970: City of Holyoke, Massachusetts (Utility Company) has 877 rates
877 of 3970: City of Holyrood, Kansas (Utility Company) has 878 rates
878 of 3970: City of Homestead, Florida (Utility Company) has 879 rates
879 of 3970: City of Hominy, Oklahoma (Utility Company) has 880 rates
880 of 3970: City of Hondo, Texas (Utility Company) has 881 rates
881 of 3970: City of Hope, Arkansas (Utility Company) has 882 rates
882 of 3970: City of Hope, North Dakota (Utility Company) has 883 rates
883 of 3970: City of Hopkinsville, Kentucky (Utility Company) has 884 rates
884 of 3970: City of Hopkinton, Iowa (Utility Company) has 885 rates
885 of 3970: City of Horton, Kansas (Utility Company) has 886 rates
886 of 3970: City of Houston, Missouri (Utility Company) has 887 rates
887 of 3970: City of Howard, South Dakota (Utility Company) has 888 rates
888 of 3970: City of Hubbard, Ohio (Utility Company) has 889 rates
889 of 3970: City of Hubbell, Nebraska (Utility Company) has 890 rates
890 of 3970: City of Hudson, Ohio (Utility Company) has 891 rates
891 of 3970: City of Hugoton, Kansas (Utility Company) has 892 rates
892 of 3970: City of Humboldt, Tennessee (Utility Company) has 893 rates
893 of 3970: City of Hunnewell, Missouri (Utility Company) has 894 rates
894 of 3970: City of Huntingburg, Indiana (Utility Company) has 895 rates
895 of 3970: City of Huntsville, Alabama (Utility Company) has 896 rates
896 of 3970: City of Idaho Falls, Idaho (Utility Company) has 897 rates
897 of 3970: City of Imperial, Nebraska (Utility Company) has 898 rates
898 of 3970: City of Independence, Iowa (Utility Company) has 899 rates
899 of 3970: City of Independence, Missouri (Utility Company) has 900 rates
900 of 3970: City of Indianola, Nebraska (Utility Company) has 901 rates
901 of 3970: City of Iola, Kansas (Utility Company) has 902 rates
902 of 3970: City of Isabel, Kansas (Utility Company) has 903 rates
903 of 3970: City of Itta Bena, Mississippi (Utility Company) has 904 rates
904 of 3970: City of Iuka, Kansas (Utility Company) has 905 rates
905 of 3970: City of Jackson, Georgia (Utility Company) has 906 rates
906 of 3970: City of Jackson, Minnesota (Utility Company) has 907 rates
907 of 3970: City of Jackson, Missouri (Utility Company) has 908 rates
908 of 3970: City of Jackson, Ohio (Utility Company) has 909 rates
909 of 3970: City of Jackson, Tennessee (Utility Company) has 910 rates
910 of 3970: City of Janesville, Minnesota (Utility Company) has 911 rates
911 of 3970: City of Jasper, Indiana (Utility Company) has 912 rates
912 of 3970: City of Jasper, Texas (Utility Company) has 913 rates
913 of 3970: City of Jellico, Tennessee (Utility Company) has 914 rates
914 of 3970: City of Jetmore, Kansas (Utility Company) has 915 rates
915 of 3970: City of Jewett City, Connecticut (Utility Company) has 916 rates
916 of 3970: City of Johnson City, Tennessee (Utility Company) has 917 rates
917 of 3970: City of Johnson, Kansas (Utility Company) has 918 rates
918 of 3970: City of Jonesville, Louisiana (Utility Company) has 919 rates
919 of 3970: City of Julesburg, Colorado (Utility Company) has 920 rates
920 of 3970: City of Kahoka, Missouri (Utility Company) has 921 rates
921 of 3970: City of Kandiyohi, Minnesota (Utility Company) has 922 rates
922 of 3970: City of Kansas City, Kansas (Utility Company) has 923 rates
923 of 3970: City of Kaplan, Louisiana (Utility Company) has 924 rates
924 of 3970: City of Kasota, Minnesota (Utility Company) has 925 rates
925 of 3970: City of Kasson, Minnesota (Utility Company) has 926 rates
926 of 3970: City of Kaukauna, Wisconsin (Utility Company) has 927 rates
927 of 3970: City of Kennett, Missouri (Utility Company) has 928 rates
928 of 3970: City of Key West, Florida (Utility Company) has 929 rates
929 of 3970: City of Kiel, Wisconsin (Utility Company) has 930 rates
930 of 3970: City of Kimball, Nebraska (Utility Company) has 931 rates
931 of 3970: City of Kimballton, Iowa (Utility Company) has 932 rates
932 of 3970: City of King Cove, Alaska (Utility Company) has 933 rates
933 of 3970: City of Kingfisher, Oklahoma (Utility Company) has 934 rates
934 of 3970: City of Kingman, Kansas (Utility Company) has 935 rates
935 of 3970: City of Kings Mountain, North Carolina (Utility Company) has 936 rates
936 of 3970: City of Kinston, North Carolina (Utility Company) has 937 rates
937 of 3970: City of Kiowa, Kansas (Utility Company) has 938 rates
938 of 3970: City of Kirkwood, Missouri (Utility Company) has 939 rates
939 of 3970: City of Kosciusko, Mississippi (Utility Company) has 940 rates
940 of 3970: City of La Crosse, Kansas (Utility Company) has 941 rates
941 of 3970: City of La Grange, Georgia (Utility Company) has 942 rates
942 of 3970: City of La Grange, Texas (Utility Company) has 943 rates
943 of 3970: City of La Harpe, Kansas (Utility Company) has 944 rates
944 of 3970: City of La Junta, Colorado (Utility Company) has 945 rates
945 of 3970: City of La Plata, Missouri (Utility Company) has 946 rates
946 of 3970: City of Lafayette, Alabama (Utility Company) has 947 rates
947 of 3970: City of LaFayette, Georgia (Utility Company) has 948 rates
948 of 3970: City of Lafayette, Louisiana (Utility Company) has 949 rates
949 of 3970: City of LaFollette, Tennessee (Utility Company) has 950 rates
950 of 3970: City of Lake City, Minnesota (Utility Company) has 951 rates
951 of 3970: City of Lake Crystal, Minnesota (Utility Company) has 952 rates
952 of 3970: City of Lake Mills, Iowa (Utility Company) has 953 rates
953 of 3970: City of Lake Park, Iowa (Utility Company) has 954 rates
954 of 3970: City of Lake Park, Minnesota (Utility Company) has 955 rates
955 of 3970: City of Lake View, Iowa (Utility Company) has 956 rates
956 of 3970: City of Lake Worth, Florida (Utility Company) has 957 rates
957 of 3970: City of Lakefield, Minnesota (Utility Company) has 958 rates
958 of 3970: City of Lakeland, Florida (Utility Company) has 959 rates
959 of 3970: City of Lakin, Kansas (Utility Company) has 960 rates
960 of 3970: City of Lakota, North Dakota (Utility Company) has 961 rates
961 of 3970: City of Lamar, Colorado (Utility Company) has 962 rates
962 of 3970: City of Lamar, Missouri (Utility Company) has 963 rates
963 of 3970: City of Lamoni, Iowa (Utility Company) has 964 rates
964 of 3970: City of Lampasas, Texas (Utility Company) has 965 rates
965 of 3970: City of Lanett, Alabama (Utility Company) has 966 rates
966 of 3970: City of Lansing, Michigan (Utility Company) has 967 rates
967 of 3970: City of Larchwood, Iowa (Utility Company) has 968 rates
968 of 3970: City of Larned, Kansas (Utility Company) has 969 rates
969 of 3970: City of Larsen Bay, Alaska (Utility Company) has 970 rates
970 of 3970: City of Las Animas, Colorado (Utility Company) has 971 rates
971 of 3970: City of Laurel, Nebraska (Utility Company) has 972 rates
972 of 3970: City of Laurens, Iowa (Utility Company) has 973 rates
973 of 3970: City of Laurens, South Carolina (Utility Company) has 974 rates
974 of 3970: City of Laurinburg, North Carolina (Utility Company) has 975 rates
975 of 3970: City of Lawler, Iowa (Utility Company) has 976 rates
976 of 3970: City of Lawrenceburg, Tennessee (Utility Company) has 977 rates
977 of 3970: City of Lawrenceville, Georgia (Utility Company) has 978 rates
978 of 3970: City of Le Sueur, Minnesota (Utility Company) has 979 rates
979 of 3970: City of Lebanon, Indiana (Utility Company) has 980 rates
980 of 3970: City of Lebanon, Missouri (Utility Company) has 981 rates
981 of 3970: City of Lebanon, Ohio (Utility Company) has 982 rates
982 of 3970: City of Leesburg, Florida (Utility Company) has 983 rates
983 of 3970: City of Lehigh, Iowa (Utility Company) has 984 rates
984 of 3970: City of Leland, Mississippi (Utility Company) has 985 rates
985 of 3970: City of Lenoir, Tennessee (Utility Company) has 986 rates
986 of 3970: City of Lenox, Iowa (Utility Company) has 987 rates
987 of 3970: City of Lewes, Delaware (Utility Company) has 988 rates
988 of 3970: City of Lewisburg, Tennessee (Utility Company) has 989 rates
989 of 3970: City of Lewisville, Indiana (Utility Company) has 990 rates
990 of 3970: City of Lexington, Nebraska (Utility Company) has 991 rates
991 of 3970: City of Lexington, North Carolina (Utility Company) has 992 rates
992 of 3970: City of Lexington, Oklahoma (Utility Company) has 993 rates
993 of 3970: City of Lexington, Tennessee (Utility Company) has 994 rates
994 of 3970: City of Lexington, Texas (Utility Company) has 995 rates
995 of 3970: City of Liberal, Missouri (Utility Company) has 996 rates
996 of 3970: City of Liberty, Texas (Utility Company) has 997 rates
997 of 3970: City of Lincoln Center, Kansas (Utility Company) has 998 rates
998 of 3970: City of Lincolnton, North Carolina (Utility Company) has 999 rates
999 of 3970: City of Lindsay, Oklahoma (Utility Company) has 1000 rates
1000 of 3970: City of Lindsborg, Kansas (Utility Company) has 1001 rates
1001 of 3970: City of Linneus, Missouri (Utility Company) has 1002 rates
1002 of 3970: City of Linton, Indiana (Utility Company) has 1003 rates
1003 of 3970: City of Livermore, Iowa (Utility Company) has 1004 rates
1004 of 3970: City of Livingston, Texas (Utility Company) has 1005 rates
1005 of 3970: City of Llano, Texas (Utility Company) has 1006 rates
1006 of 3970: City of Lockhart, Texas (Utility Company) has 1007 rates
1007 of 3970: City of Lodgepole, Nebraska (Utility Company) has 1008 rates
1008 of 3970: City of Lodi, California (Utility Company) has 1009 rates
1009 of 3970: City of Lodi, Wisconsin (Utility Company) has 1010 rates
1010 of 3970: City of Logan, Utah (Utility Company) has 1011 rates
1011 of 3970: City of Logansport, Indiana (Utility Company) has 1012 rates
1012 of 3970: City of Lompoc, California (Utility Company) has 1013 rates
1013 of 3970: City of Long Grove, Iowa (Utility Company) has 1014 rates
1014 of 3970: City of Longmont, Colorado (Utility Company) has 1015 rates
1015 of 3970: City of Los Angeles, California (Utility Company) has 1016 rates
1016 of 3970: City of Loveland, Colorado (Utility Company) has 1017 rates
1017 of 3970: City of Lowell, Michigan (Utility Company) has 1018 rates
1018 of 3970: City of Lubbock, Texas (Utility Company) has 1019 rates
1019 of 3970: City of Lucas, Kansas (Utility Company) has 1020 rates
1020 of 3970: City of Luling, Texas (Utility Company) has 1021 rates
1021 of 3970: City of Lumberton, North Carolina (Utility Company) has 1022 rates
1022 of 3970: City of Luray, Kansas (Utility Company) has 1023 rates
1023 of 3970: City of Luverne, Alabama (Utility Company) has 1024 rates
1024 of 3970: City of Luverne, Minnesota (Utility Company) has 1025 rates
1025 of 3970: City of Lyons, Nebraska (Utility Company) has 1026 rates
1026 of 3970: City of Mabel, Minnesota (Utility Company) has 1027 rates
1027 of 3970: City of Macon, Mississippi (Utility Company) has 1028 rates
1028 of 3970: City of Macon, Missouri (Utility Company) has 1029 rates
1029 of 3970: City of Maddock, North Dakota (Utility Company) has 1030 rates
1030 of 3970: City of Madelia, Minnesota (Utility Company) has 1031 rates
1031 of 3970: City of Madison, Minnesota (Utility Company) has 1032 rates
1032 of 3970: City of Madison, Nebraska (Utility Company) has 1033 rates
1033 of 3970: City of Madison, South Dakota (Utility Company) has 1034 rates
1034 of 3970: City of Malden, Missouri (Utility Company) has 1035 rates
1035 of 3970: City of Manassas, Virginia (Utility Company) has 1036 rates
1036 of 3970: City of Mangum, Oklahoma (Utility Company) has 1037 rates
1037 of 3970: City of Manitou, Oklahoma (Utility Company) has 1038 rates
1038 of 3970: City of Mankato, Kansas (Utility Company) has 1039 rates
1039 of 3970: City of Manning, Iowa (Utility Company) has 1040 rates
1040 of 3970: City of Manokotak, Alaska (Utility Company) has 1041 rates
1041 of 3970: City of Mansfield, Georgia (Utility Company) has 1042 rates
1042 of 3970: City of Mansfield, Missouri (Utility Company) has 1043 rates
1043 of 3970: City of Manti, Utah (Utility Company) has 1044 rates
1044 of 3970: City of Mapleton, Iowa (Utility Company) has 1045 rates
1045 of 3970: City of Maquoketa, Iowa (Utility Company) has 1046 rates
1046 of 3970: City of Marathon, Iowa (Utility Company) has 1047 rates
1047 of 3970: City of Marblehead, Massachusetts (Utility Company) has 1048 rates
1048 of 3970: City of Marceline, Missouri (Utility Company) has 1049 rates
1049 of 3970: City of Marietta, Georgia (Utility Company) has 1050 rates
1050 of 3970: City of Marion, Kansas (Utility Company) has 1051 rates
1051 of 3970: City of Marlow, Oklahoma (Utility Company) has 1052 rates
1052 of 3970: City of Marquette, Michigan (Utility Company) has 1053 rates
1053 of 3970: City of Marshall, Illinois (Utility Company) has 1054 rates
1054 of 3970: City of Marshall, Michigan (Utility Company) has 1055 rates
1055 of 3970: City of Marshall, Minnesota (Utility Company) has 1056 rates
1056 of 3970: City of Marshall, Missouri (Utility Company) has 1057 rates
1057 of 3970: City of Marshfield, Wisconsin (Utility Company) has 1058 rates
1058 of 3970: City of Martinsville, Virginia (Utility Company) has 1059 rates
1059 of 3970: City of Mascoutah, Illinois (Utility Company) has 1060 rates
1060 of 3970: City of Mason, Texas (Utility Company) has 1061 rates
1061 of 3970: City of Mayfield Plant Board, Kentucky (Utility Company) has 1062 rates
1062 of 3970: City of McCleary, Washington (Utility Company) has 1063 rates
1063 of 3970: City of McGregor, Iowa (Utility Company) has 1064 rates
1064 of 3970: City of McLaughlin, South Dakota (Utility Company) has 1065 rates
1065 of 3970: City of McLeansboro, Illinois (Utility Company) has 1066 rates
1066 of 3970: City of McMinnville, Oregon (Utility Company) has 1067 rates
1067 of 3970: City of McPherson, Kansas (Utility Company) has 1068 rates
1068 of 3970: City of Meade, Kansas (Utility Company) has 1069 rates
1069 of 3970: City of Meadville, Missouri (Utility Company) has 1070 rates
1070 of 3970: City of Medford, Wisconsin (Utility Company) has 1071 rates
1071 of 3970: City of Memphis, Missouri (Utility Company) has 1072 rates
1072 of 3970: City of Memphis, Tennessee (Utility Company) has 1073 rates
1073 of 3970: City of Menasha, Wisconsin (Utility Company) has 1074 rates
1074 of 3970: City of Mendon, Ohio (Utility Company) has 1075 rates
1075 of 3970: City of Mesa, Arizona (Utility Company) has 1076 rates
1076 of 3970: City of Metropolis, Illinois (Utility Company) has 1077 rates
1077 of 3970: City of Miami, Oklahoma (Utility Company) has 1078 rates
1078 of 3970: City of Milan, Missouri (Utility Company) has 1079 rates
1079 of 3970: City of Milan, Tennessee (Utility Company) has 1080 rates
1080 of 3970: City of Milford, Delaware (Utility Company) has 1081 rates
1081 of 3970: City of Milford, Iowa (Utility Company) has 1082 rates
1082 of 3970: City of Miller, South Dakota (Utility Company) has 1083 rates
1083 of 3970: City of Milton, Washington (Utility Company) has 1084 rates
1084 of 3970: City of Milton-Freewater, Oregon (Utility Company) has 1085 rates
1085 of 3970: City of Minden, Louisiana (Utility Company) has 1086 rates
1086 of 3970: City of Minden, Nebraska (Utility Company) has 1087 rates
1087 of 3970: City of Mindenmines, Missouri (Utility Company) has 1088 rates
1088 of 3970: City of Minidoka, Idaho (Utility Company) has 1089 rates
1089 of 3970: City of Minneapolis, Kansas (Utility Company) has 1090 rates
1090 of 3970: City of Mishawaka, Indiana (Utility Company) has 1091 rates
1091 of 3970: City of Mitchell, Nebraska (Utility Company) has 1092 rates
1092 of 3970: City of Monett, Missouri (Utility Company) has 1093 rates
1093 of 3970: City of Monmouth, Oregon (Utility Company) has 1094 rates
1094 of 3970: City of Monroe City, Missouri (Utility Company) has 1095 rates
1095 of 3970: City of Monroe, Georgia (Utility Company) has 1096 rates
1096 of 3970: City of Monroe, North Carolina (Utility Company) has 1097 rates
1097 of 3970: City of Monroe, Utah (Utility Company) has 1098 rates
1098 of 3970: City of Montezuma, Iowa (Utility Company) has 1099 rates
1099 of 3970: City of Montezuma, Kansas (Utility Company) has 1100 rates
1100 of 3970: City of Monticello, Georgia (Utility Company) has 1101 rates
1101 of 3970: City of Moore Haven, Florida (Utility Company) has 1102 rates
1102 of 3970: City of Mooreland, Oklahoma (Utility Company) has 1103 rates
1103 of 3970: City of Moorhead, Minnesota (Utility Company) has 1104 rates
1104 of 3970: City of Mora, Minnesota (Utility Company) has 1105 rates
1105 of 3970: City of Moran, Kansas (Utility Company) has 1106 rates
1106 of 3970: City of Moreno Valley,, California (Utility Company) has 1107 rates
1107 of 3970: City of Morgan City, Louisiana (Utility Company) has 1108 rates
1108 of 3970: City of Morgan City, Utah (Utility Company) has 1109 rates
1109 of 3970: City of Morganton, North Carolina (Utility Company) has 1110 rates
1110 of 3970: City of Morrill, Kansas (Utility Company) has 1111 rates
1111 of 3970: City of Morristown, Tennessee (Utility Company) has 1112 rates
1112 of 3970: City of Moulton, Texas (Utility Company) has 1113 rates
1113 of 3970: City of Moultrie, Georgia (Utility Company) has 1114 rates
1114 of 3970: City of Moundridge, Kansas (Utility Company) has 1115 rates
1115 of 3970: City of Mount Dora, Florida (Utility Company) has 1116 rates
1116 of 3970: City of Mount Hope, Kansas (Utility Company) has 1117 rates
1117 of 3970: City of Mount Vernon, Missouri (Utility Company) has 1118 rates
1118 of 3970: City of Mountain Iron, Minnesota (Utility Company) has 1119 rates
1119 of 3970: City of Mountain Lake, Minnesota (Utility Company) has 1120 rates
1120 of 3970: City of Mountain View, Missouri (Utility Company) has 1121 rates
1121 of 3970: City of Mt Pleasant, Iowa (Utility Company) has 1122 rates
1122 of 3970: City of Mt Pleasant, Tennessee (Utility Company) has 1123 rates
1123 of 3970: City of Mt Pleasant, Utah (Utility Company) has 1124 rates
1124 of 3970: City of Mulberry, Kansas (Utility Company) has 1125 rates
1125 of 3970: City of Mulvane, Kansas (Utility Company) has 1126 rates
1126 of 3970: City of Murfreesboro, Tennessee (Utility Company) has 1127 rates
1127 of 3970: City of Murray, Kentucky (Utility Company) has 1128 rates
1128 of 3970: City of Murray, Utah (Utility Company) has 1129 rates
1129 of 3970: City of Muscle Shoals, Alabama (Utility Company) has 1130 rates
1130 of 3970: City of Muscotah, Kansas (Utility Company) has 1131 rates
1131 of 3970: City of Naperville, Illinois (Utility Company) has 1132 rates
1132 of 3970: City of Napoleon, Ohio (Utility Company) has 1133 rates
1133 of 3970: City of Nashwauk, Minnesota (Utility Company) has 1134 rates
1134 of 3970: City of Natchitoches, Louisiana (Utility Company) has 1135 rates
1135 of 3970: City of Nebraska City, Nebraska (Utility Company) has 1136 rates
1136 of 3970: City of Needles, California (Utility Company) has 1137 rates
1137 of 3970: City of Negaunee, Michigan (Utility Company) has 1138 rates
1138 of 3970: City of Neligh, Nebraska (Utility Company) has 1139 rates
1139 of 3970: City of Nelson, Nebraska (Utility Company) has 1140 rates
1140 of 3970: City of Neodesha, Kansas (Utility Company) has 1141 rates
1141 of 3970: City of Neola, Iowa (Utility Company) has 1142 rates
1142 of 3970: City of New Albany, Mississippi (Utility Company) has 1143 rates
1143 of 3970: City of New Bern, North Carolina (Utility Company) has 1144 rates
1144 of 3970: City of New Braunfels, Texas (Utility Company) has 1145 rates
1145 of 3970: City of New Hampton, Iowa (Utility Company) has 1146 rates
1146 of 3970: City of New Holstein, Wisconsin (Utility Company) has 1147 rates
1147 of 3970: City of New Lisbon, Wisconsin (Utility Company) has 1148 rates
1148 of 3970: City of New Madrid, Missouri (Utility Company) has 1149 rates
1149 of 3970: City of New Martinsville, West Virginia (Utility Company) has 1150 rates
1150 of 3970: City of New Richmond, Wisconsin (Utility Company) has 1151 rates
1151 of 3970: City of New Roads, Louisiana (Utility Company) has 1152 rates
1152 of 3970: City of New Ross, Indiana (Utility Company) has 1153 rates
1153 of 3970: City of New Smyrna Beach, Florida (Utility Company) has 1154 rates
1154 of 3970: City of Newark, Delaware (Utility Company) has 1155 rates
1155 of 3970: City of Newbern, Tennessee (Utility Company) has 1156 rates
1156 of 3970: City of Newberry, Florida (Utility Company) has 1157 rates
1157 of 3970: City of Newberry, South Carolina (Utility Company) has 1158 rates
1158 of 3970: City of Newburg, Missouri (Utility Company) has 1159 rates
1159 of 3970: City of Newfolden, Minnesota (Utility Company) has 1160 rates
1160 of 3970: City of Newkirk, Oklahoma (Utility Company) has 1161 rates
1161 of 3970: City of Newport, Tennessee (Utility Company) has 1162 rates
1162 of 3970: City of Newton Falls, Ohio (Utility Company) has 1163 rates
1163 of 3970: City of Newton, Illinois (Utility Company) has 1164 rates
1164 of 3970: City of Newton, North Carolina (Utility Company) has 1165 rates
1165 of 3970: City of Newton, Texas (Utility Company) has 1166 rates
1166 of 3970: City of Nicholasville, Kentucky (Utility Company) has 1167 rates
1167 of 3970: City of Nielsville, Minnesota (Utility Company) has 1168 rates
1168 of 3970: City of Niles, Michigan (Utility Company) has 1169 rates
1169 of 3970: City of Niles, Ohio (Utility Company) has 1170 rates
1170 of 3970: City of Nixa, Missouri (Utility Company) has 1171 rates
1171 of 3970: City of Norcross, Georgia (Utility Company) has 1172 rates
1172 of 3970: City of North Little Rock, Arkansas (Utility Company) has 1173 rates
1173 of 3970: City of North Platte, Nebraska (Utility Company) has 1174 rates
1174 of 3970: City of North St Paul, Minnesota (Utility Company) has 1175 rates
1175 of 3970: City of Northwood, North Dakota (Utility Company) has 1176 rates
1176 of 3970: City of Norton, Kansas (Utility Company) has 1177 rates
1177 of 3970: City of Norway, Michigan (Utility Company) has 1178 rates
1178 of 3970: City of Norwich, Connecticut (Utility Company) has 1179 rates
1179 of 3970: City of Norwood, Massachusetts (Utility Company) has 1180 rates
1180 of 3970: City of Oak Ridge, Tennessee (Utility Company) has 1181 rates
1181 of 3970: City of Oberlin, Kansas (Utility Company) has 1182 rates
1182 of 3970: City of Oberlin, Ohio (Utility Company) has 1183 rates
1183 of 3970: City of Ocala, Florida (Utility Company) has 1184 rates
1184 of 3970: City of Odessa, Missouri (Utility Company) has 1185 rates
1185 of 3970: City of Ogden, Iowa (Utility Company) has 1186 rates
1186 of 3970: City of Oglesby, Illinois (Utility Company) has 1187 rates
1187 of 3970: City of Okolona, Mississippi (Utility Company) has 1188 rates
1188 of 3970: City of Olive Hill, Kentucky (Utility Company) has 1189 rates
1189 of 3970: City of Olivia, Minnesota (Utility Company) has 1190 rates
1190 of 3970: City of Olustee, Oklahoma (Utility Company) has 1191 rates
1191 of 3970: City of Onawa, Iowa (Utility Company) has 1192 rates
1192 of 3970: City of Onida, South Dakota (Utility Company) has 1193 rates
1193 of 3970: City of Opelika, Alabama (Utility Company) has 1194 rates
1194 of 3970: City of Opp, Alabama (Utility Company) has 1195 rates
1195 of 3970: City of Orange City, Iowa (Utility Company) has 1196 rates
1196 of 3970: City of Orangeburg, South Carolina (Utility Company) has 1197 rates
1197 of 3970: City of Ord, Nebraska (Utility Company) has 1198 rates
1198 of 3970: City of Orient, Iowa (Utility Company) has 1199 rates
1199 of 3970: City of Orlando, Oklahoma (Utility Company) has 1200 rates
1200 of 3970: City of Orrville, Ohio (Utility Company) has 1201 rates
1201 of 3970: City of Ortonville, Minnesota (Utility Company) has 1202 rates
1202 of 3970: City of Osage City, Kansas (Utility Company) has 1203 rates
1203 of 3970: City of Osage, Iowa (Utility Company) has 1204 rates
1204 of 3970: City of Osawatomie, Kansas (Utility Company) has 1205 rates
1205 of 3970: City of Osborne, Kansas (Utility Company) has 1206 rates
1206 of 3970: City of Osceola, Arkansas (Utility Company) has 1207 rates
1207 of 3970: City of Osceola, Missouri (Utility Company) has 1208 rates
1208 of 3970: City of Ottawa, Kansas (Utility Company) has 1209 rates
1209 of 3970: City of Ouzinkie, Alaska (Utility Company) has 1210 rates
1210 of 3970: City of Owatonna, Minnesota (Utility Company) has 1211 rates
1211 of 3970: City of Owensboro, Kentucky (Utility Company) has 1212 rates
1212 of 3970: City of Owensville, Missouri (Utility Company) has 1213 rates
1213 of 3970: City of Oxford, Georgia (Utility Company) has 1214 rates
1214 of 3970: City of Oxford, Kansas (Utility Company) has 1215 rates
1215 of 3970: City of Oxford, Mississippi (Utility Company) has 1216 rates
1216 of 3970: City of Paducah, Kentucky (Utility Company) has 1217 rates
1217 of 3970: City of Painesville, Ohio (Utility Company) has 1218 rates
1218 of 3970: City of Palmetto, Georgia (Utility Company) has 1219 rates
1219 of 3970: City of Palmyra, Missouri (Utility Company) has 1220 rates
1220 of 3970: City of Palo Alto, California (Utility Company) has 1221 rates
1221 of 3970: City of Panora, Iowa (Utility Company) has 1222 rates
1222 of 3970: City of Paris, Arkansas (Utility Company) has 1223 rates
1223 of 3970: City of Paris, Kentucky (Utility Company) has 1224 rates
1224 of 3970: City of Paris, Missouri (Utility Company) has 1225 rates
1225 of 3970: City of Paris, Tennessee (Utility Company) has 1226 rates
1226 of 3970: City of Park River, North Dakota (Utility Company) has 1227 rates
1227 of 3970: City of Parker, South Dakota (Utility Company) has 1228 rates
1228 of 3970: City of Pasadena, California (Utility Company) has 1229 rates
1229 of 3970: City of Paton, Iowa (Utility Company) has 1230 rates
1230 of 3970: City of Paullina, Iowa (Utility Company) has 1231 rates
1231 of 3970: City of Pawhuska, Oklahoma (Utility Company) has 1232 rates
1232 of 3970: City of Pawnee, Oklahoma (Utility Company) has 1233 rates
1233 of 3970: City of Peabody, Massachusetts (Utility Company) has 1234 rates
1234 of 3970: City of Pella, Iowa (Utility Company) has 1235 rates
1235 of 3970: City of Pender, Nebraska (Utility Company) has 1236 rates
1236 of 3970: City of Perry, Missouri (Utility Company) has 1237 rates
1237 of 3970: City of Perry, Oklahoma (Utility Company) has 1238 rates
1238 of 3970: City of Peru, Illinois (Utility Company) has 1239 rates
1239 of 3970: City of Peru, Indiana (Utility Company) has 1240 rates
1240 of 3970: City of Petersburg, Alaska (Utility Company) has 1241 rates
1241 of 3970: City of Peterson, Minnesota (Utility Company) has 1242 rates
1242 of 3970: City of Petoskey, Michigan (Utility Company) has 1243 rates
1243 of 3970: City of Philadelphia, Mississippi (Utility Company) has 1244 rates
1244 of 3970: City of Piedmont, Alabama (Utility Company) has 1245 rates
1245 of 3970: City of Pierce, Nebraska (Utility Company) has 1246 rates
1246 of 3970: City of Pierre, South Dakota (Utility Company) has 1247 rates
1247 of 3970: City of Pierz, Minnesota (Utility Company) has 1248 rates
1248 of 3970: City of Piggott, Arkansas (Utility Company) has 1249 rates
1249 of 3970: City of Pine Bluffs, Wyoming (Utility Company) has 1250 rates
1250 of 3970: City of Pioche, Nevada (Utility Company) has 1251 rates
1251 of 3970: City of Piqua, Ohio (Utility Company) has 1252 rates
1252 of 3970: City of Plainview, Nebraska (Utility Company) has 1253 rates
1253 of 3970: City of Plankinton, South Dakota (Utility Company) has 1254 rates
1254 of 3970: City of Plaquemine, Louisiana (Utility Company) has 1255 rates
1255 of 3970: City of Plattsburgh, New York (Utility Company) has 1256 rates
1256 of 3970: City of Plummer, Idaho (Utility Company) has 1257 rates
1257 of 3970: City of Plymouth, Wisconsin (Utility Company) has 1258 rates
1258 of 3970: City of Pocahontas, Iowa (Utility Company) has 1259 rates
1259 of 3970: City of Pomona, Kansas (Utility Company) has 1260 rates
1260 of 3970: City of Ponca City, Oklahoma (Utility Company) has 1261 rates
1261 of 3970: City of Pond Creek, Oklahoma (Utility Company) has 1262 rates
1262 of 3970: City of Poplar Bluff, Missouri (Utility Company) has 1263 rates
1263 of 3970: City of Port Angeles, Washington (Utility Company) has 1264 rates
1264 of 3970: City of Portland, Michigan (Utility Company) has 1265 rates
1265 of 3970: City of Powell, Wyoming (Utility Company) has 1266 rates
1266 of 3970: City of Pratt, Kansas (Utility Company) has 1267 rates
1267 of 3970: City of Prescott, Arkansas (Utility Company) has 1268 rates
1268 of 3970: City of Prescott, Kansas (Utility Company) has 1269 rates
1269 of 3970: City of Preston, Iowa (Utility Company) has 1270 rates
1270 of 3970: City of Primghar, Iowa (Utility Company) has 1271 rates
1271 of 3970: City of Princeton, Illinois (Utility Company) has 1272 rates
1272 of 3970: City of Princeton, Kentucky (Utility Company) has 1273 rates
1273 of 3970: City of Princeton, Wisconsin (Utility Company) has 1274 rates
1274 of 3970: City of Providence, Kentucky (Utility Company) has 1275 rates
1275 of 3970: City of Pryor, Oklahoma (Utility Company) has 1276 rates
1276 of 3970: City of Public Works Comm- Fayetteville, North Carolina (Utility Company) has 1277 rates
1277 of 3970: City of Pulaski, Tennessee (Utility Company) has 1278 rates
1278 of 3970: City of Purcell, Oklahoma (Utility Company) has 1279 rates
1279 of 3970: City of Quincy, Florida (Utility Company) has 1280 rates
1280 of 3970: City of Quitman, Georgia (Utility Company) has 1281 rates
1281 of 3970: City of Radford, Virginia (Utility Company) has 1282 rates
1282 of 3970: City of Radium, Kansas (Utility Company) has 1283 rates
1283 of 3970: City of Randall, Minnesota (Utility Company) has 1284 rates
1284 of 3970: City of Randolph, Nebraska (Utility Company) has 1285 rates
1285 of 3970: City of Rayne, Louisiana (Utility Company) has 1286 rates
1286 of 3970: City of Readlyn, Iowa (Utility Company) has 1287 rates
1287 of 3970: City of Red Bud, Illinois (Utility Company) has 1288 rates
1288 of 3970: City of Red Cloud, Nebraska (Utility Company) has 1289 rates
1289 of 3970: City of Redding, California (Utility Company) has 1290 rates
1290 of 3970: City of Remsen, Iowa (Utility Company) has 1291 rates
1291 of 3970: City of Rensselaer, Indiana (Utility Company) has 1292 rates
1292 of 3970: City of Renwick, Iowa (Utility Company) has 1293 rates
1293 of 3970: City of Rich Hill, Missouri (Utility Company) has 1294 rates
1294 of 3970: City of Richland Center, Wisconsin (Utility Company) has 1295 rates
1295 of 3970: City of Richland, Missouri (Utility Company) has 1296 rates
1296 of 3970: City of Richland, Washington (Utility Company) has 1297 rates
1297 of 3970: City of Richmond, Indiana (Utility Company) has 1298 rates
1298 of 3970: City of Ripley, Tennessee (Utility Company) has 1299 rates
1299 of 3970: City of Rising Sun, Indiana (Utility Company) has 1300 rates
1300 of 3970: City of River Falls, Wisconsin (Utility Company) has 1301 rates
1301 of 3970: City of Riverdale, North Dakota (Utility Company) has 1302 rates
1302 of 3970: City of Riverside, California (Utility Company) has 1303 rates
1303 of 3970: City of Robersonville, North Carolina (Utility Company) has 1304 rates
1304 of 3970: City of Robertsdale, Alabama (Utility Company) has 1305 rates
1305 of 3970: City of Robinson, Kansas (Utility Company) has 1306 rates
1306 of 3970: City of Robstown, Texas (Utility Company) has 1307 rates
1307 of 3970: City of Rock Falls, Illinois (Utility Company) has 1308 rates
1308 of 3970: City of Rock Hill, South Carolina (Utility Company) has 1309 rates
1309 of 3970: City of Rockford, Iowa (Utility Company) has 1310 rates
1310 of 3970: City of Rockport, Missouri (Utility Company) has 1311 rates
1311 of 3970: City of Rockwood, Tennessee (Utility Company) has 1312 rates
1312 of 3970: City of Rocky Mount, North Carolina (Utility Company) has 1313 rates
1313 of 3970: City of Rolla, Missouri (Utility Company) has 1314 rates
1314 of 3970: City of Roodhouse, Illinois (Utility Company) has 1315 rates
1315 of 3970: City of Roseau, Minnesota (Utility Company) has 1316 rates
1316 of 3970: City of Roseville, California (Utility Company) has 1317 rates
1317 of 3970: City of Round Lake, Minnesota (Utility Company) has 1318 rates
1318 of 3970: City of Rupert, Idaho (Utility Company) has 1319 rates
1319 of 3970: City of Rushford, Minnesota (Utility Company) has 1320 rates
1320 of 3970: City of Rushmore, Minnesota (Utility Company) has 1321 rates
1321 of 3970: City of Russell, Kansas (Utility Company) has 1322 rates
1322 of 3970: City of Russell, Massachusetts (Utility Company) has 1323 rates
1323 of 3970: City of Russellville, Alabama (Utility Company) has 1324 rates
1324 of 3970: City of Russellville, Kentucky (Utility Company) has 1325 rates
1325 of 3970: City of Ruston, Louisiana (Utility Company) has 1326 rates
1326 of 3970: City of Sabetha, Kansas (Utility Company) has 1327 rates
1327 of 3970: City of Sabula, Iowa (Utility Company) has 1328 rates
1328 of 3970: City of Safford, Arizona (Utility Company) has 1329 rates
1329 of 3970: City of Saint Paul, Alaska (Utility Company) has 1330 rates
1330 of 3970: City of Saint Peter, Minnesota (Utility Company) has 1331 rates
1331 of 3970: City of Salamanca, New York (Utility Company) has 1332 rates
1332 of 3970: City of Salem, Missouri (Utility Company) has 1333 rates
1333 of 3970: City of Salem, Virginia (Utility Company) has 1334 rates
1334 of 3970: City of Salisbury, Missouri (Utility Company) has 1335 rates
1335 of 3970: City of Sallisaw, Oklahoma (Utility Company) has 1336 rates
1336 of 3970: City of San Antonio, Texas (Utility Company) has 1337 rates
1337 of 3970: City of San Augustine, Texas (Utility Company) has 1338 rates
1338 of 3970: City of San Marcos, Texas (Utility Company) has 1339 rates
1339 of 3970: City of San Saba, Texas (Utility Company) has 1340 rates
1340 of 3970: City of Sanborn, Iowa (Utility Company) has 1341 rates
1341 of 3970: City of Sandersville, Georgia (Utility Company) has 1342 rates
1342 of 3970: City of Sanger, Texas (Utility Company) has 1343 rates
1343 of 3970: City of Santa Clara, California (Utility Company) has 1344 rates
1344 of 3970: City of Santa Clara, Utah (Utility Company) has 1345 rates
1345 of 3970: City of Sargent, Nebraska (Utility Company) has 1346 rates
1346 of 3970: City of Sauk Centre, Minnesota (Utility Company) has 1347 rates
1347 of 3970: City of Savonburg, Kansas (Utility Company) has 1348 rates
1348 of 3970: City of Schulenburg, Texas (Utility Company) has 1349 rates
1349 of 3970: City of Schuyler, Nebraska (Utility Company) has 1350 rates
1350 of 3970: City of Scottsboro, Alabama (Utility Company) has 1351 rates
1351 of 3970: City of Scottsburg, Indiana (Utility Company) has 1352 rates
1352 of 3970: City of Scranton, Kansas (Utility Company) has 1353 rates
1353 of 3970: City of Scribner, Nebraska (Utility Company) has 1354 rates
1354 of 3970: City of Seaford, Delaware (Utility Company) has 1355 rates
1355 of 3970: City of Seaside Heights, New Jersey (Utility Company) has 1356 rates
1356 of 3970: City of Seattle, Washington (Utility Company) has 1357 rates
1357 of 3970: City of Sebewaing, Michigan (Utility Company) has 1358 rates
1358 of 3970: City of Seguin, Texas (Utility Company) has 1359 rates
1359 of 3970: City of Seneca, Kansas (Utility Company) has 1360 rates
1360 of 3970: City of Seneca, South Carolina (Utility Company) has 1361 rates
1361 of 3970: City of Sergeant Bluff, Iowa (Utility Company) has 1362 rates
1362 of 3970: City of Seward, Alaska (Utility Company) has 1363 rates
1363 of 3970: City of Seward, Kansas (Utility Company) has 1364 rates
1364 of 3970: City of Seward, Nebraska (Utility Company) has 1365 rates
1365 of 3970: City of Seymour, Missouri (Utility Company) has 1366 rates
1366 of 3970: City of Seymour, Texas (Utility Company) has 1367 rates
1367 of 3970: City of Sharon Springs, Kansas (Utility Company) has 1368 rates
1368 of 3970: City of Sharon, North Dakota (Utility Company) has 1369 rates
1369 of 3970: City of Shasta Lake, California (Utility Company) has 1370 rates
1370 of 3970: City of Sheboygan Falls, Wisconsin (Utility Company) has 1371 rates
1371 of 3970: City of Shelbina, Missouri (Utility Company) has 1372 rates
1372 of 3970: City of Shelby, Iowa (Utility Company) has 1373 rates
1373 of 3970: City of Shelby, North Carolina (Utility Company) has 1374 rates
1374 of 3970: City of Shelby, Ohio (Utility Company) has 1375 rates
1375 of 3970: City of Shelbyville, Tennessee (Utility Company) has 1376 rates
1376 of 3970: City of Shelly, Minnesota (Utility Company) has 1377 rates
1377 of 3970: City of Sherrill, New York (Utility Company) has 1378 rates
1378 of 3970: City of Shiner, Texas (Utility Company) has 1379 rates
1379 of 3970: City of Shullsburg, Wisconsin (Utility Company) has 1380 rates
1380 of 3970: City of Sibley, Iowa (Utility Company) has 1381 rates
1381 of 3970: City of Sidney, Nebraska (Utility Company) has 1382 rates
1382 of 3970: City of Sikeston, Missouri (Utility Company) has 1383 rates
1383 of 3970: City of Siloam Springs, Arkansas (Utility Company) has 1384 rates
1384 of 3970: City of Sioux Center, Iowa (Utility Company) has 1385 rates
1385 of 3970: City of Sioux Falls, South Dakota (Utility Company) has 1386 rates
1386 of 3970: City of Slater, Missouri (Utility Company) has 1387 rates
1387 of 3970: City of Smithville, Tennessee (Utility Company) has 1388 rates
1388 of 3970: City of Smithville, Texas (Utility Company) has 1389 rates
1389 of 3970: City of Snyder, Nebraska (Utility Company) has 1390 rates
1390 of 3970: City of Soda Springs, Idaho (Utility Company) has 1391 rates
1391 of 3970: City of South Haven, Michigan (Utility Company) has 1392 rates
1392 of 3970: City of South Norwalk, Connecticut (Utility Company) has 1393 rates
1393 of 3970: City of South Sioux City, Nebraska (Utility Company) has 1394 rates
1394 of 3970: City of Southport, North Carolina (Utility Company) has 1395 rates
1395 of 3970: City of Sparta, Tennessee (Utility Company) has 1396 rates
1396 of 3970: City of Spencer, Iowa (Utility Company) has 1397 rates
1397 of 3970: City of Spencer, Nebraska (Utility Company) has 1398 rates
1398 of 3970: City of Spooner, Wisconsin (Utility Company) has 1399 rates
1399 of 3970: City of Spring Grove, Minnesota (Utility Company) has 1400 rates
1400 of 3970: City of Springfield, Colorado (Utility Company) has 1401 rates
1401 of 3970: City of Springfield, Illinois (Utility Company) has 1402 rates
1402 of 3970: City of Springfield, Oregon (Utility Company) has 1403 rates
1403 of 3970: City of Springfield, Tennessee (Utility Company) has 1404 rates
1404 of 3970: City of Springville, Utah (Utility Company) has 1405 rates
1405 of 3970: City of St Charles, Illinois (Utility Company) has 1406 rates
1406 of 3970: City of St Charles, Minnesota (Utility Company) has 1407 rates
1407 of 3970: City of St Clairsville, Ohio (Utility Company) has 1408 rates
1408 of 3970: City of St Francis, Kansas (Utility Company) has 1409 rates
1409 of 3970: City of St George, Utah (Utility Company) has 1410 rates
1410 of 3970: City of St James, Minnesota (Utility Company) has 1411 rates
1411 of 3970: City of St James, Missouri (Utility Company) has 1412 rates
1412 of 3970: City of St John, Kansas (Utility Company) has 1413 rates
1413 of 3970: City of St Louis, Michigan (Utility Company) has 1414 rates
1414 of 3970: City of St Martinville, Louisiana (Utility Company) has 1415 rates
1415 of 3970: City of St Marys, Kansas (Utility Company) has 1416 rates
1416 of 3970: City of St Marys, Ohio (Utility Company) has 1417 rates
1417 of 3970: City of St Paul, Nebraska (Utility Company) has 1418 rates
1418 of 3970: City of St Robert, Missouri (Utility Company) has 1419 rates
1419 of 3970: City of Stafford, Kansas (Utility Company) has 1420 rates
1420 of 3970: City of Stanberry, Missouri (Utility Company) has 1421 rates
1421 of 3970: City of Stanhope, Iowa (Utility Company) has 1422 rates
1422 of 3970: City of Stanton, Iowa (Utility Company) has 1423 rates
1423 of 3970: City of Stanton, North Dakota (Utility Company) has 1424 rates
1424 of 3970: City of Staples, Minnesota (Utility Company) has 1425 rates
1425 of 3970: City of Starke, Florida (Utility Company) has 1426 rates
1426 of 3970: City of Starkville, Mississippi (Utility Company) has 1427 rates
1427 of 3970: City of State Center, Iowa (Utility Company) has 1428 rates
1428 of 3970: City of Statesville, North Carolina (Utility Company) has 1429 rates
1429 of 3970: City of Steelville, Missouri (Utility Company) has 1430 rates
1430 of 3970: City of Stephen, Minnesota (Utility Company) has 1431 rates
1431 of 3970: City of Stephenson, Michigan (Utility Company) has 1432 rates
1432 of 3970: City of Sterling, Kansas (Utility Company) has 1433 rates
1433 of 3970: City of Stilwell, Oklahoma (Utility Company) has 1434 rates
1434 of 3970: City of Stockton, Kansas (Utility Company) has 1435 rates
1435 of 3970: City of Story City, Iowa (Utility Company) has 1436 rates
1436 of 3970: City of Stoughton, Wisconsin (Utility Company) has 1437 rates
1437 of 3970: City of Stratford, Iowa (Utility Company) has 1438 rates
1438 of 3970: City of Stratton, Nebraska (Utility Company) has 1439 rates
1439 of 3970: City of Strawberry Point, Iowa (Utility Company) has 1440 rates
1440 of 3970: City of Stromsburg, Nebraska (Utility Company) has 1441 rates
1441 of 3970: City of Stroud, Oklahoma (Utility Company) has 1442 rates
1442 of 3970: City of Stuart, Iowa (Utility Company) has 1443 rates
1443 of 3970: City of Stuart, Nebraska (Utility Company) has 1444 rates
1444 of 3970: City of Sturgeon Bay, Wisconsin (Utility Company) has 1445 rates
1445 of 3970: City of Sturgis, Michigan (Utility Company) has 1446 rates
1446 of 3970: City of Sullivan, Illinois (Utility Company) has 1447 rates
1447 of 3970: City of Sullivan, Missouri (Utility Company) has 1448 rates
1448 of 3970: City of Sumas, Washington (Utility Company) has 1449 rates
1449 of 3970: City of Summerfield, Kansas (Utility Company) has 1450 rates
1450 of 3970: City of Sumner, Iowa (Utility Company) has 1451 rates
1451 of 3970: City of Superior, Nebraska (Utility Company) has 1452 rates
1452 of 3970: City of Sutton, Nebraska (Utility Company) has 1453 rates
1453 of 3970: City of Sweetwater, Tennessee (Utility Company) has 1454 rates
1454 of 3970: City of Sylvania, Georgia (Utility Company) has 1455 rates
1455 of 3970: City of Sylvester, Georgia (Utility Company) has 1456 rates
1456 of 3970: City of Syracuse, Nebraska (Utility Company) has 1457 rates
1457 of 3970: City of Tacoma, Washington (Utility Company) has 1458 rates
1458 of 3970: City of Tallahassee, Florida (Utility Company) has 1459 rates
1459 of 3970: City of Tarrant, Alabama (Utility Company) has 1460 rates
1460 of 3970: City of Taunton, Massachusetts (Utility Company) has 1461 rates
1461 of 3970: City of Tecumseh, Nebraska (Utility Company) has 1462 rates
1462 of 3970: City of Tell City, Indiana (Utility Company) has 1463 rates
1463 of 3970: City of Tenakee Springs, Alaska (Utility Company) has 1464 rates
1464 of 3970: City of Thayer, Missouri (Utility Company) has 1465 rates
1465 of 3970: City of Thief River Falls, Minnesota (Utility Company) has 1466 rates
1466 of 3970: City of Thomaston, Georgia (Utility Company) has 1467 rates
1467 of 3970: City of Thomasville, Georgia (Utility Company) has 1468 rates
1468 of 3970: City of Thorntown, Indiana (Utility Company) has 1469 rates
1469 of 3970: City of Timpson, Texas (Utility Company) has 1470 rates
1470 of 3970: City of Tipp City, Ohio (Utility Company) has 1471 rates
1471 of 3970: City of Tipton, Iowa (Utility Company) has 1472 rates
1472 of 3970: City of Tonkawa, Oklahoma (Utility Company) has 1473 rates
1473 of 3970: City of Toronto, Kansas (Utility Company) has 1474 rates
1474 of 3970: City of Torrington, Wyoming (Utility Company) has 1475 rates
1475 of 3970: City of Traer, Iowa (Utility Company) has 1476 rates
1476 of 3970: City of Traverse City, Michigan (Utility Company) has 1477 rates
1477 of 3970: City of Trenton, Nebraska (Utility Company) has 1478 rates
1478 of 3970: City of Trenton, Tennessee (Utility Company) has 1479 rates
1479 of 3970: City of Trinidad, Colorado (Utility Company) has 1480 rates
1480 of 3970: City of Troy, Alabama (Utility Company) has 1481 rates
1481 of 3970: City of Troy, Indiana (Utility Company) has 1482 rates
1482 of 3970: City of Troy, Kansas (Utility Company) has 1483 rates
1483 of 3970: City of Troy, Montana (Utility Company) has 1484 rates
1484 of 3970: City of Truth or Consequences, New Mexico (Utility Company) has 1485 rates
1485 of 3970: City of Tulia, Texas (Utility Company) has 1486 rates
1486 of 3970: City of Tupelo, Mississippi (Utility Company) has 1487 rates
1487 of 3970: City of Tuscumbia, Alabama (Utility Company) has 1488 rates
1488 of 3970: City of Tuskegee, Alabama (Utility Company) has 1489 rates
1489 of 3970: City of Two Harbors, Minnesota (Utility Company) has 1490 rates
1490 of 3970: City of Tyler, Minnesota (Utility Company) has 1491 rates
1491 of 3970: City of Tyndall, South Dakota (Utility Company) has 1492 rates
1492 of 3970: City of Udall, Kansas (Utility Company) has 1493 rates
1493 of 3970: City of Ukiah, California (Utility Company) has 1494 rates
1494 of 3970: City of Unalaska, Alaska (Utility Company) has 1495 rates
1495 of 3970: City of Union City, Tennessee (Utility Company) has 1496 rates
1496 of 3970: City of Union, South Carolina (Utility Company) has 1497 rates
1497 of 3970: City of Unionville, Missouri (Utility Company) has 1498 rates
1498 of 3970: City of Valentine, Nebraska (Utility Company) has 1499 rates
1499 of 3970: City of Valley City, North Dakota (Utility Company) has 1500 rates
1500 of 3970: City of Vanceburg, Kentucky (Utility Company) has 1501 rates
1501 of 3970: City of Vandalia, Missouri (Utility Company) has 1502 rates
1502 of 3970: City of Vermillion, Kansas (Utility Company) has 1503 rates
1503 of 3970: City of Vermillion, South Dakota (Utility Company) has 1504 rates
1504 of 3970: City of Vernon, California (Utility Company) has 1505 rates
1505 of 3970: City of Vero Beach, Florida (Utility Company) has 1506 rates
1506 of 3970: City of Villisca, Iowa (Utility Company) has 1507 rates
1507 of 3970: City of Vineland, New Jersey (Utility Company) has 1508 rates
1508 of 3970: City of Vinton, Iowa (Utility Company) has 1509 rates
1509 of 3970: City of Virginia, Minnesota (Utility Company) has 1510 rates
1510 of 3970: City of Volga, South Dakota (Utility Company) has 1511 rates
1511 of 3970: City of Wadena, Minnesota (Utility Company) has 1512 rates
1512 of 3970: City of Wadsworth, Ohio (Utility Company) has 1513 rates
1513 of 3970: City of Waelder, Texas (Utility Company) has 1514 rates
1514 of 3970: City of Wahoo, Nebraska (Utility Company) has 1515 rates
1515 of 3970: City of Wakefield, Michigan (Utility Company) has 1516 rates
1516 of 3970: City of Wakefield, Nebraska (Utility Company) has 1517 rates
1517 of 3970: City of Wall Lake, Iowa (Utility Company) has 1518 rates
1518 of 3970: City of Wamego, Kansas (Utility Company) has 1519 rates
1519 of 3970: City of Wapakoneta, Ohio (Utility Company) has 1520 rates
1520 of 3970: City of Warren, Minnesota (Utility Company) has 1521 rates
1521 of 3970: City of Warroad, Minnesota (Utility Company) has 1522 rates
1522 of 3970: City of Waseca, Minnesota (Utility Company) has 1523 rates
1523 of 3970: City of Washington, Georgia (Utility Company) has 1524 rates
1524 of 3970: City of Washington, Indiana (Utility Company) has 1525 rates
1525 of 3970: City of Washington, Kansas (Utility Company) has 1526 rates
1526 of 3970: City of Washington, North Carolina (Utility Company) has 1527 rates
1527 of 3970: City of Washington, Utah (Utility Company) has 1528 rates
1528 of 3970: City of Water Valley, Mississippi (Utility Company) has 1529 rates
1529 of 3970: City of Waterloo, Illinois (Utility Company) has 1530 rates
1530 of 3970: City of Watertown, New York (Utility Company) has 1531 rates
1531 of 3970: City of Waterville, Kansas (Utility Company) has 1532 rates
1532 of 3970: City of Wathena, Kansas (Utility Company) has 1533 rates
1533 of 3970: City of Watonga, Oklahoma (Utility Company) has 1534 rates
1534 of 3970: City of Wauchula, Florida (Utility Company) has 1535 rates
1535 of 3970: City of Wayne, Nebraska (Utility Company) has 1536 rates
1536 of 3970: City of Waynesville, Missouri (Utility Company) has 1537 rates
1537 of 3970: City of Waynetown, Indiana (Utility Company) has 1538 rates
1538 of 3970: City of Waynoka, Oklahoma (Utility Company) has 1539 rates
1539 of 3970: City of Webster City, Iowa (Utility Company) has 1540 rates
1540 of 3970: City of Weimar, Texas (Utility Company) has 1541 rates
1541 of 3970: City of Weiser, Idaho (Utility Company) has 1542 rates
1542 of 3970: City of Wellington, Kansas (Utility Company) has 1543 rates
1543 of 3970: City of Wells, Minnesota (Utility Company) has 1544 rates
1544 of 3970: City of Wessington Springs, South Dakota (Utility Company) has 1545 rates
1545 of 3970: City of West Bend, Iowa (Utility Company) has 1546 rates
1546 of 3970: City of West Liberty, Iowa (Utility Company) has 1547 rates
1547 of 3970: City of West Memphis, Arkansas (Utility Company) has 1548 rates
1548 of 3970: City of West Plains, Missouri (Utility Company) has 1549 rates
1549 of 3970: City of West Point, Georgia (Utility Company) has 1550 rates
1550 of 3970: City of West Point, Mississippi (Utility Company) has 1551 rates
1551 of 3970: City of West Point, Nebraska (Utility Company) has 1552 rates
1552 of 3970: City of Westbrook, Minnesota (Utility Company) has 1553 rates
1553 of 3970: City of Westby, Wisconsin (Utility Company) has 1554 rates
1554 of 3970: City of Westerville, Ohio (Utility Company) has 1555 rates
1555 of 3970: City of Westfield, Massachusetts (Utility Company) has 1556 rates
1556 of 3970: City of Westminster, South Carolina (Utility Company) has 1557 rates
1557 of 3970: City of Wetumka, Oklahoma (Utility Company) has 1558 rates
1558 of 3970: City of Whalan, Minnesota (Utility Company) has 1559 rates
1559 of 3970: City of Whigham, Georgia (Utility Company) has 1560 rates
1560 of 3970: City of White Mountain, Alaska (Utility Company) has 1561 rates
1561 of 3970: City of White, South Dakota (Utility Company) has 1562 rates
1562 of 3970: City of Whitesboro, Texas (Utility Company) has 1563 rates
1563 of 3970: City of Whittemore, Iowa (Utility Company) has 1564 rates
1564 of 3970: City of Wilber, Nebraska (Utility Company) has 1565 rates
1565 of 3970: City of Williams - AZ, Arizona (Utility Company) has 1566 rates
1566 of 3970: City of Williamsport, Indiana (Utility Company) has 1567 rates
1567 of 3970: City of Williston, Florida (Utility Company) has 1568 rates
1568 of 3970: City of Willow Springs, Missouri (Utility Company) has 1569 rates
1569 of 3970: City of Wilson, North Carolina (Utility Company) has 1570 rates
1570 of 3970: City of Wilton, Iowa (Utility Company) has 1571 rates
1571 of 3970: City of Winchester, Tennessee (Utility Company) has 1572 rates
1572 of 3970: City of Windom, Minnesota (Utility Company) has 1573 rates
1573 of 3970: City of Winfield, Kansas (Utility Company) has 1574 rates
1574 of 3970: City of Winnfield, Louisiana (Utility Company) has 1575 rates
1575 of 3970: City of Winona, Missouri (Utility Company) has 1576 rates
1576 of 3970: City of Winterset, Iowa (Utility Company) has 1577 rates
1577 of 3970: City of Winterville, North Carolina (Utility Company) has 1578 rates
1578 of 3970: City of Winthrop, Minnesota (Utility Company) has 1579 rates
1579 of 3970: City of Wisner, Nebraska (Utility Company) has 1580 rates
1580 of 3970: City of Wood River, Nebraska (Utility Company) has 1581 rates
1581 of 3970: City of Woodbine, Iowa (Utility Company) has 1582 rates
1582 of 3970: City of Woodsfield, Ohio (Utility Company) has 1583 rates
1583 of 3970: City of Woolstock, Iowa (Utility Company) has 1584 rates
1584 of 3970: City of Worthington, Minnesota (Utility Company) has 1585 rates
1585 of 3970: City of Wrangell, Alaska (Utility Company) has 1586 rates
1586 of 3970: City of Wray, Colorado (Utility Company) has 1587 rates
1587 of 3970: City of Wymore, Nebraska (Utility Company) has 1588 rates
1588 of 3970: City of Wynnewood, Oklahoma (Utility Company) has 1589 rates
1589 of 3970: City of Yale, Oklahoma (Utility Company) has 1590 rates
1590 of 3970: City of Yoakum, Texas (Utility Company) has 1591 rates
1591 of 3970: City of Yuma, Colorado (Utility Company) has 1592 rates
1592 of 3970: City of Zeeland, Michigan (Utility Company) has 1593 rates
1593 of 3970: City Utilities has 1594 rates
1594 of 3970: City Utilities of Springfield has 1595 rates
1595 of 3970: City Water and Light Plant has 1596 rates
1596 of 3970: CL Power Sales Eight LLC has 1597 rates
1597 of 3970: Claiborne Electric Coop, Inc has 1598 rates
1598 of 3970: Clark County Rural E M C has 1599 rates
1599 of 3970: Clark Electric Coop has 1600 rates
1600 of 3970: Clark Energy Coop Inc has 1601 rates
1601 of 3970: Clarke Electric Coop Inc has 1602 rates
1602 of 3970: Clarke-Washington E M C has 1603 rates
1603 of 3970: Clarksdale Public Utilities has 1604 rates
1604 of 3970: Clarksville Light & Water Co has 1605 rates
1605 of 3970: Clatskanie Peoples Util Dist has 1606 rates
1606 of 3970: Claverack Rural Elec Coop Inc has 1607 rates
1607 of 3970: Clay County Electric Coop Corp has 1608 rates
1608 of 3970: Clay Electric Coop Inc has 1609 rates
1609 of 3970: Clay Electric Cooperative, Inc has 1610 rates
1610 of 3970: Clay-Union Electric Coop has 1611 rates
1611 of 3970: CleanPowerSF has 1612 rates
1612 of 3970: Clear Lake Cogeneration LP has 1613 rates
1613 of 3970: Clearwater Power Company has 1614 rates
1614 of 3970: Clearwater-Polk Elec Coop Inc has 1615 rates
1615 of 3970: Cleco Power LLC has 1616 rates
1616 of 3970: Cleveland Cliffs Inc has 1617 rates
1617 of 3970: Cleveland Electric Illum Co has 1618 rates
1618 of 3970: Clinton Combined Utility Sys has 1619 rates
1619 of 3970: Clinton County Elec Coop, Inc has 1620 rates
1620 of 3970: Cloverland Electric Co-op has 1621 rates
1621 of 3970: Clyde Light & Power has 1622 rates
1622 of 3970: CMS Electric Coop Inc has 1623 rates
1623 of 3970: CMS Energy Resource Management Corp has 1624 rates
1624 of 3970: Co-Mo Electric Coop Inc has 1625 rates
1625 of 3970: Coahoma Electric Power Assn has 1626 rates
1626 of 3970: Coast Electric Power Assn has 1627 rates
1627 of 3970: Coastal Electric Coop, Inc has 1628 rates
1628 of 3970: Coastal Electric Member Corp has 1629 rates
1629 of 3970: Cobb Electric Membership Corp has 1630 rates
1630 of 3970: Cobb EMC has 1631 rates
1631 of 3970: Codington-Clark Elec Coop, Inc has 1632 rates
1632 of 3970: Coldwater Board of Public Util has 1633 rates
1633 of 3970: Coleman County Elec Coop, Inc has 1634 rates
1634 of 3970: Coles-Moultrie Electric Coop has 1635 rates
1635 of 3970: Colorado Energy Nations Company LLLP has 1636 rates
1636 of 3970: Colorado River Comm of Nevada has 1637 rates
1637 of 3970: Colorado River Indian Irr Proj has 1638 rates
1638 of 3970: Colorado Springs Utilities has 1639 rates
1639 of 3970: Colorado State University has 1640 rates
1640 of 3970: Colquitt Electric Membership Corp has 1641 rates
1641 of 3970: Columbia Basin Elec Cooperative, Inc has 1642 rates
1642 of 3970: Columbia Power Coop Assn Inc has 1643 rates
1643 of 3970: Columbia Power System has 1644 rates
1644 of 3970: Columbia River Peoples Ut Dist has 1645 rates
1645 of 3970: Columbia Rural Elec Assn, Inc has 1646 rates
1646 of 3970: Columbia Rural Elec Assn, Inc (Oregon) has 1647 rates
1647 of 3970: Columbia Utilities Electricity has 1648 rates
1648 of 3970: Columbus Electric Coop, Inc has 1649 rates
1649 of 3970: Columbus Electric Coop, Inc (Arizona) has 1650 rates
1650 of 3970: Columbus Southern Power Co has 1651 rates
1651 of 3970: Comanche County Elec Coop Assn has 1652 rates
1652 of 3970: ComED has 1653 rates
1653 of 3970: Commerce Energy, Inc. has 1654 rates
1654 of 3970: Commerce Energy, Inc. (Maryland) has 1655 rates
1655 of 3970: Commerce Energy, Inc. (Michigan) has 1656 rates
1656 of 3970: Commerce Energy, Inc. (New Jersey) has 1657 rates
1657 of 3970: Commerce Energy, Inc. (Pennsylvania) has 1658 rates
1658 of 3970: Commonwealth Edison Co has 1659 rates
1659 of 3970: Community Electric Coop has 1660 rates
1660 of 3970: Competitive Energy Services, LLC has 1661 rates
1661 of 3970: Concho Valley Elec Coop Inc has 1662 rates
1662 of 3970: Concordia Electric Coop, Inc has 1663 rates
1663 of 3970: Conectiv has 1664 rates
1664 of 3970: Conectiv (Maryland) has 1665 rates
1665 of 3970: Conectiv Energy Supply Inc. has 1666 rates
1666 of 3970: ConEdison has 1667 rates
1667 of 3970: Connect Utilities has 1668 rates
1668 of 3970: Connecticut Light & Power Co has 1669 rates
1669 of 3970: Connecticut Municipal Electric Energy Cooperative has 1670 rates
1670 of 3970: Connexus Energy has 1671 rates
1671 of 3970: ConocoPhillips Company has 1672 rates
1672 of 3970: ConocoPhillips Company (Illinois) has 1673 rates
1673 of 3970: ConocoPhillips Company (Montana) has 1674 rates
1674 of 3970: Consolidated Edison Co-NY Inc has 1675 rates
1675 of 3970: Consolidated Edison Sol Inc has 1676 rates
1676 of 3970: Consolidated Edison Sol Inc (Connecticut) has 1677 rates
1677 of 3970: Consolidated Edison Sol Inc (Delaware) has 1678 rates
1678 of 3970: Consolidated Edison Sol Inc (District of Columbia) has 1679 rates
1679 of 3970: Consolidated Edison Sol Inc (Illinois) has 1680 rates
1680 of 3970: Consolidated Edison Sol Inc (Maine) has 1681 rates
1681 of 3970: Consolidated Edison Sol Inc (Maryland) has 1682 rates
1682 of 3970: Consolidated Edison Sol Inc (Massachusetts) has 1683 rates
1683 of 3970: Consolidated Edison Sol Inc (New Hampshire) has 1684 rates
1684 of 3970: Consolidated Edison Sol Inc (New Jersey) has 1685 rates
1685 of 3970: Consolidated Edison Sol Inc (Pennsylvania) has 1686 rates
1686 of 3970: Consolidated Edison Sol Inc (Texas) has 1687 rates
1687 of 3970: Consolidated Electric Coop has 1688 rates
1688 of 3970: Consolidated Electric Coop Inc has 1689 rates
1689 of 3970: Consolidated Water Power Co has 1690 rates
1690 of 3970: Constellation NewEnergy, Inc has 1691 rates
1691 of 3970: Constellation NewEnergy, Inc (California) has 1692 rates
1692 of 3970: Constellation NewEnergy, Inc (Connecticut) has 1693 rates
1693 of 3970: Constellation NewEnergy, Inc (Delaware) has 1694 rates
1694 of 3970: Constellation NewEnergy, Inc (District of Columbia) has 1695 rates
1695 of 3970: Constellation NewEnergy, Inc (Illinois) has 1696 rates
1696 of 3970: Constellation NewEnergy, Inc (Maine) has 1697 rates
1697 of 3970: Constellation NewEnergy, Inc (Massachusetts) has 1698 rates
1698 of 3970: Constellation NewEnergy, Inc (Michigan) has 1699 rates
1699 of 3970: Constellation NewEnergy, Inc (New Hampshire) has 1700 rates
1700 of 3970: Constellation NewEnergy, Inc (New Jersey) has 1701 rates
1701 of 3970: Constellation NewEnergy, Inc (New York) has 1702 rates
1702 of 3970: Constellation NewEnergy, Inc (Ohio) has 1703 rates
1703 of 3970: Constellation NewEnergy, Inc (Oregon) has 1704 rates
1704 of 3970: Constellation NewEnergy, Inc (Pennsylvania) has 1705 rates
1705 of 3970: Constellation NewEnergy, Inc (Rhode Island) has 1706 rates
1706 of 3970: Constellation NewEnergy, Inc (Texas) has 1707 rates
1707 of 3970: Constllation Enrgy Commodities has 1708 rates
1708 of 3970: Consumers Energy has 1709 rates
1709 of 3970: Consumers Energy Co has 1710 rates
1710 of 3970: Consumers Power, Inc has 1711 rates
1711 of 3970: Continental Divide El Coop Inc has 1712 rates
1712 of 3970: Conway Corporation has 1713 rates
1713 of 3970: Cooke County Elec Coop Assn has 1714 rates
1714 of 3970: Cookson Hills Elec Coop, Inc has 1715 rates
1715 of 3970: Cooperative L&P Assn Lake Cnty has 1716 rates
1716 of 3970: Coos-Curry Electric Coop, Inc has 1717 rates
1717 of 3970: Coosa Valley Electric Coop Inc has 1718 rates
1718 of 3970: Copan Public Works Authority has 1719 rates
1719 of 3970: Copper Valley Elec Assn, Inc has 1720 rates
1720 of 3970: Coral Power LLC has 1721 rates
1721 of 3970: Coral Power LLC (California) has 1722 rates
1722 of 3970: Coral Power LLC (Nevada) has 1723 rates
1723 of 3970: Coral Power LLC (Washington) has 1724 rates
1724 of 3970: Corbin City Utilities Comm has 1725 rates
1725 of 3970: Cordova Electric Coop, Inc has 1726 rates
1726 of 3970: Corn Belt Energy Corporation has 1727 rates
1727 of 3970: Corn Belt Power Coop has 1728 rates
1728 of 3970: Cornhusker Public Power Dist has 1729 rates
1729 of 3970: Corpus Christi Cogeneration LP has 1730 rates
1730 of 3970: CoServ has 1731 rates
1731 of 3970: Cotton Electric Coop, Inc has 1732 rates
1732 of 3970: Covington Electric Coop, Inc has 1733 rates
1733 of 3970: Coweta-Fayette El Member Corp has 1734 rates
1734 of 3970: Cowlitz County PUD has 1735 rates
1735 of 3970: Cozad Board of Public Works has 1736 rates
1736 of 3970: CP Power Sales Seventeen LLC has 1737 rates
1737 of 3970: CPKelco U S Inc has 1738 rates
1738 of 3970: CPL Retail Energy, LP has 1739 rates
1739 of 3970: CPS Energy has 1740 rates
1740 of 3970: Craig-Botetourt Electric Coop has 1741 rates
1741 of 3970: Craig-Botetourt Electric Coop (West Virginia) has 1742 rates
1742 of 3970: Craighead Electric Coop Corp has 1743 rates
1743 of 3970: Crawford Electric Coop, Inc has 1744 rates
1744 of 3970: Crawfordsville Elec, Lgt & Pwr has 1745 rates
1745 of 3970: Crisp County Power Comm has 1746 rates
1746 of 3970: Crow Wing Cooperative Power & Light Comp has 1747 rates
1747 of 3970: Cuivre River Electric Coop Inc has 1748 rates
1748 of 3970: Cullman Electric Coop, Inc has 1749 rates
1749 of 3970: Cullman Power Board has 1750 rates
1750 of 3970: Cumberland Elec Member Corp has 1751 rates
1751 of 3970: Cumberland Valley Rural E C C has 1752 rates
1752 of 3970: Cumberland Valley Rural E C C (Tennessee) has 1753 rates
1753 of 3970: Cuming County Public Pwr Dist has 1754 rates
1754 of 3970: Custer Public Power District has 1755 rates
1755 of 3970: D S & O Rural E C A, Inc has 1756 rates
1756 of 3970: Dahlberg Light & Power Co has 1757 rates
1757 of 3970: Dairyland Power Coop has 1758 rates
1758 of 3970: Dakota Electric Association has 1759 rates
1759 of 3970: Dakota Energy Coop Inc has 1760 rates
1760 of 3970: Dakota Valley Elec Coop Inc has 1761 rates
1761 of 3970: Dalton Utilities has 1762 rates
1762 of 3970: Darke Rural Electric Coop, Inc has 1763 rates
1763 of 3970: Darlington Light & Power Co has 1764 rates
1764 of 3970: Daviess Martin County R E M C has 1765 rates
1765 of 3970: Dawson Power District has 1766 rates
1766 of 3970: Dayton Power & Light Co has 1767 rates
1767 of 3970: Deaf Smith Electric Coop, Inc has 1768 rates
1768 of 3970: Decatur County Rural E M C has 1769 rates
1769 of 3970: Decatur Utilities has 1770 rates
1770 of 3970: Deep East Texas Elec Coop Inc has 1771 rates
1771 of 3970: Delano Municipal Utilities has 1772 rates
1772 of 3970: Delaware County Elec Coop Inc has 1773 rates
1773 of 3970: Delaware Electric Cooperative has 1774 rates
1774 of 3970: Delmarva Power has 1775 rates
1775 of 3970: Delmarva Power (Maryland) has 1776 rates
1776 of 3970: Delta Electric Power Assn has 1777 rates
1777 of 3970: Delta Montrose Electric Assn has 1778 rates
1778 of 3970: Denton County Elec Coop, Inc has 1779 rates
1779 of 3970: Deseret Generation & Tran Coop has 1780 rates
1780 of 3970: Deseret Generation & Tran Coop (Colorado) has 1781 rates
1781 of 3970: Detroit Edison Co has 1782 rates
1782 of 3970: Devonshire Energy, LLC has 1783 rates
1783 of 3970: Devonshire Energy, LLC (District of Columbia) has 1784 rates
1784 of 3970: Direct Energy Services has 1785 rates
1785 of 3970: Direct Energy Services (Delaware) has 1786 rates
1786 of 3970: Direct Energy Services (District of Columbia) has 1787 rates
1787 of 3970: Direct Energy Services (Illinois) has 1788 rates
1788 of 3970: Direct Energy Services (Maine) has 1789 rates
1789 of 3970: Direct Energy Services (Maryland) has 1790 rates
1790 of 3970: Direct Energy Services (Massachusetts) has 1791 rates
1791 of 3970: Direct Energy Services (New Jersey) has 1792 rates
1792 of 3970: Direct Energy Services (New York) has 1793 rates
1793 of 3970: Direct Energy Services (Pennsylvania) has 1794 rates
1794 of 3970: Direct Energy Services (Rhode Island) has 1795 rates
1795 of 3970: Direct Energy, LP has 1796 rates
1796 of 3970: Discount Power has 1797 rates
1797 of 3970: Diverse Power Incorporated has 1798 rates
1798 of 3970: Dixie Electric Coop has 1799 rates
1799 of 3970: Dixie Electric Membership Corp has 1800 rates
1800 of 3970: Dixie Electric Power Assn has 1801 rates
1801 of 3970: Dixie Escalante R E A, Inc has 1802 rates
1802 of 3970: Dixie Escalante R E A, Inc (Arizona) has 1803 rates
1803 of 3970: Dominion Energy Marketing Inc. has 1804 rates
1804 of 3970: Dominion Retail Inc has 1805 rates
1805 of 3970: Dominion Retail Inc (Connecticut) has 1806 rates
1806 of 3970: Dominion Retail Inc (Maine) has 1807 rates
1807 of 3970: Dominion Retail Inc (Maryland) has 1808 rates
1808 of 3970: Dominion Retail Inc (Massachusetts) has 1809 rates
1809 of 3970: Dominion Retail Inc (New Jersey) has 1810 rates
1810 of 3970: Dominion Retail Inc (New York) has 1811 rates
1811 of 3970: Dominion Retail Inc (Ohio) has 1812 rates
1812 of 3970: Dominion Retail Inc (Pennsylvania) has 1813 rates
1813 of 3970: Dominion Virginia has 1814 rates
1814 of 3970: Doniphan Elec Coop Assn, Inc has 1815 rates
1815 of 3970: Douglas Electric Coop, Inc has 1816 rates
1816 of 3970: Douglas Electric Coop, Inc (South Dakota) has 1817 rates
1817 of 3970: Dow Chemical Company-Oyster Creek VIII has 1818 rates
1818 of 3970: DPC Juniper, LLC has 1819 rates
1819 of 3970: DPI Energy LLC has 1820 rates
1820 of 3970: DPL has 1821 rates
1821 of 3970: DPL Energy Resources has 1822 rates
1822 of 3970: DPS Gregory LLC has 1823 rates
1823 of 3970: DTE has 1824 rates
1824 of 3970: DTE Electric has 1825 rates
1825 of 3970: DTE Energy Trading, Inc has 1826 rates
1826 of 3970: Dublin Municipal Electric Util has 1827 rates
1827 of 3970: Dubois Rural Electric Coop Inc has 1828 rates
1828 of 3970: Duck River Elec Member Corp has 1829 rates
1829 of 3970: Duke Energy has 1830 rates
1830 of 3970: Duke Energy Carolinas, LLC has 1831 rates
1831 of 3970: Duke Energy Carolinas, LLC (South Carolina) has 1832 rates
1832 of 3970: Duke Energy Indiana Inc has 1833 rates
1833 of 3970: Duke Energy Kentucky, Inc. has 1834 rates
1834 of 3970: Duke Energy Ohio Inc has 1835 rates
1835 of 3970: Duke Energy Retail Sales, LLC has 1836 rates
1836 of 3970: Duncan Valley Elec Coop, Inc has 1837 rates
1837 of 3970: Duncan Valley Elec Coop, Inc (New Mexico) has 1838 rates
1838 of 3970: Dunn County Electric Coop has 1839 rates
1839 of 3970: Duquesne Light Co has 1840 rates
1840 of 3970: Duquesne Light Energy, LLC has 1841 rates
1841 of 3970: Dynegy Power Marketing Inc has 1842 rates
1842 of 3970: E I DuPont De Nemours & Co has 1843 rates
1843 of 3970: E I DuPont De Nemours & Co (Texas) has 1844 rates
1844 of 3970: Easley Combined Utility System has 1845 rates
1845 of 3970: East Bay Community Energy has 1846 rates
1846 of 3970: East Bay Municipal Util Dist has 1847 rates
1847 of 3970: East Central Energy has 1848 rates
1848 of 3970: East Central Energy (Wisconsin) has 1849 rates
1849 of 3970: East Central Oklahoma Elec Coop Inc has 1850 rates
1850 of 3970: East End Mutual Elec Co Ltd has 1851 rates
1851 of 3970: East Kentucky Power Coop, Inc has 1852 rates
1852 of 3970: East Mississippi Elec Pwr Assn has 1853 rates
1853 of 3970: East River Elec Pwr Coop, Inc has 1854 rates
1854 of 3970: East Texas Electric Coop, Inc has 1855 rates
1855 of 3970: East-Central Iowa Rural Elec Coop has 1856 rates
1856 of 3970: Eastern Illinois Elec Coop has 1857 rates
1857 of 3970: Eastern Iowa Light & Power Coop has 1858 rates
1858 of 3970: Eastern Maine Electric Coop has 1859 rates
1859 of 3970: Easton Utilities Comm has 1860 rates
1860 of 3970: Eau Claire Electric Coop has 1861 rates
1861 of 3970: EDF Industrial Power Services (TX), LLC has 1862 rates
1862 of 3970: Edgar Electric Co-op, Assn has 1863 rates
1863 of 3970: Edgecombe-Martin County E M C has 1864 rates
1864 of 3970: Edinburg Municipal Utilities has 1865 rates
1865 of 3970: Edison Mission Marktg & Trdg Inc has 1866 rates
1866 of 3970: Edisto Electric Coop, Inc has 1867 rates
1867 of 3970: Egegik Light & Power Co has 1868 rates
1868 of 3970: Egyptian Electric Coop Assn has 1869 rates
1869 of 3970: El Paso Electric Co has 1870 rates
1870 of 3970: El Paso Electric Co (New Mexico) has 1871 rates
1871 of 3970: El Paso Merchant Energy LP has 1872 rates
1872 of 3970: Eldridge City Utilities has 1873 rates
1873 of 3970: Elec District No. 5 Maricopa C has 1874 rates
1874 of 3970: Electric Energy Inc has 1875 rates
1875 of 3970: Electric Energy Inc (Kentucky) has 1876 rates
1876 of 3970: Electric Fund (CDWR) has 1877 rates
1877 of 3970: Electrical Dist No2 Pinal Cnty has 1878 rates
1878 of 3970: Electrical Dist No3 Pinal Cnty has 1879 rates
1879 of 3970: Electrical Dist No4 Pinal Cnty has 1880 rates
1880 of 3970: Electrical Dist No5 Pinal Cnty has 1881 rates
1881 of 3970: Electrical Dist No6 Pinal Cnty has 1882 rates
1882 of 3970: Electrical Dist No7 Maricopa has 1883 rates
1883 of 3970: Electrical Dist No8 Maricopa has 1884 rates
1884 of 3970: Elkhorn Rural Public Pwr Dist has 1885 rates
1885 of 3970: Elmhurst Mutual Power & Light Co has 1886 rates
1886 of 3970: Emera Maine has 1887 rates
1887 of 3970: Emerald People's Utility Dist has 1888 rates
1888 of 3970: Empire has 1889 rates
1889 of 3970: Empire District Electric Co has 1890 rates
1890 of 3970: Empire District Electric Co (Kansas) has 1891 rates
1891 of 3970: Empire District Electric Co (Missouri) has 1892 rates
1892 of 3970: Empire District Electric Co (Oklahoma) has 1893 rates
1893 of 3970: Empire Electric Assn, Inc has 1894 rates
1894 of 3970: Empire Electric Assn, Inc (Utah) has 1895 rates
1895 of 3970: Empire Natural Gas Corporation has 1896 rates
1896 of 3970: En-Touch Energy has 1897 rates
1897 of 3970: Energetix has 1898 rates
1898 of 3970: Energy Coop of New York, Inc has 1899 rates
1899 of 3970: Energy Northwest has 1900 rates
1900 of 3970: Energy Plus Holdings LLC has 1901 rates
1901 of 3970: Energy Plus Holdings LLC (Connecticut) has 1902 rates
1902 of 3970: Energy Plus Holdings LLC (Maryland) has 1903 rates
1903 of 3970: Energy Plus Holdings LLC (New Jersey) has 1904 rates
1904 of 3970: Energy Plus Holdings LLC (New York) has 1905 rates
1905 of 3970: Energy Plus Holdings LLC (Texas) has 1906 rates
1906 of 3970: Energy Services Providers, Inc. has 1907 rates
1907 of 3970: Energy Services Providers, Inc. (New York) has 1908 rates
1908 of 3970: EnergyUnited Elec Member Corp has 1909 rates
1909 of 3970: Entergy Arkansas Inc has 1910 rates
1910 of 3970: Entergy Arkansas Inc (Arkansas) has 1911 rates
1911 of 3970: Entergy Arkansas Inc (Tennessee) has 1912 rates
1912 of 3970: Entergy Gulf States Louisiana LLC has 1913 rates
1913 of 3970: Entergy Louisiana Inc has 1914 rates
1914 of 3970: Entergy Mississippi Inc has 1915 rates
1915 of 3970: Entergy New Orleans Inc has 1916 rates
1916 of 3970: Entergy Power, Inc has 1917 rates
1917 of 3970: Entergy Solutions, Ltd has 1918 rates
1918 of 3970: Entergy Solutions, Ltd (Massachusetts) has 1919 rates
1919 of 3970: Entergy Texas Inc. has 1920 rates
1920 of 3970: EPB has 1921 rates
1921 of 3970: Epcot Electric has 1922 rates
1922 of 3970: Escambia River Elec Coop, Inc has 1923 rates
1923 of 3970: Eugene Water & Electric Board has 1924 rates
1924 of 3970: Evergy Kansas Central has 1925 rates
1925 of 3970: Evergy Kansas Metro has 1926 rates
1926 of 3970: Evergy Missouri Metro has 1927 rates
1927 of 3970: Evergy Missouri West has 1928 rates
1928 of 3970: Eversource Energy Connecticut has 1929 rates
1929 of 3970: Eversource of Massachusetts has 1930 rates
1930 of 3970: EWEB has 1931 rates
1931 of 3970: Excelsior Electric Member Corp has 1932 rates
1932 of 3970: Exelon Energy Company has 1933 rates
1933 of 3970: Exelon Energy Company (Pennsylvania) has 1934 rates
1934 of 3970: Fairfield Electric Coop, Inc has 1935 rates
1935 of 3970: Fairmont Public Utilities Comm has 1936 rates
1936 of 3970: Fairview City Corporation (Utility Company) has 1937 rates
1937 of 3970: Fale-Safe, Inc has 1938 rates
1938 of 3970: Fall River Rural Elec Coop Inc has 1939 rates
1939 of 3970: Fall River Rural Elec Coop Inc (Montana) has 1940 rates
1940 of 3970: Fall River Rural Elec Coop Inc (Wyoming) has 1941 rates
1941 of 3970: Fannin County Electric Coop has 1942 rates
1942 of 3970: Farmers Electric Company, Ltd has 1943 rates
1943 of 3970: Farmers Electric Coop has 1944 rates
1944 of 3970: Farmers Electric Coop Corp has 1945 rates
1945 of 3970: Farmers Electric Coop, Inc has 1946 rates
1946 of 3970: Farmers Electric Coop, Inc (Texas) has 1947 rates
1947 of 3970: Farmers Mutual Electric Co has 1948 rates
1948 of 3970: Farmers Rural Electric Coop Corp has 1949 rates
1949 of 3970: Farmers' Electric Coop, Inc has 1950 rates
1950 of 3970: Farmers' Electric Coop, Inc (New Mexico) has 1951 rates
1951 of 3970: Farmington River Power Company has 1952 rates
1952 of 3970: Fayette Electric Coop, Inc has 1953 rates
1953 of 3970: Federated Rural Electric Assn has 1954 rates
1954 of 3970: Federated Rural Electric Assn (Iowa) has 1955 rates
1955 of 3970: FEM Electric Assn, Inc has 1956 rates
1956 of 3970: Fergus Electric Coop, Inc has 1957 rates
1957 of 3970: Fillmore City Corporation (Utility Company) has 1958 rates
1958 of 3970: Firelands Electric Coop, Inc has 1959 rates
1959 of 3970: First Choice Power has 1960 rates
1960 of 3970: First Electric Coop Corp has 1961 rates
1961 of 3970: First Energy Solutions Corp. has 1962 rates
1962 of 3970: First Energy Solutions Corp. (Illinois) has 1963 rates
1963 of 3970: First Energy Solutions Corp. (Maryland) has 1964 rates
1964 of 3970: First Energy Solutions Corp. (Michigan) has 1965 rates
1965 of 3970: First Energy Solutions Corp. (New Jersey) has 1966 rates
1966 of 3970: First Energy Solutions Corp. (Pennsylvania) has 1967 rates
1967 of 3970: FirstEnergy Generation Corp has 1968 rates
1968 of 3970: Fishers Island Utility Co Inc has 1969 rates
1969 of 3970: Fitchburg Gas and Electric Light Company has 1970 rates
1970 of 3970: Fitchburg Gas and Electric Light Company (Massachusetts) has 1971 rates
1971 of 3970: Fitzgerald Wtr Lgt & Bond Comm has 1972 rates
1972 of 3970: Flathead Electric Coop Inc has 1973 rates
1973 of 3970: Fleming-Mason Energy Coop Inc has 1974 rates
1974 of 3970: Flint Electric Membership Corp has 1975 rates
1975 of 3970: Flint Hills Rural E C A, Inc has 1976 rates
1976 of 3970: Flora Utilities has 1977 rates
1977 of 3970: Florence Utility Comm has 1978 rates
1978 of 3970: Florida Keys El Coop Assn, Inc has 1979 rates
1979 of 3970: Florida Municipal Power Agency has 1980 rates
1980 of 3970: Florida Power & Light Co. has 1981 rates
1981 of 3970: Florida Public Utilities Co has 1982 rates
1982 of 3970: Flowell Electric Assn, Inc has 1983 rates
1983 of 3970: Foley Board of Utilities has 1984 rates
1984 of 3970: Forked Deer Electric Coop, Inc has 1985 rates
1985 of 3970: Fort Belknap Electric Coop Inc has 1986 rates
1986 of 3970: Fort Loudoun Electric Coop has 1987 rates
1987 of 3970: Fort Payne Improvement Auth has 1988 rates
1988 of 3970: Fort Pierce Utilities Auth has 1989 rates
1989 of 3970: Fort Valley Utility Comm has 1990 rates
1990 of 3970: Four County Elec Member Corp has 1991 rates
1991 of 3970: Fox Islands Electric Coop, Inc has 1992 rates
1992 of 3970: FPL has 1993 rates
1993 of 3970: FPL Energy has 1994 rates
1994 of 3970: Franklin Electric Coop has 1995 rates
1995 of 3970: Franklin Heating Station has 1996 rates
1996 of 3970: Franklin Rural Electric Cooperative has 1997 rates
1997 of 3970: Freeborn-Mower Coop Services has 1998 rates
1998 of 3970: Freeborn-Mower Coop Services (Iowa) has 1999 rates
1999 of 3970: Freedom Energy has 2000 rates
2000 of 3970: Freedom Energy (Connecticut) has 2001 rates
2001 of 3970: Freedom Energy (Maine) has 2002 rates
2002 of 3970: Freedom Energy (Massachusetts) has 2003 rates
2003 of 3970: Freedom Energy (Rhode Island) has 2004 rates
2004 of 3970: French Broad Elec Member Corp has 2005 rates
2005 of 3970: French Broad Elec Member Corp (Tennessee) has 2006 rates
2006 of 3970: Frontier Power Company has 2007 rates
2007 of 3970: Frontier Utilities, Inc. has 2008 rates
2008 of 3970: FRV SI Transport Solar LP has 2009 rates
2009 of 3970: Fulton County Rural E M C has 2010 rates
2010 of 3970: G & K, Inc has 2011 rates
2011 of 3970: Gainesville Regional Utilities has 2012 rates
2012 of 3970: Galena Electric Utility has 2013 rates
2013 of 3970: Garkane Energy Coop, Inc has 2014 rates
2014 of 3970: Garkane Energy Coop, Inc (Arizona) has 2015 rates
2015 of 3970: Garland Light & Power Company has 2016 rates
2016 of 3970: Gascosage Electric Coop has 2017 rates
2017 of 3970: Gateway Energy Services Corporation has 2018 rates
2018 of 3970: Gateway Energy Services Corporation (Maryland) has 2019 rates
2019 of 3970: Gateway Energy Services Corporation (New Jersey) has 2020 rates
2020 of 3970: Gateway Energy Services Corporation (Pennsylvania) has 2021 rates
2021 of 3970: Gateway Energy Services Corporation (Texas) has 2022 rates
2022 of 3970: Gay & Robinson Inc has 2023 rates
2023 of 3970: Georgia Power Co has 2024 rates
2024 of 3970: Georgia Transmission Corp has 2025 rates
2025 of 3970: GEXA Corp. has 2026 rates
2026 of 3970: GEXA Corp. (Connecticut) has 2027 rates
2027 of 3970: GEXA Corp. (Delaware) has 2028 rates
2028 of 3970: GEXA Corp. (District of Columbia) has 2029 rates
2029 of 3970: GEXA Corp. (Illinois) has 2030 rates
2030 of 3970: GEXA Corp. (Maine) has 2031 rates
2031 of 3970: GEXA Corp. (Maryland) has 2032 rates
2032 of 3970: GEXA Corp. (Massachusetts) has 2033 rates
2033 of 3970: GEXA Corp. (New Hampshire) has 2034 rates
2034 of 3970: GEXA Corp. (New Jersey) has 2035 rates
2035 of 3970: GEXA Corp. (Pennsylvania) has 2036 rates
2036 of 3970: GEXA Corp. (Rhode Island) has 2037 rates
2037 of 3970: Gibson Electric Members Corp has 2038 rates
2038 of 3970: Glacial Energy Holdings has 2039 rates
2039 of 3970: Glacial Energy Holdings (California) has 2040 rates
2040 of 3970: Glacial Energy Holdings (Connecticut) has 2041 rates
2041 of 3970: Glacial Energy Holdings (Delaware) has 2042 rates
2042 of 3970: Glacial Energy Holdings (District of Columbia) has 2043 rates
2043 of 3970: Glacial Energy Holdings (Illinois) has 2044 rates
2044 of 3970: Glacial Energy Holdings (Maine) has 2045 rates
2045 of 3970: Glacial Energy Holdings (Maryland) has 2046 rates
2046 of 3970: Glacial Energy Holdings (Massachusetts) has 2047 rates
2047 of 3970: Glacial Energy Holdings (Michigan) has 2048 rates
2048 of 3970: Glacial Energy Holdings (New Hampshire) has 2049 rates
2049 of 3970: Glacial Energy Holdings (New Jersey) has 2050 rates
2050 of 3970: Glacial Energy Holdings (New York) has 2051 rates
2051 of 3970: Glacial Energy Holdings (Ohio) has 2052 rates
2052 of 3970: Glacial Energy Holdings (Pennsylvania) has 2053 rates
2053 of 3970: Glacial Energy Holdings (Rhode Island) has 2054 rates
2054 of 3970: Glacier Electric Coop, Inc has 2055 rates
2055 of 3970: Glades Electric Coop, Inc has 2056 rates
2056 of 3970: Glencoe Light & Power Comm has 2057 rates
2057 of 3970: Glidden Rural Electric Coop has 2058 rates
2058 of 3970: Gold Country Energy has 2059 rates
2059 of 3970: Golden Spread Electric Cooperative, Inc has 2060 rates
2060 of 3970: Golden Valley Elec Assn Inc has 2061 rates
2061 of 3970: Goldenwest Electric Coop, Inc has 2062 rates
2062 of 3970: Goldenwest Electric Coop, Inc (North Dakota) has 2063 rates
2063 of 3970: Goltry Public Works Authority has 2064 rates
2064 of 3970: Goodhue County Coop Elec Assn has 2065 rates
2065 of 3970: Gowrie Municipal Utilities has 2066 rates
2066 of 3970: Grady Electric Membership Corp has 2067 rates
2067 of 3970: Grafton Electric has 2068 rates
2068 of 3970: Graham County Electric Coop Inc has 2069 rates
2069 of 3970: Grand Electric Coop, Inc has 2070 rates
2070 of 3970: Grand Rapids Public Util Comm has 2071 rates
2071 of 3970: Grand River Dam Authority has 2072 rates
2072 of 3970: Grand Valley Rrl Pwr Line, Inc has 2073 rates
2073 of 3970: Granite State Electric Co has 2074 rates
2074 of 3970: Granite State Electric Co (New Hampshire) has 2075 rates
2075 of 3970: Grant Country Public Utility has 2076 rates
2076 of 3970: Grayson Rural Electric Coop Corp has 2077 rates
2077 of 3970: Grayson-Collin Elec Coop, Inc has 2078 rates
2078 of 3970: Great Bay Power Marketing, Inc. has 2079 rates
2079 of 3970: Great Lakes Energy Coop has 2080 rates
2080 of 3970: Great River Energy has 2081 rates
2081 of 3970: Green Mountain Energy Company has 2082 rates
2082 of 3970: Green Mountain Power Corp has 2083 rates
2083 of 3970: Greenbelt Electric Coop, Inc has 2084 rates
2084 of 3970: Greenville Utilities Comm has 2085 rates
2085 of 3970: Greenwood Commissioners-Pub Wk has 2086 rates
2086 of 3970: Greenwood Utilities Comm has 2087 rates
2087 of 3970: Greer Commission of Public Wks has 2088 rates
2088 of 3970: GreyStone has 2089 rates
2089 of 3970: GreyStone Power Corporation has 2090 rates
2090 of 3970: Groton Dept of Utilities has 2091 rates
2091 of 3970: Grundy Center Mun Light & Power has 2092 rates
2092 of 3970: Grundy County Rural Elec Coop has 2093 rates
2093 of 3970: Grundy Electric Coop, Inc has 2094 rates
2094 of 3970: Grundy Electric Coop, Inc (Iowa) has 2095 rates
2095 of 3970: Guadalupe Blanco River Auth has 2096 rates
2096 of 3970: Guadalupe Valley Elec Coop Inc has 2097 rates
2097 of 3970: Guam Power Authority has 2098 rates
2098 of 3970: Guernsey-Muskingum El Coop Inc has 2099 rates
2099 of 3970: Gulf Coast Electric Coop, Inc has 2100 rates
2100 of 3970: Gulf Power Co has 2101 rates
2101 of 3970: Gunnison County Elec Assn. has 2102 rates
2102 of 3970: Guntersville Electric Board has 2103 rates
2103 of 3970: Gustavus Electric Inc has 2104 rates
2104 of 3970: Guthrie County Rural E C A has 2105 rates
2105 of 3970: Gwitchyaa Zhee Utility Co has 2106 rates
2106 of 3970: H-D Electric Coop Inc has 2107 rates
2107 of 3970: H-D Electric Coop Inc (Minnesota) has 2108 rates
2108 of 3970: Habersham Electric Membership Corp has 2109 rates
2109 of 3970: Hagerstown Light Department has 2110 rates
2110 of 3970: Halifax Electric Member Corp has 2111 rates
2111 of 3970: Hamilton County Elec Coop Assn has 2112 rates
2112 of 3970: Hancock County Rural E M C has 2113 rates
2113 of 3970: Hancock-Wood Electric Coop Inc has 2114 rates
2114 of 3970: Harmon Electric Assn Inc has 2115 rates
2115 of 3970: Harney Electric Coop, Inc has 2116 rates
2116 of 3970: Harney Electric Coop, Inc (Nevada) has 2117 rates
2117 of 3970: Harquahala Valley Pwr District has 2118 rates
2118 of 3970: Harrison County Rrl Elec Coop has 2119 rates
2119 of 3970: Harrison County Rural E M C has 2120 rates
2120 of 3970: Harrison Rural Elec Assn, Inc has 2121 rates
2121 of 3970: Hart Electric Member Corp has 2122 rates
2122 of 3970: Hartford Electric has 2123 rates
2123 of 3970: Hartford Steam Co has 2124 rates
2124 of 3970: Harvard Dedicated Energy Limited has 2125 rates
2125 of 3970: Havana Power & Light Company has 2126 rates
2126 of 3970: Hawaii Electric Light Co Inc has 2127 rates
2127 of 3970: Hawaiian Electric Co Inc has 2128 rates
2128 of 3970: Hawkeye Tri-County El Coop Inc has 2129 rates
2129 of 3970: Hawley Public Utilities Comm has 2130 rates
2130 of 3970: Haywood Electric Member Corp has 2131 rates
2131 of 3970: Heart of Texas Electric Coop has 2132 rates
2132 of 3970: Heartland Consumers Power Dist has 2133 rates
2133 of 3970: Heartland Power Coop has 2134 rates
2134 of 3970: Heartland Power Coop (Minnesota) has 2135 rates
2135 of 3970: Heartland Rural Elec Coop, Inc has 2136 rates
2136 of 3970: Heber Light & Power Company has 2137 rates
2137 of 3970: HECO has 2138 rates
2138 of 3970: Henderson City Utility Comm has 2139 rates
2139 of 3970: Hendricks County Rural E M C has 2140 rates
2140 of 3970: Henry County Rural E M C has 2141 rates
2141 of 3970: Hess Retail Natural Gas and Elec. Acctg. has 2142 rates
2142 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Connecticut) has 2143 rates
2143 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Delaware) has 2144 rates
2144 of 3970: Hess Retail Natural Gas and Elec. Acctg. (District of Columbia) has 2145 rates
2145 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Maine) has 2146 rates
2146 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Maryland) has 2147 rates
2147 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Massachusetts) has 2148 rates
2148 of 3970: Hess Retail Natural Gas and Elec. Acctg. (New Hampshire) has 2149 rates
2149 of 3970: Hess Retail Natural Gas and Elec. Acctg. (New York) has 2150 rates
2150 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Pennsylvania) has 2151 rates
2151 of 3970: Hess Retail Natural Gas and Elec. Acctg. (Rhode Island) has 2152 rates
2152 of 3970: Hibbing Public Utilities Comm has 2153 rates
2153 of 3970: Hickman-Fulton Counties RECC has 2154 rates
2154 of 3970: High Plains Power Inc has 2155 rates
2155 of 3970: High West Energy, Inc has 2156 rates
2156 of 3970: High West Energy, Inc (Nebraska) has 2157 rates
2157 of 3970: High West Energy, Inc (Wyoming) has 2158 rates
2158 of 3970: Highline Electric Assn has 2159 rates
2159 of 3970: HILCO Electric Cooperative, Inc. has 2160 rates
2160 of 3970: Hill County Electric Coop, Inc has 2161 rates
2161 of 3970: Hillsdale Board of Public Wks has 2162 rates
2162 of 3970: Hino Electric Holding Company, LP. has 2163 rates
2163 of 3970: Hinson Power Company LLC has 2164 rates
2164 of 3970: Hinson Power Company LLC (Montana) has 2165 rates
2165 of 3970: Hohokam Irr & Drain Dist has 2166 rates
2166 of 3970: Holmes-Wayne Electric Coop Inc has 2167 rates
2167 of 3970: Holston Electric Coop, Inc has 2168 rates
2168 of 3970: Holy Cross Electric Assn, Inc has 2169 rates
2169 of 3970: Homer Electric Assn Inc has 2170 rates
2170 of 3970: Hood River Electric Coop has 2171 rates
2171 of 3970: Hoosier Energy R E C, Inc has 2172 rates
2172 of 3970: Hooversville Boro Elec Lgt Co has 2173 rates
2173 of 3970: Horry Electric Coop Inc has 2174 rates
2174 of 3970: Houlton Water Company has 2175 rates
2175 of 3970: Houston County Elec Coop Inc has 2176 rates
2176 of 3970: Howard Electric Coop has 2177 rates
2177 of 3970: Howard Greeley Rural P P D has 2178 rates
2178 of 3970: Howell-Oregon Elec Coop, Inc has 2179 rates
2179 of 3970: HQ Energy Services (US), Inc has 2180 rates
2180 of 3970: Hudson Energy Services has 2181 rates
2181 of 3970: Hudson Energy Services (Illinois) has 2182 rates
2182 of 3970: Hudson Energy Services (Texas) has 2183 rates
2183 of 3970: Hudson Municipal Electric Utility has 2184 rates
2184 of 3970: Hughes Power & Light Co has 2185 rates
2185 of 3970: Hull Municipal Light Plant has 2186 rates
2186 of 3970: Humboldt County R E C has 2187 rates
2187 of 3970: Hunterdon Cogeneration LP has 2188 rates
2188 of 3970: Huntsville Utilities has 2189 rates
2189 of 3970: Hurricane Power Committee has 2190 rates
2190 of 3970: Hustisford Utilities has 2191 rates
2191 of 3970: Hutchinson Utilities Comm has 2192 rates
2192 of 3970: Hyrum City Corporation (Utility Company) has 2193 rates
2193 of 3970: I-N-N Electric Coop, Inc has 2194 rates
2194 of 3970: Idaho Cnty L&P Coop Assn, Inc has 2195 rates
2195 of 3970: Idaho Power Co has 2196 rates
2196 of 3970: Idaho Power Co (Oregon) has 2197 rates
2197 of 3970: IDT Energy, Inc. has 2198 rates
2198 of 3970: IDT Energy, Inc. (New York) has 2199 rates
2199 of 3970: Igiugig Electric Company has 2200 rates
2200 of 3970: IID has 2201 rates
2201 of 3970: Illinois Municipal Elec Agency has 2202 rates
2202 of 3970: Illinois Rural Electric Coop has 2203 rates
2203 of 3970: Imperial Irrigation District has 2204 rates
2204 of 3970: Independence Power Marketing has 2205 rates
2205 of 3970: Indian Electric Coop, Inc has 2206 rates
2206 of 3970: Indiana Michigan Power Co (Indiana) has 2207 rates
2207 of 3970: Indiana Michigan Power Co (Michigan) has 2208 rates
2208 of 3970: Indiana Municipal Power Agency has 2209 rates
2209 of 3970: Indiana-Kentucky Electric Corp has 2210 rates
2210 of 3970: Indianapolis Power & Light Co has 2211 rates
2211 of 3970: Indianola Municipal Utilities has 2212 rates
2212 of 3970: Inland Power & Light Company has 2213 rates
2213 of 3970: Inside Passage Elec Coop, Inc has 2214 rates
2214 of 3970: Integrys has 2215 rates
2215 of 3970: Integrys Energy Services of N.Y., Inc. has 2216 rates
2216 of 3970: Integrys Energy Services, Inc. has 2217 rates
2217 of 3970: Integrys Energy Services, Inc. (Connecticut) has 2218 rates
2218 of 3970: Integrys Energy Services, Inc. (Delaware) has 2219 rates
2219 of 3970: Integrys Energy Services, Inc. (District of Columbia) has 2220 rates
2220 of 3970: Integrys Energy Services, Inc. (Illinois) has 2221 rates
2221 of 3970: Integrys Energy Services, Inc. (Maine) has 2222 rates
2222 of 3970: Integrys Energy Services, Inc. (Maryland) has 2223 rates
2223 of 3970: Integrys Energy Services, Inc. (Massachusetts) has 2224 rates
2224 of 3970: Integrys Energy Services, Inc. (Michigan) has 2225 rates
2225 of 3970: Integrys Energy Services, Inc. (New Hampshire) has 2226 rates
2226 of 3970: Integrys Energy Services, Inc. (New Jersey) has 2227 rates
2227 of 3970: Integrys Energy Services, Inc. (Ohio) has 2228 rates
2228 of 3970: Integrys Energy Services, Inc. (Pennsylvania) has 2229 rates
2229 of 3970: Integrys Energy Services, Inc. (Rhode Island) has 2230 rates
2230 of 3970: Intelligent Energy/Infinite Energy, Inc. has 2231 rates
2231 of 3970: Intelligent Energy/Infinite Energy, Inc. (Texas) has 2232 rates
2232 of 3970: Inter County Energy Coop Corp has 2233 rates
2233 of 3970: Intercounty Electric Coop Assn has 2234 rates
2234 of 3970: Intermountain Power Agency has 2235 rates
2235 of 3970: Intermountain Rural Elec Assn has 2236 rates
2236 of 3970: Interstate Power and Light Co has 2237 rates
2237 of 3970: Interstate Power and Light Co (Minnesota) has 2238 rates
2238 of 3970: Iowa Lakes Electric Coop has 2239 rates
2239 of 3970: Ipnatchiaq Electric Company has 2240 rates
2240 of 3970: IPT SRI Cogeneration Inc has 2241 rates
2241 of 3970: Irwin Electric Membership Corp has 2242 rates
2242 of 3970: Itasca-Mantrap Co-op Electrical Assn has 2243 rates
2243 of 3970: ITC Great Plains, LLC has 2244 rates
2244 of 3970: ITC Midwest LLC has 2245 rates
2245 of 3970: ITC Transmission has 2246 rates
2246 of 3970: J-A-C Electric Coop Inc has 2247 rates
2247 of 3970: Jackson County Rural E M C has 2248 rates
2248 of 3970: Jackson Electric Coop, Inc has 2249 rates
2249 of 3970: Jackson Electric Coop, Inc (Texas) has 2250 rates
2250 of 3970: Jackson Electric Member Corp has 2251 rates
2251 of 3970: Jackson Energy Coop Corp has 2252 rates
2252 of 3970: Jackson Purchase Energy Corporation has 2253 rates
2253 of 3970: Jacksonville Electric Authority has 2254 rates
2254 of 3970: Jamestown Board of Public Util has 2255 rates
2255 of 3970: Jasper County Rural E M C has 2256 rates
2256 of 3970: Jasper-Newton Elec Coop, Inc has 2257 rates
2257 of 3970: Jay County Rural E M C has 2258 rates
2258 of 3970: JCP&L has 2259 rates
2259 of 3970: JEA has 2260 rates
2260 of 3970: Jefferson Davis Elec Coop, Inc has 2261 rates
2261 of 3970: Jefferson Electric Member Corp has 2262 rates
2262 of 3970: Jefferson Utilities has 2263 rates
2263 of 3970: Jemez Mountains Elec Coop, Inc has 2264 rates
2264 of 3970: Jersey Central Power & Lt Co (New Jersey) has 2265 rates
2265 of 3970: Jo-Carroll Energy Coop Inc has 2266 rates
2266 of 3970: Joe Wheeler Elec Member Corp has 2267 rates
2267 of 3970: Johnson County Rural E M C has 2268 rates
2268 of 3970: Jones-Onslow Elec Member Corp has 2269 rates
2269 of 3970: JP Morgan has 2270 rates
2270 of 3970: JP Morgan (Oregon) has 2271 rates
2271 of 3970: JP Morgan (Washington) has 2272 rates
2272 of 3970: Jump River Electric Coop Inc has 2273 rates
2273 of 3970: Juneau Utility Comm has 2274 rates
2274 of 3970: Just Energy has 2275 rates
2275 of 3970: Just Energy New York Corp. has 2276 rates
2276 of 3970: Just Energy New York Corp. (New York) has 2277 rates
2277 of 3970: K C Electric Association has 2278 rates
2278 of 3970: KAMO Electric Coop Inc has 2279 rates
2279 of 3970: Kandiyohi Power Coop has 2280 rates
2280 of 3970: Kankakee Valley Rural E M C has 2281 rates
2281 of 3970: Kanosh Town Corporation (Utility Company) has 2282 rates
2282 of 3970: Kansas City Power & Light Co has 2283 rates
2283 of 3970: Kansas City Power & Light Co (Missouri) has 2284 rates
2284 of 3970: Kansas Electric Power Coop Inc has 2285 rates
2285 of 3970: Kansas Gas & Electric Co has 2286 rates
2286 of 3970: Kansas Municipal Energy Agency has 2287 rates
2287 of 3970: Karnes Electric Coop Inc has 2288 rates
2288 of 3970: Kauai Island Utility Cooperative has 2289 rates
2289 of 3970: Kaw Valley Electric Coop Inc has 2290 rates
2290 of 3970: Kay Electric Coop has 2291 rates
2291 of 3970: Kaysville City Corporation (Utility Company) has 2292 rates
2292 of 3970: KBR Rural Public Power District has 2293 rates
2293 of 3970: KCP&L has 2294 rates
2294 of 3970: KCP&L Greater Missouri Operations has 2295 rates
2295 of 3970: Keewatin Public Utilities has 2296 rates
2296 of 3970: KEM Electric Coop Inc has 2297 rates
2297 of 3970: Kenergy Corp has 2298 rates
2298 of 3970: Kennebunk Light & Power Dist has 2299 rates
2299 of 3970: Kentucky Power Co has 2300 rates
2300 of 3970: Kentucky Utilities Co has 2301 rates
2301 of 3970: Kentucky Utilities Co (Tennessee) has 2302 rates
2302 of 3970: Kentucky Utilities Co (Virginia) has 2303 rates
2303 of 3970: Kenyon Municipal Utilities has 2304 rates
2304 of 3970: Keosauqua Municipal Light & Pwr has 2305 rates
2305 of 3970: Kerrville Public Utility Board has 2306 rates
2306 of 3970: Ketchikan Public Utilities has 2307 rates
2307 of 3970: Kiamichi Electric Coop, Inc has 2308 rates
2308 of 3970: Kinetic Energy LLC has 2309 rates
2309 of 3970: King City Community Power has 2310 rates
2310 of 3970: Kings River Conservation Dist has 2311 rates
2311 of 3970: Kingsbury Electric Coop, Inc has 2312 rates
2312 of 3970: Kingsport Power Co (Tennessee) has 2313 rates
2313 of 3970: Kirbyville Light & Power Co has 2314 rates
2314 of 3970: Kissimmee Utility Authority has 2315 rates
2315 of 3970: Kit Carson Electric Coop, Inc has 2316 rates
2316 of 3970: Kiwash Electric Coop, Inc has 2317 rates
2317 of 3970: Knoxville Utilities Board has 2318 rates
2318 of 3970: Kodiak Electric Assn Inc has 2319 rates
2319 of 3970: Kokhanok Village Council (Utility Company) has 2320 rates
2320 of 3970: Kootenai Electric Cooperative has 2321 rates
2321 of 3970: Kosciusko County Rural E M C has 2322 rates
2322 of 3970: Kotzebue Electric Assn Inc has 2323 rates
2323 of 3970: KUB has 2324 rates
2324 of 3970: Kuiggluum Kallugvia has 2325 rates
2325 of 3970: Kwig Power Company has 2326 rates
2326 of 3970: L & O Power Co-operative has 2327 rates
2327 of 3970: La Farge Municipal Electric Co has 2328 rates
2328 of 3970: La Plata Electric Assn, Inc has 2329 rates
2329 of 3970: La Plata Electric Association has 2330 rates
2330 of 3970: La Porte City Utilities has 2331 rates
2331 of 3970: Laclede Electric Coop, Inc has 2332 rates
2332 of 3970: LaCreek Electric Assn, Inc has 2333 rates
2333 of 3970: LaCreek Electric Assn, Inc (Nebraska) has 2334 rates
2334 of 3970: LADWP has 2335 rates
2335 of 3970: Lafayette Public Power Auth has 2336 rates
2336 of 3970: Lagrange County Rural E M C has 2337 rates
2337 of 3970: Lake Country Power has 2338 rates
2338 of 3970: Lake Mills Light & Water has 2339 rates
2339 of 3970: Lake Placid Village, Inc (Utility Company) has 2340 rates
2340 of 3970: Lake Region Electric Assn, Inc has 2341 rates
2341 of 3970: Lake Region Electric Coop, Inc has 2342 rates
2342 of 3970: Lake Region Electric Cooperative has 2343 rates
2343 of 3970: Lakeview Light & Power has 2344 rates
2344 of 3970: Lamar County Elec Coop Assn has 2345 rates
2345 of 3970: Lamb County Electric Coop, Inc has 2346 rates
2346 of 3970: Lane Electric Coop Inc has 2347 rates
2347 of 3970: Lane-Scott Electric Coop, Inc has 2348 rates
2348 of 3970: Lanesboro Public Utility Comm has 2349 rates
2349 of 3970: Langford Wind Power LLC has 2350 rates
2350 of 3970: Lansing Board of Water & Light has 2351 rates
2351 of 3970: Lassen Municipal Utility District has 2352 rates
2352 of 3970: Laurens Electric Coop, Inc has 2353 rates
2353 of 3970: Lawrenceburg Municipal Utils has 2354 rates
2354 of 3970: LCEC has 2355 rates
2355 of 3970: Lea County Electric Coop, Inc has 2356 rates
2356 of 3970: Lea County Electric Coop, Inc (Texas) has 2357 rates
2357 of 3970: Leavenworth-Jefferson E C, Inc has 2358 rates
2358 of 3970: Lee County Electric Coop, Inc has 2359 rates
2359 of 3970: Lehi City Corporation (Utility Company) has 2360 rates
2360 of 3970: LES has 2361 rates
2361 of 3970: Levan Town Corporation (Utility Company) has 2362 rates
2362 of 3970: Lewis County Rural E C A has 2363 rates
2363 of 3970: Liberty Power has 2364 rates
2364 of 3970: Liberty Power Corp. has 2365 rates
2365 of 3970: Liberty Power Corp. (California) has 2366 rates
2366 of 3970: Liberty Power Corp. (Connecticut) has 2367 rates
2367 of 3970: Liberty Power Corp. (Delaware) has 2368 rates
2368 of 3970: Liberty Power Corp. (District of Columbia) has 2369 rates
2369 of 3970: Liberty Power Corp. (Illinois) has 2370 rates
2370 of 3970: Liberty Power Corp. (Maine) has 2371 rates
2371 of 3970: Liberty Power Corp. (Maryland) has 2372 rates
2372 of 3970: Liberty Power Corp. (Massachusetts) has 2373 rates
2373 of 3970: Liberty Power Corp. (New Jersey) has 2374 rates
2374 of 3970: Liberty Power Corp. (New York) has 2375 rates
2375 of 3970: Liberty Power Corp. (Pennsylvania) has 2376 rates
2376 of 3970: Liberty Power Corp. (Rhode Island) has 2377 rates
2377 of 3970: Liberty Power Corp. (Texas) has 2378 rates
2378 of 3970: Licking Rural Electric Inc has 2379 rates
2379 of 3970: Licking Valley Rural E C C has 2380 rates
2380 of 3970: Lighthouse Electric Coop, Inc has 2381 rates
2381 of 3970: Lincoln County Power Dist No 1 has 2382 rates
2382 of 3970: Lincoln Electric Coop, Inc has 2383 rates
2383 of 3970: Lincoln Electric System has 2384 rates
2384 of 3970: Linde Energy Services, Inc. has 2385 rates
2385 of 3970: Linde Energy Services, Inc. (Delaware) has 2386 rates
2386 of 3970: Linde Energy Services, Inc. (Illinois) has 2387 rates
2387 of 3970: Linde Energy Services, Inc. (Maine) has 2388 rates
2388 of 3970: Linde Energy Services, Inc. (New York) has 2389 rates
2389 of 3970: Linde Energy Services, Inc. (Pennsylvania) has 2390 rates
2390 of 3970: Linn County Rural E C A has 2391 rates
2391 of 3970: Litchfield Public Utilities has 2392 rates
2392 of 3970: Little Ocmulgee El Member Corp has 2393 rates
2393 of 3970: Little River Electric Coop Inc has 2394 rates
2394 of 3970: Lockhart Power Co has 2395 rates
2395 of 3970: Lockwood Water & Light Company has 2396 rates
2396 of 3970: Logan County Coop Power & Light has 2397 rates
2397 of 3970: Long Island Power Authority has 2398 rates
2398 of 3970: Lorain-Medina R E C, Inc has 2399 rates
2399 of 3970: Los Alamos County has 2400 rates
2400 of 3970: Los Angeles Department of Water & Power has 2401 rates
2401 of 3970: Los Medanos Energy Center LLC has 2402 rates
2402 of 3970: Lost River Electric Coop Inc has 2403 rates
2403 of 3970: Loudon Utilities Board has 2404 rates
2404 of 3970: Louisiana Energy & Power Auth has 2405 rates
2405 of 3970: Louisville Electric System has 2406 rates
2406 of 3970: Louisville Gas & Electric Co has 2407 rates
2407 of 3970: Loup River Public Power Dist has 2408 rates
2408 of 3970: Loup Valleys Rural P P D has 2409 rates
2409 of 3970: Lower Colorado River Authority has 2410 rates
2410 of 3970: Lower Valley Energy Inc has 2411 rates
2411 of 3970: Lower Valley Energy Inc (Wyoming) has 2412 rates
2412 of 3970: Lower Yellowstone R E A, Inc has 2413 rates
2413 of 3970: Lower Yellowstone R E A, Inc (North Dakota) has 2414 rates
2414 of 3970: LPEA has 2415 rates
2415 of 3970: Lubbock Power & Light has 2416 rates
2416 of 3970: Lumbee River Elec Member Corp has 2417 rates
2417 of 3970: Luminant Energy has 2418 rates
2418 of 3970: Lynches River Elec Coop, Inc has 2419 rates
2419 of 3970: Lyntegar Electric Coop, Inc has 2420 rates
2420 of 3970: Lyon Rural Electric Coop has 2421 rates
2421 of 3970: Lyon-Coffey Electric Coop, Inc has 2422 rates
2422 of 3970: Lyon-Lincoln Electric Coop Inc has 2423 rates
2423 of 3970: M & A Electric Power Coop has 2424 rates
2424 of 3970: M J M Electric Cooperative Inc has 2425 rates
2425 of 3970: Macon Electric Coop has 2426 rates
2426 of 3970: Macquarie Energy LLC has 2427 rates
2427 of 3970: Madison Gas & Electric Co has 2428 rates
2428 of 3970: Madisonville Municipal Utils has 2429 rates
2429 of 3970: Magic Valley Electric Coop Inc has 2430 rates
2430 of 3970: Magnolia Electric Power Assn has 2431 rates
2431 of 3970: Maine Public Service Co has 2432 rates
2432 of 3970: Major Energy Electric Services has 2433 rates
2433 of 3970: Manitowoc Public Utilities has 2434 rates
2434 of 3970: Maquoketa Valley Rrl Elec Coop has 2435 rates
2435 of 3970: Marias River Electric Coop Inc has 2436 rates
2436 of 3970: Maricopa County M W C Dist has 2437 rates
2437 of 3970: Marin Clean Energy has 2438 rates
2438 of 3970: Marin Energy Authority has 2439 rates
2439 of 3970: Marlboro Electric Coop, Inc has 2440 rates
2440 of 3970: Marshall County Rural E M C has 2441 rates
2441 of 3970: Marshall-De Kalb Electric Coop has 2442 rates
2442 of 3970: Maryville Utilities has 2443 rates
2443 of 3970: Massachusetts Bay Trans Auth has 2444 rates
2444 of 3970: Massachusetts Electric Co has 2445 rates
2445 of 3970: Massachusetts Mun Wholes Electric Co has 2446 rates
2446 of 3970: Matanuska Electric Assn Inc has 2447 rates
2447 of 3970: Matinicus Plantation Elec Co has 2448 rates
2448 of 3970: Maui Electric Co Ltd has 2449 rates
2449 of 3970: MC Squared Energy Services, LLC has 2450 rates
2450 of 3970: McCone Electric Coop Inc has 2451 rates
2451 of 3970: McCook Public Power District has 2452 rates
2452 of 3970: McDonough Power Coop has 2453 rates
2453 of 3970: MCE has 2454 rates
2454 of 3970: McGrath Light & Power Co has 2455 rates
2455 of 3970: McKenzie Electric Coop Inc has 2456 rates
2456 of 3970: McKenzie Electric Coop Inc (North Dakota) has 2457 rates
2457 of 3970: McLean Electric Coop, Inc has 2458 rates
2458 of 3970: McLeod Cooperative Power Assn has 2459 rates
2459 of 3970: McMinnville Electric System has 2460 rates
2460 of 3970: McMullen Valley Water C&D Dist has 2461 rates
2461 of 3970: MDU has 2462 rates
2462 of 3970: MDU Resources Group Inc has 2463 rates
2463 of 3970: MDU Resources Group Inc (North Dakota) has 2464 rates
2464 of 3970: MDU Resources Group Inc (South Dakota) has 2465 rates
2465 of 3970: MDU Resources Group Inc (Wyoming) has 2466 rates
2466 of 3970: Meade County Rural E C C has 2467 rates
2467 of 3970: Meadow Town Corporation (Utility Company) has 2468 rates
2468 of 3970: Mecklenburg Electric Coop, Inc has 2469 rates
2469 of 3970: Mecklenburg Electric Coop, Inc (North Carolina) has 2470 rates
2470 of 3970: Medical Area Total Egy Plt Inc has 2471 rates
2471 of 3970: Medina Electric Coop, Inc has 2472 rates
2472 of 3970: Meeker Coop Light & Power Assn has 2473 rates
2473 of 3970: Mega Energy, LP has 2474 rates
2474 of 3970: Melrose Public Utilities has 2475 rates
2475 of 3970: Memphis Light, Gas & Water has 2476 rates
2476 of 3970: Menard Electric Coop has 2477 rates
2477 of 3970: Merced Irrigation District has 2478 rates
2478 of 3970: Meriwether Lewis Electric Coop has 2479 rates
2479 of 3970: Merrill Lynch Commodities has 2480 rates
2480 of 3970: Metlakatla Power & Light has 2481 rates
2481 of 3970: Metropolitan Edison Co (Pennsylvania) has 2482 rates
2482 of 3970: Metropolitan Water District of S CA has 2483 rates
2483 of 3970: MGE has 2484 rates
2484 of 3970: Miami Power Corporation has 2485 rates
2485 of 3970: Miami-Cass County Rural E M C has 2486 rates
2486 of 3970: Michigan Electric Transmission Company has 2487 rates
2487 of 3970: Michigan Public Power Agency has 2488 rates
2488 of 3970: Michigan South Central Pwr Agy has 2489 rates
2489 of 3970: MID has 2490 rates
2490 of 3970: Mid-Carolina Electric Coop Inc has 2491 rates
2491 of 3970: Mid-Kansas Electric Company, LLC (MKEC) has 2492 rates
2492 of 3970: Mid-Ohio Energy Coop, Inc has 2493 rates
2493 of 3970: Mid-South Electric Coop Assn has 2494 rates
2494 of 3970: Mid-Yellowstone Elec Coop, Inc has 2495 rates
2495 of 3970: MidAmerican Energy Co has 2496 rates
2496 of 3970: MidAmerican Energy Co (Illinois) has 2497 rates
2497 of 3970: MidAmerican Energy Co (South Dakota) has 2498 rates
2498 of 3970: Middle Georgia El Member Corp has 2499 rates
2499 of 3970: Middle Kuskokwim Elec Coop Inc has 2500 rates
2500 of 3970: Middle Tennessee E M C has 2501 rates
2501 of 3970: Midland Power Coop has 2502 rates
2502 of 3970: Midstate Electric Coop, Inc has 2503 rates
2503 of 3970: Midvale Irrigation District has 2504 rates
2504 of 3970: Midwest Electric Member Corp has 2505 rates
2505 of 3970: Midwest Electric, Inc has 2506 rates
2506 of 3970: Midwest Energy Cooperative has 2507 rates
2507 of 3970: Midwest Energy Inc has 2508 rates
2508 of 3970: Milagro Power Company has 2509 rates
2509 of 3970: Mille Lacs Energy Cooperative has 2510 rates
2510 of 3970: Minnesota Municipal Power Agency has 2511 rates
2511 of 3970: Minnesota Power Inc has 2512 rates
2512 of 3970: Minnesota Valley Coop L&P Assn has 2513 rates
2513 of 3970: Minnesota Valley Electric Coop has 2514 rates
2514 of 3970: Minnkota Power Coop, Inc has 2515 rates
2515 of 3970: Mirant Energy Trading, LLC has 2516 rates
2516 of 3970: Mississippi County Electric Coop has 2517 rates
2517 of 3970: Mississippi Power Co has 2518 rates
2518 of 3970: Missoula Electric Coop, Inc has 2519 rates
2519 of 3970: Missoula Electric Coop, Inc (Montana) has 2520 rates
2520 of 3970: Missouri River Energy Services has 2521 rates
2521 of 3970: Missouri Rural Electric Coop has 2522 rates
2522 of 3970: Mitchell Electric Member Corp has 2523 rates
2523 of 3970: MLGW has 2524 rates
2524 of 3970: MMA Belmar Power LLC has 2525 rates
2525 of 3970: MMA DAS Power has 2526 rates
2526 of 3970: MMA Fresno Power LP has 2527 rates
2527 of 3970: MMA GDC Power LP has 2528 rates
2528 of 3970: MMA LA Power LP has 2529 rates
2529 of 3970: MMA WBF Power LP has 2530 rates
2530 of 3970: Modern Electric Water Company has 2531 rates
2531 of 3970: Modesto Irrigation District has 2532 rates
2532 of 3970: Mohave Electric Cooperative, Inc has 2533 rates
2533 of 3970: Mohawk Municipal Comm has 2534 rates
2534 of 3970: Mohegan Tribal Utility Auth has 2535 rates
2535 of 3970: Monongahela Power Co (West Virginia) has 2536 rates
2536 of 3970: Monroe County Elec Coop, Inc has 2537 rates
2537 of 3970: Monroe County Elec Power Assn has 2538 rates
2538 of 3970: Mont Alto Borough has 2539 rates
2539 of 3970: Montana-Dakota Utilities Co has 2540 rates
2540 of 3970: Montana-Dakota Utilities Co (North Dakota) has 2541 rates
2541 of 3970: Montana-Dakota Utilities Co (South Dakota) has 2542 rates
2542 of 3970: Montana-Dakota Utilities Co (Wyoming) has 2543 rates
2543 of 3970: Monterey Bay Community Power has 2544 rates
2544 of 3970: Moon Lake Electric Assn Inc has 2545 rates
2545 of 3970: Moon Lake Electric Assn Inc (Utah) has 2546 rates
2546 of 3970: Moorhead Public Service Utilty has 2547 rates
2547 of 3970: Moose Lake Water & Light Comm has 2548 rates
2548 of 3970: Mor-Gran-Sou Electric Coop Inc has 2549 rates
2549 of 3970: Mora-San Miguel Elec Coop, Inc has 2550 rates
2550 of 3970: Moreau-Grand Electric Coop Inc has 2551 rates
2551 of 3970: Morenci Water and Electric Co has 2552 rates
2552 of 3970: Morgan County Rural Elec Assn has 2553 rates
2553 of 3970: Morgan Stanley Capital Grp Inc has 2554 rates
2554 of 3970: Morris Cogeneration LLC has 2555 rates
2555 of 3970: Mountain Electric Coop, Inc has 2556 rates
2556 of 3970: Mountain Electric Coop, Inc (North Carolina) has 2557 rates
2557 of 3970: Mountain Parks Electric, Inc has 2558 rates
2558 of 3970: Mountain View Elec Assn, Inc has 2559 rates
2559 of 3970: Mountrail-Williams Elec Coop has 2560 rates
2560 of 3970: MSR Public Power Agency has 2561 rates
2561 of 3970: Mt Carmel Public Utility Co has 2562 rates
2562 of 3970: Mt Wheeler Power, Inc has 2563 rates
2563 of 3970: Mt Wheeler Power, Inc (Utah) has 2564 rates
2564 of 3970: Municipal Electric Authority has 2565 rates
2565 of 3970: Municipal Energy Agency of MS has 2566 rates
2566 of 3970: Municipal Energy Agency of NE has 2567 rates
2567 of 3970: MxEnergy Electric, Inc. has 2568 rates
2568 of 3970: MxEnergy Electric, Inc. (Connecticut) has 2569 rates
2569 of 3970: MxEnergy Electric, Inc. (Massachusetts) has 2570 rates
2570 of 3970: MxEnergy Electric, Inc. (New York) has 2571 rates
2571 of 3970: MxEnergy Electric, Inc. (Pennsylvania) has 2572 rates
2572 of 3970: N W Electric Power Coop, Inc has 2573 rates
2573 of 3970: Naknek Electric Association has 2574 rates
2574 of 3970: Nantucket Electric Co has 2575 rates
2575 of 3970: Nantucket Electric Co (Massachusetts) has 2576 rates
2576 of 3970: Napakiak Ircinraq Power Co has 2577 rates
2577 of 3970: Nashville Electric Service has 2578 rates
2578 of 3970: Natchez Trace Elec Power Assn has 2579 rates
2579 of 3970: National Grid Generation, LLC has 2580 rates
2580 of 3970: National Grid of Massachusetts has 2581 rates
2581 of 3970: National Grid of New York has 2582 rates
2582 of 3970: Native Village of Perryville, Alaska (Utility Company) has 2583 rates
2583 of 3970: Navajo Tribal Utility Authority has 2584 rates
2584 of 3970: Navarro County Elec Coop, Inc has 2585 rates
2585 of 3970: Navasota Valley Elec Coop, Inc has 2586 rates
2586 of 3970: Navopache Electric Coop, Inc has 2587 rates
2587 of 3970: Nebraska Electric G&T Coop Inc has 2588 rates
2588 of 3970: Nebraska Public Power District has 2589 rates
2589 of 3970: Nelson Lagoon Elec Coop Inc has 2590 rates
2590 of 3970: Nemaha-Marshall E C A, Inc has 2591 rates
2591 of 3970: Nephi City Corporation (Utility Company) has 2592 rates
2592 of 3970: Nespelem Valley Elec Coop, Inc has 2593 rates
2593 of 3970: Nevada Irrigation District has 2594 rates
2594 of 3970: Nevada Power Co has 2595 rates
2595 of 3970: New Castle Municipal Serv Comm has 2596 rates
2596 of 3970: New England Elec Transm'n Corp has 2597 rates
2597 of 3970: New England Hydro-Tran Elec Co has 2598 rates
2598 of 3970: New England Hydro-Trans Corp has 2599 rates
2599 of 3970: New England Power Company has 2600 rates
2600 of 3970: New Enterprise R E C, Inc has 2601 rates
2601 of 3970: New Hampshire Elec Coop Inc has 2602 rates
2602 of 3970: New Hampton Village Precinct (Utility Company) has 2603 rates
2603 of 3970: New London Electric&Water Util has 2604 rates
2604 of 3970: New London Municipal Utilities has 2605 rates
2605 of 3970: New Prague Utilities Comm has 2606 rates
2606 of 3970: New River Light & Power Co has 2607 rates
2607 of 3970: New Ulm Public Utilities Comm has 2608 rates
2608 of 3970: New York Industrial Energy Buyers, LLC has 2609 rates
2609 of 3970: New York Mun Power Agency has 2610 rates
2610 of 3970: New York Power Authority has 2611 rates
2611 of 3970: New York State Elec & Gas Corp has 2612 rates
2612 of 3970: New-Mac Electric Coop, Inc has 2613 rates
2613 of 3970: Newberry Electric Coop, Inc has 2614 rates
2614 of 3970: Newberry Water & Light Board has 2615 rates
2615 of 3970: Newnan Wtr, Sewer & Light Comm has 2616 rates
2616 of 3970: Newton County Rural E M C has 2617 rates
2617 of 3970: NextEra Energy Power Marketing LLC has 2618 rates
2618 of 3970: NextEra Energy Power Marketing LLC (Maine) has 2619 rates
2619 of 3970: NextEra Energy Power Marketing LLC (Massachusetts) has 2620 rates
2620 of 3970: NextEra Retail of Texas LP has 2621 rates
2621 of 3970: Niagara Mohawk Power Corp. has 2622 rates
2622 of 3970: Nick's Utility has 2623 rates
2623 of 3970: Ninnescah Rural E C A Inc has 2624 rates
2624 of 3970: Niobrara Electric Assn, Inc has 2625 rates
2625 of 3970: Niobrara Electric Assn, Inc (Nebraska) has 2626 rates
2626 of 3970: Niobrara Electric Assn, Inc (South Dakota) has 2627 rates
2627 of 3970: Niobrara Valley El Member Corp has 2628 rates
2628 of 3970: Nishnabotna Valley R E C has 2629 rates
2629 of 3970: Nissequoque Cogen Partners has 2630 rates
2630 of 3970: Noble Americas Energy Solutions LLC has 2631 rates
2631 of 3970: Noble Americas Energy Solutions LLC (Connecticut) has 2632 rates
2632 of 3970: Noble Americas Energy Solutions LLC (Delaware) has 2633 rates
2633 of 3970: Noble Americas Energy Solutions LLC (District of Columbia) has 2634 rates
2634 of 3970: Noble Americas Energy Solutions LLC (Illinois) has 2635 rates
2635 of 3970: Noble Americas Energy Solutions LLC (Maine) has 2636 rates
2636 of 3970: Noble Americas Energy Solutions LLC (Maryland) has 2637 rates
2637 of 3970: Noble Americas Energy Solutions LLC (Massachusetts) has 2638 rates
2638 of 3970: Noble Americas Energy Solutions LLC (Michigan) has 2639 rates
2639 of 3970: Noble Americas Energy Solutions LLC (New Jersey) has 2640 rates
2640 of 3970: Noble Americas Energy Solutions LLC (New York) has 2641 rates
2641 of 3970: Noble Americas Energy Solutions LLC (Ohio) has 2642 rates
2642 of 3970: Noble Americas Energy Solutions LLC (Oregon) has 2643 rates
2643 of 3970: Noble Americas Energy Solutions LLC (Pennsylvania) has 2644 rates
2644 of 3970: Noble Americas Energy Solutions LLC (Rhode Island) has 2645 rates
2645 of 3970: Noble Americas Energy Solutions LLC (Texas) has 2646 rates
2646 of 3970: Noble County R E M C has 2647 rates
2647 of 3970: Nobles Cooperative Electric has 2648 rates
2648 of 3970: Nobles Cooperative Electric (Iowa) has 2649 rates
2649 of 3970: NOCO Electric has 2650 rates
2650 of 3970: Nodak Electric Coop Inc has 2651 rates
2651 of 3970: Nolin Rural Electric Coop Corp has 2652 rates
2652 of 3970: Nome Joint Utility Systems has 2653 rates
2653 of 3970: Norris Electric Coop has 2654 rates
2654 of 3970: Norris Public Power District has 2655 rates
2655 of 3970: North Alabama Electric Coop has 2656 rates
2656 of 3970: North Arkansas Elec Coop, Inc has 2657 rates
2657 of 3970: North Branch Water & Light Comm has 2658 rates
2658 of 3970: North Carolina Eastern M P A has 2659 rates
2659 of 3970: North Carolina El Member Corp has 2660 rates
2660 of 3970: North Carolina Mun Power Agny has 2661 rates
2661 of 3970: North Central Elec Coop, Inc has 2662 rates
2662 of 3970: North Central Elec Coop, Inc (North Dakota) has 2663 rates
2663 of 3970: North Central MO Elec Coop Inc has 2664 rates
2664 of 3970: North Central Power Co Inc has 2665 rates
2665 of 3970: North Central Public Pwr Dist has 2666 rates
2666 of 3970: North East Mississippi E P A has 2667 rates
2667 of 3970: North Georgia Elec Member Corp has 2668 rates
2668 of 3970: North Georgia EMC has 2669 rates
2669 of 3970: North Itasca Electric Coop Inc has 2670 rates
2670 of 3970: North Plains Electric Coop Inc has 2671 rates
2671 of 3970: North Slope Borough Power & Light has 2672 rates
2672 of 3970: North Star Electric Coop, Inc has 2673 rates
2673 of 3970: North West Rural Electric Coop has 2674 rates
2674 of 3970: North Western Elec Coop, Inc has 2675 rates
2675 of 3970: Northcentral Mississippi E P A has 2676 rates
2676 of 3970: Northeast Louisiana Power Coop Inc. has 2677 rates
2677 of 3970: Northeast Missouri El Pwr Coop has 2678 rates
2678 of 3970: Northeast Nebraska P P D has 2679 rates
2679 of 3970: Northeast Oklahoma Electric Coop, Inc has 2680 rates
2680 of 3970: Northeast Texas Elec Coop, Inc has 2681 rates
2681 of 3970: Northeastern Rural E M C has 2682 rates
2682 of 3970: Northern California Power Agny has 2683 rates
2683 of 3970: Northern Electric Coop, Inc has 2684 rates
2684 of 3970: Northern Indiana Pub Serv Co has 2685 rates
2685 of 3970: Northern Lights, Inc has 2686 rates
2686 of 3970: Northern Lights, Inc (Montana) has 2687 rates
2687 of 3970: Northern Lights, Inc (Washington) has 2688 rates
2688 of 3970: Northern Municipal Power Agency has 2689 rates
2689 of 3970: Northern Neck Elec Coop, Inc has 2690 rates
2690 of 3970: Northern Plains Electric Coop has 2691 rates
2691 of 3970: Northern Rio Arriba E Coop Inc has 2692 rates
2692 of 3970: Northern States Power Co (Michigan) has 2693 rates
2693 of 3970: Northern States Power Co - Minnesota has 2694 rates
2694 of 3970: Northern States Power Co - Minnesota (North Dakota) has 2695 rates
2695 of 3970: Northern States Power Co - Minnesota (South Dakota) has 2696 rates
2696 of 3970: Northern States Power Co - Wisconsin has 2697 rates
2697 of 3970: Northern States Power Co - Wisconsin (Michigan) has 2698 rates
2698 of 3970: Northern Virginia Elec Coop has 2699 rates
2699 of 3970: Northern Wasco County PUD has 2700 rates
2700 of 3970: Northfork Electric Coop, Inc has 2701 rates
2701 of 3970: Northwest Iowa Power Coop has 2702 rates
2702 of 3970: Northwest Rural Pub Pwr Dist has 2703 rates
2703 of 3970: NorthWestern Corporation has 2704 rates
2704 of 3970: Northwestern Electric Coop Inc has 2705 rates
2705 of 3970: NorthWestern Energy has 2706 rates
2706 of 3970: Northwestern Rural E C A, Inc has 2707 rates
2707 of 3970: Northwestern Wisconsin Elec Co has 2708 rates
2708 of 3970: NorVal Electric Cooperative, Inc has 2709 rates
2709 of 3970: Norwalk Third Taxing District has 2710 rates
2710 of 3970: NOVEC has 2711 rates
2711 of 3970: NRG Power Marketing LLC has 2712 rates
2712 of 3970: NSTAR Electric Company has 2713 rates
2713 of 3970: Nueces Electric Coop, Inc has 2714 rates
2714 of 3970: Nushagak Electric Coop, Inc has 2715 rates
2715 of 3970: NV Energy has 2716 rates
2716 of 3970: NYSEG Solutions Inc has 2717 rates
2717 of 3970: Oahe Electric Coop Inc has 2718 rates
2718 of 3970: Oakdale Electric Coop has 2719 rates
2719 of 3970: Oakdale&South San Joaquin Irrigation D. has 2720 rates
2720 of 3970: Ocmulgee Electric Member Corp has 2721 rates
2721 of 3970: Oconee Electric Member Corp has 2722 rates
2722 of 3970: Oconomowoc Utilities has 2723 rates
2723 of 3970: Oconto Electric Cooperative has 2724 rates
2724 of 3970: Oconto Falls Water & Light Comm has 2725 rates
2725 of 3970: Ocotillo Water Conserv. Dist. has 2726 rates
2726 of 3970: OG&E has 2727 rates
2727 of 3970: OGE Energy Resources, Inc has 2728 rates
2728 of 3970: Oglethorpe Power Corporation has 2729 rates
2729 of 3970: Ohio Edison Co has 2730 rates
2730 of 3970: Ohio Power Co has 2731 rates
2731 of 3970: Ohio Valley Electric Corp has 2732 rates
2732 of 3970: Ohop Mutual Light Company, Inc has 2733 rates
2733 of 3970: Okanogan County Elec Coop, Inc has 2734 rates
2734 of 3970: Okeene Public Works Authority has 2735 rates
2735 of 3970: Okefenoke Rural El Member Corp has 2736 rates
2736 of 3970: Okefenoke Rural El Member Corp (Florida) has 2737 rates
2737 of 3970: Oklahoma Electric Coop Inc has 2738 rates
2738 of 3970: Oklahoma Gas & Electric Co has 2739 rates
2739 of 3970: Oklahoma Gas & Electric Co (Arkansas) has 2740 rates
2740 of 3970: Oklahoma Municipal Power Auth has 2741 rates
2741 of 3970: Old Dominion Electric Coop has 2742 rates
2742 of 3970: Old Dominion Power Co has 2743 rates
2743 of 3970: Oliver-Mercer Elec Coop Inc has 2744 rates
2744 of 3970: Olmsted County Public Works has 2745 rates
2745 of 3970: OLS Energy-Camarillo has 2746 rates
2746 of 3970: OLS Energy-Chino has 2747 rates
2747 of 3970: Omaha Public Power District has 2748 rates
2748 of 3970: Omya Inc has 2749 rates
2749 of 3970: Oncor Electric Delivery Company LLC has 2750 rates
2750 of 3970: Oneida-Madison Elec Coop, Inc has 2751 rates
2751 of 3970: OnPAC Energy has 2752 rates
2752 of 3970: Ontonagon County R E A has 2753 rates
2753 of 3970: OPPD has 2754 rates
2754 of 3970: Optim Energy Marketing LLC has 2755 rates
2755 of 3970: Orange & Rockland has 2756 rates
2756 of 3970: Orange & Rockland Utils Inc has 2757 rates
2757 of 3970: Orange County Rural E M C has 2758 rates
2758 of 3970: Orcas Power & Light Coop has 2759 rates
2759 of 3970: Oregon Trail El Cons Coop, Inc has 2760 rates
2760 of 3970: Orlando Utilities Comm has 2761 rates
2761 of 3970: Osage Valley Elec Coop Assn has 2762 rates
2762 of 3970: Osceola Electric Coop, Inc has 2763 rates
2763 of 3970: Otero County Electric Coop Inc has 2764 rates
2764 of 3970: Otsego Electric Coop, Inc has 2765 rates
2765 of 3970: Otter Tail Power Co has 2766 rates
2766 of 3970: Otter Tail Power Co (North Dakota) has 2767 rates
2767 of 3970: Otter Tail Power Co (South Dakota) has 2768 rates
2768 of 3970: Ouachita Electric Coop Corp has 2769 rates
2769 of 3970: OUC has 2770 rates
2770 of 3970: Our Energy LLC has 2771 rates
2771 of 3970: Overton Power District No 5 has 2772 rates
2772 of 3970: Owen Electric Coop Inc has 2773 rates
2773 of 3970: Ozark Border Electric Coop has 2774 rates
2774 of 3970: Ozark Electric Coop Inc has 2775 rates
2775 of 3970: Ozarks Electric Coop Corp has 2776 rates
2776 of 3970: P K M Electric Coop, Inc has 2777 rates
2777 of 3970: Pacific Gas & Electric Co has 2778 rates
2778 of 3970: Pacific Northwest Generating Coop has 2779 rates
2779 of 3970: Pacific Power (California) has 2780 rates
2780 of 3970: Pacific Power (Oregon) has 2781 rates
2781 of 3970: Pacific Power (Washington) has 2782 rates
2782 of 3970: PacifiCorp has 2783 rates
2783 of 3970: PacifiCorp (Idaho) has 2784 rates
2784 of 3970: PacifiCorp (Oregon) has 2785 rates
2785 of 3970: PacifiCorp (Utah) has 2786 rates
2786 of 3970: PacifiCorp (Washington) has 2787 rates
2787 of 3970: PacifiCorp (Wyoming) has 2788 rates
2788 of 3970: Page Electric Utility has 2789 rates
2789 of 3970: Palmco Power NJ, LLC has 2790 rates
2790 of 3970: Palmco Power NJ, LLC (New Jersey) has 2791 rates
2791 of 3970: Palmco Power PA, LLC has 2792 rates
2792 of 3970: Palmco Power PA, LLC (Pennsylvania) has 2793 rates
2793 of 3970: Palmetto Electric Coop Inc has 2794 rates
2794 of 3970: Panhandle Rural El Member Assn has 2795 rates
2795 of 3970: Panola-Harrison Elec Coop, Inc has 2796 rates
2796 of 3970: Panola-Harrison Elec Coop, Inc (Louisiana) has 2797 rates
2797 of 3970: Paragould Light & Water Comm has 2798 rates
2798 of 3970: Park Electric Coop Inc has 2799 rates
2799 of 3970: Parke County Rural E M C has 2800 rates
2800 of 3970: Parkland Light & Water Company has 2801 rates
2801 of 3970: Parowan City Corporation (Utility Company) has 2802 rates
2802 of 3970: Pasadena Cogneration LP has 2803 rates
2803 of 3970: Pascoag Utility District has 2804 rates
2804 of 3970: Pataula Electric Member Corp has 2805 rates
2805 of 3970: Paulding-Putman Elec Coop, Inc has 2806 rates
2806 of 3970: Paulding-Putman Elec Coop, Inc (Indiana) has 2807 rates
2807 of 3970: Payson City Corporation (Utility Company) has 2808 rates
2808 of 3970: Pea River Electric Coop has 2809 rates
2809 of 3970: Peace River Electric Coop, Inc has 2810 rates
2810 of 3970: Pearl River Valley El Pwr Assn has 2811 rates
2811 of 3970: PEC has 2812 rates
2812 of 3970: PECO has 2813 rates
2813 of 3970: PECO Energy Co has 2814 rates
2814 of 3970: Pedernales Electric Coop, Inc has 2815 rates
2815 of 3970: Pedro Bay Village Council (Utility Company) has 2816 rates
2816 of 3970: Pee Dee Electric Coop, Inc has 2817 rates
2817 of 3970: Pee Dee Electric Member Corp has 2818 rates
2818 of 3970: Pelican Utility has 2819 rates
2819 of 3970: Pella Cooperative Elec Assn has 2820 rates
2820 of 3970: Pemiscot-Dunklin Elec Coop Inc has 2821 rates
2821 of 3970: Peninsula Clean Energy has 2822 rates
2822 of 3970: Peninsula Light Company has 2823 rates
2823 of 3970: Pennsylvania Electric Co has 2824 rates
2824 of 3970: Pennsylvania Electric Co (New York) has 2825 rates
2825 of 3970: Pennsylvania Electric Co (Pennsylvania) has 2826 rates
2826 of 3970: Pennsylvania Power & Light has 2827 rates
2827 of 3970: Pennsylvania Power Co (Pennsylvania) has 2828 rates
2828 of 3970: Pennyrile Rural Electric Coop has 2829 rates
2829 of 3970: Penoyer Valley Electric Coop has 2830 rates
2830 of 3970: Penstar Power has 2831 rates
2831 of 3970: People's Cooperative Services has 2832 rates
2832 of 3970: People's Electric Cooperative has 2833 rates
2833 of 3970: People's Electric Corporation has 2834 rates
2834 of 3970: PEPCO (DC) has 2835 rates
2835 of 3970: PEPCO Energy Services has 2836 rates
2836 of 3970: PEPCO Energy Services (Connecticut) has 2837 rates
2837 of 3970: PEPCO Energy Services (Delaware) has 2838 rates
2838 of 3970: PEPCO Energy Services (District of Columbia) has 2839 rates
2839 of 3970: PEPCO Energy Services (Illinois) has 2840 rates
2840 of 3970: PEPCO Energy Services (Maryland) has 2841 rates
2841 of 3970: PEPCO Energy Services (Massachusetts) has 2842 rates
2842 of 3970: PEPCO Energy Services (New Jersey) has 2843 rates
2843 of 3970: PEPCO Energy Services (New York) has 2844 rates
2844 of 3970: PEPCO Energy Services (Pennsylvania) has 2845 rates
2845 of 3970: PEPCO Energy Services (Texas) has 2846 rates
2846 of 3970: PEPCO of Maryland has 2847 rates
2847 of 3970: Perennial Public Power Dist has 2848 rates
2848 of 3970: Petit Jean Electric Coop Corp has 2849 rates
2849 of 3970: PG&E has 2850 rates
2850 of 3970: PGE has 2851 rates
2851 of 3970: Philippi Municipal Electric has 2852 rates
2852 of 3970: Pickwick Electric Coop has 2853 rates
2853 of 3970: Piedmont Electric Member Corp has 2854 rates
2854 of 3970: Piedmont Municipal Power Agny has 2855 rates
2855 of 3970: Pierce-Pepin Coop Services has 2856 rates
2856 of 3970: Pike County Light & Power Co has 2857 rates
2857 of 3970: Pike County Light & Power Co (Pennsylvania) has 2858 rates
2858 of 3970: Pilot Power Group Inc has 2859 rates
2859 of 3970: Pioneer Community Energy has 2860 rates
2860 of 3970: Pioneer Electric Coop, Inc has 2861 rates
2861 of 3970: Pioneer Electric Coop, Inc (Alabama) has 2862 rates
2862 of 3970: Pioneer Power and Light Co has 2863 rates
2863 of 3970: Pioneer Rural Elec Coop, Inc has 2864 rates
2864 of 3970: Pitt & Greene Elec Member Corp has 2865 rates
2865 of 3970: Placer County Water Agency has 2866 rates
2866 of 3970: Planters Electric Member Corp has 2867 rates
2867 of 3970: Plateau Electric Cooperative has 2868 rates
2868 of 3970: Platte River Power Authority has 2869 rates
2869 of 3970: Platte-Clay Electric Coop, Inc has 2870 rates
2870 of 3970: Plumas-Sierra Rural Elec Coop has 2871 rates
2871 of 3970: Plymouth Cogeneration LP has 2872 rates
2872 of 3970: PNM has 2873 rates
2873 of 3970: Pointe Coupee Elec Member Corp has 2874 rates
2874 of 3970: Polk County Rural Pub Pwr Dist has 2875 rates
2875 of 3970: Polk-Burnett Electric Coop has 2876 rates
2876 of 3970: Pontotoc Electric Power Assn has 2877 rates
2877 of 3970: Portland General Electric Co has 2878 rates
2878 of 3970: Portside Energy Corp has 2879 rates
2879 of 3970: Potentia Energy, LLC has 2880 rates
2880 of 3970: Potomac Electric Power Co has 2881 rates
2881 of 3970: Potomac Electric Power Co (Maryland) has 2882 rates
2882 of 3970: Poudre Valley R E A, Inc has 2883 rates
2883 of 3970: Powder River Energy Corporation has 2884 rates
2884 of 3970: Powder River Energy Corporation (Montana) has 2885 rates
2885 of 3970: Powell Valley Electric Coop has 2886 rates
2886 of 3970: Power Choice/Pepco Energy Serv has 2887 rates
2887 of 3970: Power Resources Cooperative has 2888 rates
2888 of 3970: Powerex Corporation has 2889 rates
2889 of 3970: PowerSouth Energy Cooperative has 2890 rates
2890 of 3970: PPL has 2891 rates
2891 of 3970: PPL Electric Utilities Corp has 2892 rates
2892 of 3970: PPL EnergyPlus has 2893 rates
2893 of 3970: PPL EnergyPlus LLC has 2894 rates
2894 of 3970: PPL EnergyPlus LLC (Montana) has 2895 rates
2895 of 3970: PPM Energy Inc has 2896 rates
2896 of 3970: Prague Public Works Authority has 2897 rates
2897 of 3970: Prairie Energy Coop has 2898 rates
2898 of 3970: Prairie Land Electric Coop Inc has 2899 rates
2899 of 3970: Prairie Power, Inc has 2900 rates
2900 of 3970: Precinct of Woodsville has 2901 rates
2901 of 3970: Prentiss County Elec Pwr Assn has 2902 rates
2902 of 3970: Presque Isle Elec & Gas Coop has 2903 rates
2903 of 3970: Preston Public Utilities Comm has 2904 rates
2904 of 3970: Price Electric Coop Inc has 2905 rates
2905 of 3970: Price Municipal Corporation has 2906 rates
2906 of 3970: Prince George Electric Coop has 2907 rates
2907 of 3970: Princeton Public Utils Comm has 2908 rates
2908 of 3970: Proctor Public Utilities Comm has 2909 rates
2909 of 3970: Progress Energy Carolinas Inc has 2910 rates
2910 of 3970: Progress Energy Carolinas Inc (South Carolina) has 2911 rates
2911 of 3970: Progress Energy Florida Inc has 2912 rates
2912 of 3970: Prospect Corporation has 2913 rates
2913 of 3970: Provo City Corp (Utility Company) has 2914 rates
2914 of 3970: PSEG has 2915 rates
2915 of 3970: PSEG Energy Resources and Trade has 2916 rates
2916 of 3970: PSNH has 2917 rates
2917 of 3970: PSO has 2918 rates
2918 of 3970: Public Power & Utility, Inc. has 2919 rates
2919 of 3970: Public Power & Utility, Inc. (Massachusetts) has 2920 rates
2920 of 3970: Public Power & Utility, Inc. (New Jersey) has 2921 rates
2921 of 3970: Public Power & Utility, Inc. (New York) has 2922 rates
2922 of 3970: Public Power & Utility, Inc. (Pennsylvania) has 2923 rates
2923 of 3970: Public Serv Comm of Yazoo City has 2924 rates
2924 of 3970: Public Service Co of Colorado has 2925 rates
2925 of 3970: Public Service Co of NH has 2926 rates
2926 of 3970: Public Service Co of NM has 2927 rates
2927 of 3970: Public Service Co of Oklahoma has 2928 rates
2928 of 3970: Public Service Elec & Gas Co has 2929 rates
2929 of 3970: Public Utility District No 1 has 2930 rates
2930 of 3970: Public Utility District No 2 has 2931 rates
2931 of 3970: PUD No 1 of Asotin County has 2932 rates
2932 of 3970: PUD No 1 of Benton County has 2933 rates
2933 of 3970: PUD No 1 of Chelan County has 2934 rates
2934 of 3970: PUD No 1 of Clallam County has 2935 rates
2935 of 3970: PUD No 1 of Clark County has 2936 rates
2936 of 3970: PUD No 1 of Cowlitz County has 2937 rates
2937 of 3970: PUD No 1 of Douglas County has 2938 rates
2938 of 3970: PUD No 1 of Ferry County has 2939 rates
2939 of 3970: PUD No 1 of Franklin County has 2940 rates
2940 of 3970: PUD No 1 of Grays Harbor Cnty has 2941 rates
2941 of 3970: PUD No 1 of Kittitas County has 2942 rates
2942 of 3970: PUD No 1 of Klickitat County has 2943 rates
2943 of 3970: PUD No 1 of Lewis County has 2944 rates
2944 of 3970: PUD No 1 of Mason County has 2945 rates
2945 of 3970: PUD No 1 of Okanogan County has 2946 rates
2946 of 3970: PUD No 1 of Pend Oreille Cnty has 2947 rates
2947 of 3970: PUD No 1 of Skamania Co has 2948 rates
2948 of 3970: PUD No 1 of Whatcom County has 2949 rates
2949 of 3970: PUD No 2 of Grant County has 2950 rates
2950 of 3970: PUD No 3 of Mason County has 2951 rates
2951 of 3970: Puerto Rico Electric Pwr Authority has 2952 rates
2952 of 3970: Puget Sound Energy Inc has 2953 rates
2953 of 3970: Radiant Electric Coop, Inc has 2954 rates
2954 of 3970: Raft River Rural Elec Coop Inc has 2955 rates
2955 of 3970: Rainbow Energy Marketing Corp has 2956 rates
2956 of 3970: Ralls County Electric Coop has 2957 rates
2957 of 3970: Rancho Cucamonga Municipal Utility has 2958 rates
2958 of 3970: Randolph Electric Member Corp has 2959 rates
2959 of 3970: Rappahannock Electric Coop has 2960 rates
2960 of 3970: Raton Public Service Company has 2961 rates
2961 of 3970: Ravalli County Elec Coop, Inc has 2962 rates
2962 of 3970: Rayburn Country Elec Coop, Inc has 2963 rates
2963 of 3970: Rayle Electric Membership Corp has 2964 rates
2964 of 3970: REA Energy Coop Inc has 2965 rates
2965 of 3970: Reach Energy, LLC has 2966 rates
2966 of 3970: REC has 2967 rates
2967 of 3970: Red Lake Electric Coop, Inc has 2968 rates
2968 of 3970: Red River Valley Coop Pwr Assn has 2969 rates
2969 of 3970: Red River Valley Rrl Elec Assn has 2970 rates
2970 of 3970: Redlands Water & Power Company has 2971 rates
2971 of 3970: Redwood Coast Energy Authority has 2972 rates
2972 of 3970: Redwood Electric Coop has 2973 rates
2973 of 3970: Redwood Falls Public Util Comm has 2974 rates
2974 of 3970: Reedsburg Utility Comm has 2975 rates
2975 of 3970: Reedy Creek Improvement Dist has 2976 rates
2976 of 3970: Reliable Power, LLC has 2977 rates
2977 of 3970: Reliable Power, LLC (Massachusetts) has 2978 rates
2978 of 3970: Reliant Energy Power Supply LLC has 2979 rates
2979 of 3970: Reliant Energy Retail Services LLC has 2980 rates
2980 of 3970: Renville-Sibley Coop Pwr Assn has 2981 rates
2981 of 3970: RGE has 2982 rates
2982 of 3970: Rice Lake Utilities has 2983 rates
2983 of 3970: Riceland Foods Inc. has 2984 rates
2984 of 3970: Rich Mountain Elec Coop, Inc has 2985 rates
2985 of 3970: Rich Mountain Elec Coop, Inc (Oklahoma) has 2986 rates
2986 of 3970: Richland Electric Coop has 2987 rates
2987 of 3970: Rio Grande Electric Coop, Inc has 2988 rates
2988 of 3970: Rio Grande Electric Coop, Inc (New Mexico) has 2989 rates
2989 of 3970: Rita Blanca Electric Coop, Inc has 2990 rates
2990 of 3970: Riverland Energy Cooperative has 2991 rates
2991 of 3970: Riverside Electric Cooperative has 2992 rates
2992 of 3970: Roanoke Electric Member Corp has 2993 rates
2993 of 3970: Robison Energy, LLC has 2994 rates
2994 of 3970: Rochelle Municipal Utilities has 2995 rates
2995 of 3970: Rochester Gas & Electric Corp has 2996 rates
2996 of 3970: Rochester Public Utilities has 2997 rates
2997 of 3970: Rock Energy Cooperative has 2998 rates
2998 of 3970: Rock Energy Cooperative (Illinois) has 2999 rates
2999 of 3970: Rock Rapids Municipal Utility has 3000 rates
3000 of 3970: Rockland Electric Co has 3001 rates
3001 of 3970: Rockland Electric Co (New Jersey) has 3002 rates
3002 of 3970: Rocky Mountain Power (Idaho) has 3003 rates
3003 of 3970: Rocky Mountain Power (Utah) has 3004 rates
3004 of 3970: Rocky Mountain Power (Wyoming) has 3005 rates
3005 of 3970: Rolling Hills Electric Coop has 3006 rates
3006 of 3970: Roosevelt County Elec Coop Inc has 3007 rates
3007 of 3970: Roosevelt Irrigation District has 3008 rates
3008 of 3970: Roosevelt Public Power Dist has 3009 rates
3009 of 3970: Roseau Electric Coop, Inc has 3010 rates
3010 of 3970: Rosebud Electric Coop Inc has 3011 rates
3011 of 3970: Roughrider Electric Cooperative has 3012 rates
3012 of 3970: RRI Energy Services, Inc. has 3013 rates
3013 of 3970: Runestone Electric Assn has 3014 rates
3014 of 3970: Rural Electric Conven Coop has 3015 rates
3015 of 3970: Rural Electric Coop, Inc has 3016 rates
3016 of 3970: Rushmore Electric Pwr Coop Inc has 3017 rates
3017 of 3970: RushShelby Energy has 3018 rates
3018 of 3970: Rusk County Electric Coop, Inc has 3019 rates
3019 of 3970: Rutherford Elec Member Corp has 3020 rates
3020 of 3970: RV CSU Power II LLC has 3021 rates
3021 of 3970: Sabine Cogen LP has 3022 rates
3022 of 3970: Sac-Osage Electric Coop Inc has 3023 rates
3023 of 3970: Sacramento Municipal Utility District has 3024 rates
3024 of 3970: Safe Harbor Water Power Corp has 3025 rates
3025 of 3970: Salem City Corporation (Utility Company) has 3026 rates
3026 of 3970: Salem Electric has 3027 rates
3027 of 3970: Salmon River Electric Coop Inc has 3028 rates
3028 of 3970: Salt River Electric Coop Corp has 3029 rates
3029 of 3970: Salt River Project has 3030 rates
3030 of 3970: Sam Houston Electric Coop Inc has 3031 rates
3031 of 3970: Sam Rayburn G&T Elec Coop Inc has 3032 rates
3032 of 3970: Sam Rayburn Municipal Pwr Agny has 3033 rates
3033 of 3970: San Bernard Electric Coop, Inc has 3034 rates
3034 of 3970: San Diego Gas & Electric Co has 3035 rates
3035 of 3970: San Isabel Electric Assn, Inc has 3036 rates
3036 of 3970: San Jose Clean Energy has 3037 rates
3037 of 3970: San Luis Valley R E C, Inc has 3038 rates
3038 of 3970: San Miguel Electric Coop, Inc has 3039 rates
3039 of 3970: San Miguel Power Assn, Inc has 3040 rates
3040 of 3970: San Patricio Electric Coop Inc has 3041 rates
3041 of 3970: Sand Mountain Electric Coop has 3042 rates
3042 of 3970: Sangre De Cristo Elec Assn Inc has 3043 rates
3043 of 3970: Santee Electric Coop, Inc has 3044 rates
3044 of 3970: Satilla Rural Elec Member Corporation has 3045 rates
3045 of 3970: Sawnee Electric Membership Corporation has 3046 rates
3046 of 3970: Sawnee EMC has 3047 rates
3047 of 3970: SCE has 3048 rates
3048 of 3970: Scenic Rivers Energy Coop has 3049 rates
3049 of 3970: SDG&E has 3050 rates
3050 of 3970: SE-MA-NO Electric Coop has 3051 rates
3051 of 3970: Seattle City Light has 3052 rates
3052 of 3970: Seattle City of (Washington) has 3053 rates
3053 of 3970: SECO Energy has 3054 rates
3054 of 3970: Sedgwick Cnty El Coop Assn Inc has 3055 rates
3055 of 3970: Seminole Electric Cooperative Inc has 3056 rates
3056 of 3970: SEMO Electric Cooperative has 3057 rates
3057 of 3970: Sempra Energy Trading Corp has 3058 rates
3058 of 3970: Sempra Energy Trading Corp (Washington) has 3059 rates
3059 of 3970: Sempra Generation has 3060 rates
3060 of 3970: Sequachee Valley Electric Coop has 3061 rates
3061 of 3970: Sevier County Electric System has 3062 rates
3062 of 3970: Seville Board of Public Affairs has 3063 rates
3063 of 3970: Seward County Rrl Pub Pwr Dist has 3064 rates
3064 of 3970: Shakopee Public Utilities Comm has 3065 rates
3065 of 3970: Sharyland Utilities LP has 3066 rates
3066 of 3970: Shawano Municipal Utilities has 3067 rates
3067 of 3970: Sheffield Utilities has 3068 rates
3068 of 3970: Shelby Electric Coop, Inc has 3069 rates
3069 of 3970: Shelby Energy Co-op, Inc has 3070 rates
3070 of 3970: Shenandoah Valley Elec Coop has 3071 rates
3071 of 3970: Sheridan Electric Coop, Inc has 3072 rates
3072 of 3970: Sheridan Electric Coop, Inc (North Dakota) has 3073 rates
3073 of 3970: Sho-Me Power Electric Coop has 3074 rates
3074 of 3970: Sierra Electric Coop, Inc has 3075 rates
3075 of 3970: Sierra Pacific Industries Inc has 3076 rates
3076 of 3970: Sierra Pacific Power Co has 3077 rates
3077 of 3970: Sierra Pacific Power Co (Nevada) has 3078 rates
3078 of 3970: Sierra Power Corp has 3079 rates
3079 of 3970: Silicon Valley Clean Energy has 3080 rates
3080 of 3970: Silicon Valley Power has 3081 rates
3081 of 3970: Simple Power, LP has 3082 rates
3082 of 3970: Singing River Elec Pwr Assn (Mississippi) has 3083 rates
3083 of 3970: Sioux Valley Energy has 3084 rates
3084 of 3970: Sioux Valley Energy (South Dakota) has 3085 rates
3085 of 3970: Sioux Valley SW Elec Coop has 3086 rates
3086 of 3970: Slash Pine Elec Member Corp has 3087 rates
3087 of 3970: Sleepy Eye Public Utility Comm has 3088 rates
3088 of 3970: Slinger Utilities has 3089 rates
3089 of 3970: Slope Electric Coop Inc has 3090 rates
3090 of 3970: Smarr EMC has 3091 rates
3091 of 3970: Smart Prepaid Electric has 3092 rates
3092 of 3970: SMECO has 3093 rates
3093 of 3970: SMUD has 3094 rates
3094 of 3970: Snapping Shoals El Member Corp has 3095 rates
3095 of 3970: Snohomish County PUD No 1 has 3096 rates
3096 of 3970: Socorro Electric Coop, Inc has 3097 rates
3097 of 3970: Solar Star NAFB LLC has 3098 rates
3098 of 3970: Somerset Rural Elec Coop, Inc has 3099 rates
3099 of 3970: Sonoma Clean Power has 3100 rates
3100 of 3970: South Alabama Elec Coop, Inc has 3101 rates
3101 of 3970: South Carolina Electric&Gas Co has 3102 rates
3102 of 3970: South Carolina Genertg Co, Inc has 3103 rates
3103 of 3970: South Carolina Pub Serv Auth has 3104 rates
3104 of 3970: South Central Ark El Coop, Inc has 3105 rates
3105 of 3970: South Central Electric Assn has 3106 rates
3106 of 3970: South Central Indiana REMC has 3107 rates
3107 of 3970: South Central Power Company has 3108 rates
3108 of 3970: South Central Public Pwr Dist has 3109 rates
3109 of 3970: South Feather Water and Power Agency has 3110 rates
3110 of 3970: South Jersey Energy Company has 3111 rates
3111 of 3970: South Jersey Energy Company (Connecticut) has 3112 rates
3112 of 3970: South Jersey Energy Company (Maine) has 3113 rates
3113 of 3970: South Jersey Energy Company (Massachusetts) has 3114 rates
3114 of 3970: South Jersey Energy Company (New Hampshire) has 3115 rates
3115 of 3970: South Jersey Energy Company (Pennsylvania) has 3116 rates
3116 of 3970: South Jersey Energy Company (Rhode Island) has 3117 rates
3117 of 3970: South Kentucky Rural Electric Coop Corp has 3118 rates
3118 of 3970: South Kentucky Rural Electric Coop Corp (Tennessee) has 3119 rates
3119 of 3970: South Louisiana Elec Coop Assn has 3120 rates
3120 of 3970: South Mississippi El Pwr Assn has 3121 rates
3121 of 3970: South Plains Electric Coop Inc has 3122 rates
3122 of 3970: South River Elec Member Corp has 3123 rates
3123 of 3970: South Side Electric, Inc has 3124 rates
3124 of 3970: South Texas Electric Coop, Inc has 3125 rates
3125 of 3970: South Utah Valley Electric Service District has 3126 rates
3126 of 3970: South Vienna Corporation has 3127 rates
3127 of 3970: Southeast Colorado Power Assn has 3128 rates
3128 of 3970: Southeast Electric Coop, Inc has 3129 rates
3129 of 3970: Southeast Electric Coop, Inc (South Dakota) has 3130 rates
3130 of 3970: Southeast Electric Coop, Inc (Wyoming) has 3131 rates
3131 of 3970: Southeastern Electric Coop Inc has 3132 rates
3132 of 3970: Southeastern Electric Coop Inc (South Dakota) has 3133 rates
3133 of 3970: Southeastern IL Elec Coop, Inc has 3134 rates
3134 of 3970: Southeastern Indiana R E M C has 3135 rates
3135 of 3970: Southeastern Power Admin has 3136 rates
3136 of 3970: Southern California Edison Co has 3137 rates
3137 of 3970: Southern California P P A has 3138 rates
3138 of 3970: Southern Electric Gen Co has 3139 rates
3139 of 3970: Southern Illinois Elec Coop has 3140 rates
3140 of 3970: Southern Illinois Power Coop has 3141 rates
3141 of 3970: Southern Indiana Gas & Elec Co has 3142 rates
3142 of 3970: Southern Indiana R E C, Inc has 3143 rates
3143 of 3970: Southern Iowa Elec Coop, Inc has 3144 rates
3144 of 3970: Southern Maryland Elec Coop Inc has 3145 rates
3145 of 3970: Southern Minnesota Mun P Agny has 3146 rates
3146 of 3970: Southern Pine Elec Coop, Inc has 3147 rates
3147 of 3970: Southern Pine Elec Power Assn has 3148 rates
3148 of 3970: Southern Public Power District has 3149 rates
3149 of 3970: Southern Rivers Energy has 3150 rates
3150 of 3970: Southside Electric Coop, Inc has 3151 rates
3151 of 3970: Southwest Arkansas E C C has 3152 rates
3152 of 3970: Southwest Arkansas E C C (Arkansas) has 3153 rates
3153 of 3970: Southwest Electric Coop, Inc has 3154 rates
3154 of 3970: Southwest Iowa Rural Elec Coop has 3155 rates
3155 of 3970: Southwest Louisiana E M C has 3156 rates
3156 of 3970: Southwest Mississippi E P A has 3157 rates
3157 of 3970: Southwest Public Power Dist has 3158 rates
3158 of 3970: Southwest Rural Elec Assn Inc has 3159 rates
3159 of 3970: Southwest Rural Elec Assn Inc (Texas) has 3160 rates
3160 of 3970: Southwest Tennessee E M C has 3161 rates
3161 of 3970: Southwest Texas Elec Coop, Inc has 3162 rates
3162 of 3970: Southwestern Electric Coop Inc has 3163 rates
3163 of 3970: Southwestern Electric Coop Inc (Colorado) has 3164 rates
3164 of 3970: Southwestern Electric Coop Inc (New Mexico) has 3165 rates
3165 of 3970: Southwestern Electric Coop Inc (Oklahoma) has 3166 rates
3166 of 3970: Southwestern Electric Coop Inc (Texas) has 3167 rates
3167 of 3970: Southwestern Electric Power Co has 3168 rates
3168 of 3970: Southwestern Electric Power Co (Arkansas) has 3169 rates
3169 of 3970: Southwestern Electric Power Co (Louisiana) has 3170 rates
3170 of 3970: Southwestern Electric Power Co (Texas) has 3171 rates
3171 of 3970: Southwestern Power Admin has 3172 rates
3172 of 3970: Southwestern Public Service Co has 3173 rates
3173 of 3970: Southwestern Public Service Co (Texas) has 3174 rates
3174 of 3970: Spanish Fork City Corporation (Utility Company) has 3175 rates
3175 of 3970: Spark Energy has 3176 rates
3176 of 3970: Spark Energy, LP has 3177 rates
3177 of 3970: Spark Energy, LP (Connecticut) has 3178 rates
3178 of 3970: Spark Energy, LP (Maryland) has 3179 rates
3179 of 3970: Spark Energy, LP (Massachusetts) has 3180 rates
3180 of 3970: Spark Energy, LP (New York) has 3181 rates
3181 of 3970: Spark Energy, LP (Pennsylvania) has 3182 rates
3182 of 3970: Spartan Renewable Energy, Inc has 3183 rates
3183 of 3970: Spoon River Electric Coop, Inc has 3184 rates
3184 of 3970: Spring City Corporation (Utility Company) has 3185 rates
3185 of 3970: Spring Valley Pub Utils Comm has 3186 rates
3186 of 3970: Springer Electric Coop, Inc has 3187 rates
3187 of 3970: Springfield Public Utils Comm has 3188 rates
3188 of 3970: Square Butte Electric Coop has 3189 rates
3189 of 3970: SRW Cogeneration LP has 3190 rates
3190 of 3970: St Croix Electric Coop has 3191 rates
3191 of 3970: Stanton County Public Pwr Dist has 3192 rates
3192 of 3970: StarTex Power has 3193 rates
3193 of 3970: Stearns Cooperative Elec Assn has 3194 rates
3194 of 3970: Steele-Waseca Cooperative Electric has 3195 rates
3195 of 3970: Steuben County Rural E M C has 3196 rates
3196 of 3970: Steuben Rural Elec Coop, Inc has 3197 rates
3197 of 3970: Stillwater Utilities Authority has 3198 rates
3198 of 3970: Strategic Energy LLC has 3199 rates
3199 of 3970: Strategic Energy LLC (California) has 3200 rates
3200 of 3970: Strategic Energy LLC (Connecticut) has 3201 rates
3201 of 3970: Strategic Energy LLC (Illinois) has 3202 rates
3202 of 3970: Strategic Energy LLC (Maryland) has 3203 rates
3203 of 3970: Strategic Energy LLC (Massachusetts) has 3204 rates
3204 of 3970: Strategic Energy LLC (Michigan) has 3205 rates
3205 of 3970: Strategic Energy LLC (New Jersey) has 3206 rates
3206 of 3970: Strategic Energy LLC (New York) has 3207 rates
3207 of 3970: Strategic Energy LLC (Ohio) has 3208 rates
3208 of 3970: Strategic Energy LLC (Texas) has 3209 rates
3209 of 3970: Stream Energy has 3210 rates
3210 of 3970: Suez Energy Resources North America has 3211 rates
3211 of 3970: Suez Energy Resources North America (Connecticut) has 3212 rates
3212 of 3970: Suez Energy Resources North America (Delaware) has 3213 rates
3213 of 3970: Suez Energy Resources North America (District of Columbia) has 3214 rates
3214 of 3970: Suez Energy Resources North America (Illinois) has 3215 rates
3215 of 3970: Suez Energy Resources North America (Maine) has 3216 rates
3216 of 3970: Suez Energy Resources North America (Maryland) has 3217 rates
3217 of 3970: Suez Energy Resources North America (Massachusetts) has 3218 rates
3218 of 3970: Suez Energy Resources North America (New Jersey) has 3219 rates
3219 of 3970: Suez Energy Resources North America (New York) has 3220 rates
3220 of 3970: Suez Energy Resources North America (Pennsylvania) has 3221 rates
3221 of 3970: SUEZ-DEGS of Ashtabula LLC has 3222 rates
3222 of 3970: Sullivan County R E C, Inc has 3223 rates
3223 of 3970: Sulphur Springs Valley E C Inc has 3224 rates
3224 of 3970: Sumner-Cowley Elec Coop, Inc has 3225 rates
3225 of 3970: Sumter Electric Coop, Inc has 3226 rates
3226 of 3970: Sumter Electric Member Corp has 3227 rates
3227 of 3970: Sun Prairie Water & Light Comm has 3228 rates
3228 of 3970: Sun River Electric Coop, Inc has 3229 rates
3229 of 3970: SunE CPA CDC1 LLC has 3230 rates
3230 of 3970: SunE CPA CDC2 LLC has 3231 rates
3231 of 3970: SunE KHL55 San Bernardino LLC has 3232 rates
3232 of 3970: SunE M5 Holdings LLC has 3233 rates
3233 of 3970: SunE M5C Holdings LLC has 3234 rates
3234 of 3970: SunE U6 Holdings LLC has 3235 rates
3235 of 3970: SunE U6 Holdings LLC (Colorado) has 3236 rates
3236 of 3970: SunE WG113 Moreno Valley LLC has 3237 rates
3237 of 3970: SunE WG45 Woodland LLC has 3238 rates
3238 of 3970: Sunflower Electric Power Corp has 3239 rates
3239 of 3970: Superior Water, Light and Power Co has 3240 rates
3240 of 3970: Surprise Valley Electrification Corp. has 3241 rates
3241 of 3970: Surprise Valley Electrification Corp. (Nevada) has 3242 rates
3242 of 3970: Surprise Valley Electrification Corp. (Oregon) has 3243 rates
3243 of 3970: Surry-Yadkin Elec Member Corp has 3244 rates
3244 of 3970: Sussex Rural Electric Coop Inc has 3245 rates
3245 of 3970: Suwannee Valley Elec Coop Inc has 3246 rates
3246 of 3970: Swans Island Electric Coop Inc has 3247 rates
3247 of 3970: SWEPCO has 3248 rates
3248 of 3970: Swisher Electric Coop, Inc has 3249 rates
3249 of 3970: Sylacauga Utilities Board has 3250 rates
3250 of 3970: System Energy Resources, Inc has 3251 rates
3251 of 3970: T I P Rural Electric Coop has 3252 rates
3252 of 3970: Tacoma Power has 3253 rates
3253 of 3970: Tacoma Public Utilities has 3254 rates
3254 of 3970: Tahlequah Public Works Auth has 3255 rates
3255 of 3970: Talgov has 3256 rates
3256 of 3970: Tallahatchie Valley E P A has 3257 rates
3257 of 3970: Tallapoosa River Elec Coop Inc has 3258 rates
3258 of 3970: Talquin Electric Coop, Inc has 3259 rates
3259 of 3970: Tampa Electric Co has 3260 rates
3260 of 3970: Tanana Power Co Inc has 3261 rates
3261 of 3970: Tanner Electric Coop has 3262 rates
3262 of 3970: Tara Energy Resources has 3263 rates
3263 of 3970: Tara Energy, Inc has 3264 rates
3264 of 3970: Tatitlek Electric Utility has 3265 rates
3265 of 3970: Taunton Municipal Lighting Plant (TMLP) has 3266 rates
3266 of 3970: Taylor County Rural E C C has 3267 rates
3267 of 3970: Taylor Electric Coop has 3268 rates
3268 of 3970: Taylor Electric Coop Inc has 3269 rates
3269 of 3970: TDM US has 3270 rates
3270 of 3970: TDX Manley Generating LLC has 3271 rates
3271 of 3970: TDX North Slope Generating Co has 3272 rates
3272 of 3970: Tecumseh Utility Authority has 3273 rates
3273 of 3970: Tenaska has 3274 rates
3274 of 3970: Tenaska Power Services Co has 3275 rates
3275 of 3970: Tenaska Power Services Co (Delaware) has 3276 rates
3276 of 3970: Tennessee Valley Authority has 3277 rates
3277 of 3970: Tennessee Valley Authority (Alabama) has 3278 rates
3278 of 3970: Tennessee Valley Authority (Kentucky) has 3279 rates
3279 of 3970: Tennessee Valley Authority (Mississippi) has 3280 rates
3280 of 3970: Tennessee Valley Authority (North Carolina) has 3281 rates
3281 of 3970: Tennessee Valley Electric Coop has 3282 rates
3282 of 3970: Terrebonne Parish Consol Gov't has 3283 rates
3283 of 3970: TEST UTILITY COMPANY has 3284 rates
3284 of 3970: Teton Operating Services LLC has 3285 rates
3285 of 3970: Tex-La Electric Coop-Texas Inc has 3286 rates
3286 of 3970: Texas General Land Office has 3287 rates
3287 of 3970: Texas Municipal Power Agency has 3288 rates
3288 of 3970: Texas Power, LP has 3289 rates
3289 of 3970: Texas Retail Energy, LLC has 3290 rates
3290 of 3970: Texas Retail Energy, LLC (Texas) has 3291 rates
3291 of 3970: Texas-New Mexico Power Co has 3292 rates
3292 of 3970: The Energy Coop has 3293 rates
3293 of 3970: The Narragansett Electric Co has 3294 rates
3294 of 3970: The Potomac Edison Co (Maryland) has 3295 rates
3295 of 3970: The Potomac Edison Co (West Virginia) has 3296 rates
3296 of 3970: The Toledo Edison Co has 3297 rates
3297 of 3970: Three Notch Elec Member Corp has 3298 rates
3298 of 3970: Three Rivers Electric Coop has 3299 rates
3299 of 3970: Thumb Electric Coop of Mich has 3300 rates
3300 of 3970: Thurmont Municipal Light Co has 3301 rates
3301 of 3970: Tideland Electric Member Corp has 3302 rates
3302 of 3970: Tillamook Peoples Utility Dist has 3303 rates
3303 of 3970: Tillotson Rubber Co Inc has 3304 rates
3304 of 3970: Tipmont Rural Elec Member Corp has 3305 rates
3305 of 3970: Tippah Electric Power Assn has 3306 rates
3306 of 3970: Tipton Municipal Electric Util has 3307 rates
3307 of 3970: Tishomingo County E P A has 3308 rates
3308 of 3970: Todd-Wadena Electric Coop has 3309 rates
3309 of 3970: Tohono O'Odham Utility Auth has 3310 rates
3310 of 3970: Toledo Bend Project Joint Oper has 3311 rates
3311 of 3970: Tombigbee Electric Coop, Inc has 3312 rates
3312 of 3970: Tombigbee Electric Power Assn has 3313 rates
3313 of 3970: Tongue River Electric Coop Inc has 3314 rates
3314 of 3970: Tonopah Irrigation District has 3315 rates
3315 of 3970: Town of Advance, Indiana (Utility Company) has 3316 rates
3316 of 3970: Town of Apex, North Carolina (Utility Company) has 3317 rates
3317 of 3970: Town of Argos, Indiana (Utility Company) has 3318 rates
3318 of 3970: Town of Ashburnham, Massachusetts (Utility Company) has 3319 rates
3319 of 3970: Town of Ashland, New Hampshire (Utility Company) has 3320 rates
3320 of 3970: Town of Avilla, Indiana (Utility Company) has 3321 rates
3321 of 3970: Town of Ayden, North Carolina (Utility Company) has 3322 rates
3322 of 3970: Town of Bainbridge, Indiana (Utility Company) has 3323 rates
3323 of 3970: Town of Bargersville, Indiana (Utility Company) has 3324 rates
3324 of 3970: Town of Basin, Wyoming (Utility Company) has 3325 rates
3325 of 3970: Town of Belhaven, North Carolina (Utility Company) has 3326 rates
3326 of 3970: Town of Belmont, Massachusetts (Utility Company) has 3327 rates
3327 of 3970: Town of Benson, North Carolina (Utility Company) has 3328 rates
3328 of 3970: Town of Berlin, Maryland (Utility Company) has 3329 rates
3329 of 3970: Town of Black Creek, North Carolina (Utility Company) has 3330 rates
3330 of 3970: Town of Blackstone, Virginia (Utility Company) has 3331 rates
3331 of 3970: Town of Bostic, North Carolina (Utility Company) has 3332 rates
3332 of 3970: Town of Boyce, Louisiana (Utility Company) has 3333 rates
3333 of 3970: Town of Boylston, Massachusetts (Utility Company) has 3334 rates
3334 of 3970: Town of Braintree, Massachusetts (Utility Company) has 3335 rates
3335 of 3970: Town of Braman, Oklahoma (Utility Company) has 3336 rates
3336 of 3970: Town of Brinson, Georgia (Utility Company) has 3337 rates
3337 of 3970: Town of Brooklyn, Indiana (Utility Company) has 3338 rates
3338 of 3970: Town of Brookston, Indiana (Utility Company) has 3339 rates
3339 of 3970: Town of Centerville, Indiana (Utility Company) has 3340 rates
3340 of 3970: Town of Chalmers, Indiana (Utility Company) has 3341 rates
3341 of 3970: Town of Chester, Massachusetts (Utility Company) has 3342 rates
3342 of 3970: Town of Clayton, Delaware (Utility Company) has 3343 rates
3343 of 3970: Town of Clayton, North Carolina (Utility Company) has 3344 rates
3344 of 3970: Town of Coatesville, Indiana (Utility Company) has 3345 rates
3345 of 3970: Town of Concord, Massachusetts (Utility Company) has 3346 rates
3346 of 3970: Town of Crane, Indiana (Utility Company) has 3347 rates
3347 of 3970: Town of Culpeper, Virginia (Utility Company) has 3348 rates
3348 of 3970: Town of Dallas, North Carolina (Utility Company) has 3349 rates
3349 of 3970: Town of Danvers, Massachusetts (Utility Company) has 3350 rates
3350 of 3970: Town of Drexel, North Carolina (Utility Company) has 3351 rates
3351 of 3970: Town of Dunreith, Indiana (Utility Company) has 3352 rates
3352 of 3970: Town of Eatonville, Washington (Utility Company) has 3353 rates
3353 of 3970: Town of Edenton, North Carolina (Utility Company) has 3354 rates
3354 of 3970: Town of Elkton, Virginia (Utility Company) has 3355 rates
3355 of 3970: Town of Enfield, North Carolina (Utility Company) has 3356 rates
3356 of 3970: Town of Erwin, Tennessee (Utility Company) has 3357 rates
3357 of 3970: Town of Estes Park, Colorado (Utility Company) has 3358 rates
3358 of 3970: Town of Etna Green, Indiana (Utility Company) has 3359 rates
3359 of 3970: Town of Farmville, North Carolina (Utility Company) has 3360 rates
3360 of 3970: Town of Ferdinand, Indiana (Utility Company) has 3361 rates
3361 of 3970: Town of Fleming, Colorado (Utility Company) has 3362 rates
3362 of 3970: Town of Forest City, North Carolina (Utility Company) has 3363 rates
3363 of 3970: Town of Fort Laramie, Wyoming (Utility Company) has 3364 rates
3364 of 3970: Town of Fort Supply, Oklahoma (Utility Company) has 3365 rates
3365 of 3970: Town of Fountain, North Carolina (Utility Company) has 3366 rates
3366 of 3970: Town of Frankton, Indiana (Utility Company) has 3367 rates
3367 of 3970: Town of Frederick, Colorado (Utility Company) has 3368 rates
3368 of 3970: Town of Fremont, North Carolina (Utility Company) has 3369 rates
3369 of 3970: Town of Front Royal, Virginia (Utility Company) has 3370 rates
3370 of 3970: Town of Georgetown, Massachusetts (Utility Company) has 3371 rates
3371 of 3970: Town of Granada, Colorado (Utility Company) has 3372 rates
3372 of 3970: Town of Granite Falls, North Carolina (Utility Company) has 3373 rates
3373 of 3970: Town of Groton, Massachusetts (Utility Company) has 3374 rates
3374 of 3970: Town of Groveland, Massachusetts (Utility Company) has 3375 rates
3375 of 3970: Town of Guernsey, Wyoming (Utility Company) has 3376 rates
3376 of 3970: Town of Gueydan, Louisiana (Utility Company) has 3377 rates
3377 of 3970: Town of Hamilton, North Carolina (Utility Company) has 3378 rates
3378 of 3970: Town of Hardwick, Vermont (Utility Company) has 3379 rates
3379 of 3970: Town of Haxtun, Colorado (Utility Company) has 3380 rates
3380 of 3970: Town of High Point, North Carolina (Utility Company) has 3381 rates
3381 of 3970: Town of Hobgood, North Carolina (Utility Company) has 3382 rates
3382 of 3970: Town of Holden, Massachusetts (Utility Company) has 3383 rates
3383 of 3970: Town of Holden, Utah (Utility Company) has 3384 rates
3384 of 3970: Town of Holly, Colorado (Utility Company) has 3385 rates
3385 of 3970: Town of Hookerton, North Carolina (Utility Company) has 3386 rates
3386 of 3970: Town of Hudson, Massachusetts (Utility Company) has 3387 rates
3387 of 3970: Town of Huntersville, North Carolina (Utility Company) has 3388 rates
3388 of 3970: Town of Ipswich, Massachusetts (Utility Company) has 3389 rates
3389 of 3970: Town of Jamestown, Indiana (Utility Company) has 3390 rates
3390 of 3970: Town of Kingsford Heights, Indiana (Utility Company) has 3391 rates
3391 of 3970: Town of Knightstown, Indiana (Utility Company) has 3392 rates
3392 of 3970: Town of La Grange, North Carolina (Utility Company) has 3393 rates
3393 of 3970: Town of Ladoga, Indiana (Utility Company) has 3394 rates
3394 of 3970: Town of Landis, North Carolina (Utility Company) has 3395 rates
3395 of 3970: Town of Langford, South Dakota (Utility Company) has 3396 rates
3396 of 3970: Town of Laverne, Oklahoma (Utility Company) has 3397 rates
3397 of 3970: Town of Lingle, Wyoming (Utility Company) has 3398 rates
3398 of 3970: Town of Littleton, Massachusetts (Utility Company) has 3399 rates
3399 of 3970: Town of Littleton, New Hampshire (Utility Company) has 3400 rates
3400 of 3970: Town of Louisburg, North Carolina (Utility Company) has 3401 rates
3401 of 3970: Town of Lucama, North Carolina (Utility Company) has 3402 rates
3402 of 3970: Town of Lusk, Wyoming (Utility Company) has 3403 rates
3403 of 3970: Town of Lyons, Colorado (Utility Company) has 3404 rates
3404 of 3970: Town of MacClesfield, North Carolina (Utility Company) has 3405 rates
3405 of 3970: Town of Madison, Maine (Utility Company) has 3406 rates
3406 of 3970: Town of Maiden, North Carolina (Utility Company) has 3407 rates
3407 of 3970: Town of Manilla, Iowa (Utility Company) has 3408 rates
3408 of 3970: Town of Mannford, Oklahoma (Utility Company) has 3409 rates
3409 of 3970: Town of Mansfield, Massachusetts (Utility Company) has 3410 rates
3410 of 3970: Town of Massena, New York (Utility Company) has 3411 rates
3411 of 3970: Town of McCormick, South Carolina (Utility Company) has 3412 rates
3412 of 3970: Town of Merrimac, Massachusetts (Utility Company) has 3413 rates
3413 of 3970: Town of Middleborough, Massachusetts (Utility Company) has 3414 rates
3414 of 3970: Town of Middleton, Massachusetts (Utility Company) has 3415 rates
3415 of 3970: Town of Middletown, Delaware (Utility Company) has 3416 rates
3416 of 3970: Town of Middletown, Indiana (Utility Company) has 3417 rates
3417 of 3970: Town of Montezuma, Indiana (Utility Company) has 3418 rates
3418 of 3970: Town of Murphy, North Carolina (Utility Company) has 3419 rates
3419 of 3970: Town of New Carlisle, Indiana (Utility Company) has 3420 rates
3420 of 3970: Town of North Attleborough, Massachusetts (Utility Company) has 3421 rates
3421 of 3970: Town of Oak City, North Carolina (Utility Company) has 3422 rates
3422 of 3970: Town of Oak City, Utah (Utility Company) has 3423 rates
3423 of 3970: Town of Oak Creek, Colorado (Utility Company) has 3424 rates
3424 of 3970: Town of Paoli, Indiana (Utility Company) has 3425 rates
3425 of 3970: Town of Paragonah, Utah (Utility Company) has 3426 rates
3426 of 3970: Town of Paxton, Massachusetts (Utility Company) has 3427 rates
3427 of 3970: Town of Pendleton, Indiana (Utility Company) has 3428 rates
3428 of 3970: Town of Pikeville, North Carolina (Utility Company) has 3429 rates
3429 of 3970: Town of Pinetops, North Carolina (Utility Company) has 3430 rates
3430 of 3970: Town of Pineville, North Carolina (Utility Company) has 3431 rates
3431 of 3970: Town of Pittsboro, Indiana (Utility Company) has 3432 rates
3432 of 3970: Town of Princeton, Massachusetts (Utility Company) has 3433 rates
3433 of 3970: Town of Prosperity, South Carolina (Utility Company) has 3434 rates
3434 of 3970: Town of Reading, Massachusetts (Utility Company) has 3435 rates
3435 of 3970: Town of Readsboro, Vermont (Utility Company) has 3436 rates
3436 of 3970: Town of Red Springs, North Carolina (Utility Company) has 3437 rates
3437 of 3970: Town of Richlands, Virginia (Utility Company) has 3438 rates
3438 of 3970: Town of Rockville, Indiana (Utility Company) has 3439 rates
3439 of 3970: Town of Rowley, Massachusetts (Utility Company) has 3440 rates
3440 of 3970: Town of Ruston, Washington (Utility Company) has 3441 rates
3441 of 3970: Town of Ryan, Oklahoma (Utility Company) has 3442 rates
3442 of 3970: Town of Scotland Neck, North Carolina (Utility Company) has 3443 rates
3443 of 3970: Town of Selma, North Carolina (Utility Company) has 3444 rates
3444 of 3970: Town of Sharpsburg, North Carolina (Utility Company) has 3445 rates
3445 of 3970: Town of Shrewsbury, Massachusetts (Utility Company) has 3446 rates
3446 of 3970: Town of Skiatook, Oklahoma (Utility Company) has 3447 rates
3447 of 3970: Town of Smithfield, North Carolina (Utility Company) has 3448 rates
3448 of 3970: Town of Smyrna, Delaware (Utility Company) has 3449 rates
3449 of 3970: Town of South Coffeyville, Oklahoma (Utility Company) has 3450 rates
3450 of 3970: Town of South Hadley, Massachusetts (Utility Company) has 3451 rates
3451 of 3970: Town of South Whitley, Indiana (Utility Company) has 3452 rates
3452 of 3970: Town of Spiceland, Indiana (Utility Company) has 3453 rates
3453 of 3970: Town of Spiro, Oklahoma (Utility Company) has 3454 rates
3454 of 3970: Town of Springer, New Mexico (Utility Company) has 3455 rates
3455 of 3970: Town of Stantonsburg, North Carolina (Utility Company) has 3456 rates
3456 of 3970: Town of Steilacoom, Washington (Utility Company) has 3457 rates
3457 of 3970: Town of Sterling, Massachusetts (Utility Company) has 3458 rates
3458 of 3970: Town of Stowe, Vermont (Utility Company) has 3459 rates
3459 of 3970: Town of Straughn, Indiana (Utility Company) has 3460 rates
3460 of 3970: Town of Tarboro, North Carolina (Utility Company) has 3461 rates
3461 of 3970: Town of Templeton, Massachusetts (Utility Company) has 3462 rates
3462 of 3970: Town of Thatcher, Arizona (Utility Company) has 3463 rates
3463 of 3970: Town of Veedersburg, Indiana (Utility Company) has 3464 rates
3464 of 3970: Town of Vidalia, Louisiana (Utility Company) has 3465 rates
3465 of 3970: Town of Vinton, Louisiana (Utility Company) has 3466 rates
3466 of 3970: Town of Wake Forest, North Carolina (Utility Company) has 3467 rates
3467 of 3970: Town of Wakefield, Massachusetts (Utility Company) has 3468 rates
3468 of 3970: Town of Wakefield, Virginia (Utility Company) has 3469 rates
3469 of 3970: Town of Walkerton, Indiana (Utility Company) has 3470 rates
3470 of 3970: Town of Wallingford, Connecticut (Utility Company) has 3471 rates
3471 of 3970: Town of Walstonburg, North Carolina (Utility Company) has 3472 rates
3472 of 3970: Town of Warren, Indiana (Utility Company) has 3473 rates
3473 of 3970: Town of Waynesville, North Carolina (Utility Company) has 3474 rates
3474 of 3970: Town of Wellesley, Massachusetts (Utility Company) has 3475 rates
3475 of 3970: Town of Welsh, Louisiana (Utility Company) has 3476 rates
3476 of 3970: Town of West Boylston, Massachusetts (Utility Company) has 3477 rates
3477 of 3970: Town of Westfield, Iowa (Utility Company) has 3478 rates
3478 of 3970: Town of Wheatland, Wyoming (Utility Company) has 3479 rates
3479 of 3970: Town of Wickenburg, Arizona (Utility Company) has 3480 rates
3480 of 3970: Town of Williamsport, Maryland (Utility Company) has 3481 rates
3481 of 3970: Town of Winamac, Indiana (Utility Company) has 3482 rates
3482 of 3970: Town of Windsor, North Carolina (Utility Company) has 3483 rates
3483 of 3970: Town of Winnsboro, South Carolina (Utility Company) has 3484 rates
3484 of 3970: Town of Wolfeboro, New Hampshire (Utility Company) has 3485 rates
3485 of 3970: Tractebel Energy Marketing Inc has 3486 rates
3486 of 3970: TransAlta Energy Marketing (U.S.) Inc. has 3487 rates
3487 of 3970: TransCanada has 3488 rates
3488 of 3970: TransCanada Energy Marketing ULC has 3489 rates
3489 of 3970: TransCanada Power Mktg Ltd has 3490 rates
3490 of 3970: TransCanada Power Mktg Ltd (Connecticut) has 3491 rates
3491 of 3970: TransCanada Power Mktg Ltd (Maine) has 3492 rates
3492 of 3970: TransCanada Power Mktg Ltd (New Hampshire) has 3493 rates
3493 of 3970: TransCanada Power Mktg Ltd (New York) has 3494 rates
3494 of 3970: TransCanada Power Mktg Ltd (Rhode Island) has 3495 rates
3495 of 3970: Traverse Electric Coop, Inc has 3496 rates
3496 of 3970: Traverse Electric Coop, Inc (North Dakota) has 3497 rates
3497 of 3970: Trenton Municipal Utilities has 3498 rates
3498 of 3970: Tri-County Elec Member Corp has 3499 rates
3499 of 3970: Tri-County Elec Member Corp (Kentucky) has 3500 rates
3500 of 3970: Tri-County Elec Member Corp (North Carolina) has 3501 rates
3501 of 3970: Tri-County Elec Member Corp (Tennessee) has 3502 rates
3502 of 3970: Tri-County Electric Coop has 3503 rates
3503 of 3970: Tri-County Electric Coop (Michigan) has 3504 rates
3504 of 3970: Tri-County Electric Coop Assn has 3505 rates
3505 of 3970: Tri-County Electric Coop, Inc has 3506 rates
3506 of 3970: Tri-County Electric Coop, Inc (Florida) has 3507 rates
3507 of 3970: Tri-County Electric Coop, Inc (Illinois) has 3508 rates
3508 of 3970: Tri-County Electric Coop, Inc (Oklahoma) has 3509 rates
3509 of 3970: Tri-County Electric Coop, Inc (Texas) has 3510 rates
3510 of 3970: Tri-County Rural Elec Coop Inc has 3511 rates
3511 of 3970: Tri-State Electric Member Corp has 3512 rates
3512 of 3970: Tri-State Electric Member Corp (North Carolina) has 3513 rates
3513 of 3970: Tri-State Electric Member Corp (Tennessee) has 3514 rates
3514 of 3970: Tri-State G & T Assn, Inc has 3515 rates
3515 of 3970: Trico Electric Cooperative Inc has 3516 rates
3516 of 3970: Tricounty Rural Elec Coop, Inc has 3517 rates
3517 of 3970: TriEagle Energy, LLC has 3518 rates
3518 of 3970: Trinity Public Utilities Dist has 3519 rates
3519 of 3970: Trinity Valley Elec Coop Inc has 3520 rates
3520 of 3970: Truckee Donner P U D has 3521 rates
3521 of 3970: True Electric LLC has 3522 rates
3522 of 3970: Truman Public Utilities Comm has 3523 rates
3523 of 3970: Tucson Electric Power Co has 3524 rates
3524 of 3970: Tullahoma Board-Public Utils has 3525 rates
3525 of 3970: Tuntutuliak Comm Services Assn has 3526 rates
3526 of 3970: Tuolumne County Pub Power Agny has 3527 rates
3527 of 3970: Turlock Irrigation District has 3528 rates
3528 of 3970: Twin County Electric Pwr Assn has 3529 rates
3529 of 3970: Twin Valley Electric Coop Inc has 3530 rates
3530 of 3970: Twin Valleys Public Power Dist has 3531 rates
3531 of 3970: Two Rivers Water & Light has 3532 rates
3532 of 3970: TXU Energy Retail Co LP has 3533 rates
3533 of 3970: U.S. Energy Partners LLC has 3534 rates
3534 of 3970: UGI Energy Services, Inc. has 3535 rates
3535 of 3970: UGI Energy Services, Inc. (Delaware) has 3536 rates
3536 of 3970: UGI Energy Services, Inc. (District of Columbia) has 3537 rates
3537 of 3970: UGI Energy Services, Inc. (Maryland) has 3538 rates
3538 of 3970: UGI Energy Services, Inc. (New Jersey) has 3539 rates
3539 of 3970: UGI Energy Services, Inc. (New York) has 3540 rates
3540 of 3970: UGI Utilities, Inc has 3541 rates
3541 of 3970: UIL has 3542 rates
3542 of 3970: Umatilla Electric Coop Assn has 3543 rates
3543 of 3970: Unalakleet Valley Elec Coop has 3544 rates
3544 of 3970: Union County Electric Coop Inc has 3545 rates
3545 of 3970: Union Electric Co has 3546 rates
3546 of 3970: Union Electric Membership Corp has 3547 rates
3547 of 3970: Union Light, Heat & Power Co has 3548 rates
3548 of 3970: Union Rural Electric Coop, Inc has 3549 rates
3549 of 3970: United Electric Co-op, Inc has 3550 rates
3550 of 3970: United Electric Coop Service Inc has 3551 rates
3551 of 3970: United Electric Coop, Inc has 3552 rates
3552 of 3970: United Electric Coop, Inc (Iowa) has 3553 rates
3553 of 3970: United Electric Coop, Inc (Pennsylvania) has 3554 rates
3554 of 3970: United Illuminating Co has 3555 rates
3555 of 3970: United Power, Inc has 3556 rates
3556 of 3970: United Rural Elec Member Corp has 3557 rates
3557 of 3970: Unitil Energy Systems has 3558 rates
3558 of 3970: Unitil Energy Systems (Massachusetts) has 3559 rates
3559 of 3970: University of Illinois has 3560 rates
3560 of 3970: UNS Electric, Inc has 3561 rates
3561 of 3970: UP Power Marketing, LLC has 3562 rates
3562 of 3970: Upper Cumberland E M C has 3563 rates
3563 of 3970: Upper Missouri G&T El Coop Inc has 3564 rates
3564 of 3970: Upper Peninsula Power Co has 3565 rates
3565 of 3970: Upshur Rural Elec Coop Corp has 3566 rates
3566 of 3970: Upson Elec Member Corp has 3567 rates
3567 of 3970: US Operating Services Company has 3568 rates
3568 of 3970: USBIA-Mission Valley Power has 3569 rates
3569 of 3970: USBIA-San Carlos Project has 3570 rates
3570 of 3970: Utah Associated Mun Power Sys has 3571 rates
3571 of 3970: Utah Municipal Power Agency has 3572 rates
3572 of 3970: Utilities Dist-Western IN REMC has 3573 rates
3573 of 3970: Valero Refining Company - NJ has 3574 rates
3574 of 3970: Valley Clean Energy has 3575 rates
3575 of 3970: Valley Electric Assn, Inc has 3576 rates
3576 of 3970: Valley Electric Assn, Inc (Nevada) has 3577 rates
3577 of 3970: Valley Electric Member Corp has 3578 rates
3578 of 3970: Valley Rural Electric Coop Inc has 3579 rates
3579 of 3970: Van Buren Light & Power Dist has 3580 rates
3580 of 3970: Vectren has 3581 rates
3581 of 3970: Vera Irrigation District has 3582 rates
3582 of 3970: Verdigris Valley Elec Coop Inc has 3583 rates
3583 of 3970: Verendrye Electric Coop Inc has 3584 rates
3584 of 3970: Vermont Electric Cooperative, Inc. has 3585 rates
3585 of 3970: Vermont Electric Power Co, Inc has 3586 rates
3586 of 3970: Vermont Electric Trans Co Inc has 3587 rates
3587 of 3970: Vermont Public Pwr Supply Auth has 3588 rates
3588 of 3970: Vermont Yankee Nucl Pwr Corp has 3589 rates
3589 of 3970: Vernon Electric Coop has 3590 rates
3590 of 3970: Victoria Electric Coop, Inc has 3591 rates
3591 of 3970: Victory Electric Coop Assn Inc has 3592 rates
3592 of 3970: Vigilante Electric Coop, Inc has 3593 rates
3593 of 3970: Vigilante Electric Coop, Inc (Idaho) has 3594 rates
3594 of 3970: Village of Akron, New York (Utility Company) has 3595 rates
3595 of 3970: Village of Andover, New York (Utility Company) has 3596 rates
3596 of 3970: Village of Angelica, New York (Utility Company) has 3597 rates
3597 of 3970: Village of Arcade, New York (Utility Company) has 3598 rates
3598 of 3970: Village of Arcadia, Ohio (Utility Company) has 3599 rates
3599 of 3970: Village of Arnold, Nebraska (Utility Company) has 3600 rates
3600 of 3970: Village of Baraga, Michigan (Utility Company) has 3601 rates
3601 of 3970: Village of Bartley, Nebraska (Utility Company) has 3602 rates
3602 of 3970: Village of Beach City, Ohio (Utility Company) has 3603 rates
3603 of 3970: Village of Belmont, Wisconsin (Utility Company) has 3604 rates
3604 of 3970: Village of Benton, Wisconsin (Utility Company) has 3605 rates
3605 of 3970: Village of Bergen, New York (Utility Company) has 3606 rates
3606 of 3970: Village of Bethany, Illinois (Utility Company) has 3607 rates
3607 of 3970: Village of Bethel, Ohio (Utility Company) has 3608 rates
3608 of 3970: Village of Black Earth, Wisconsin (Utility Company) has 3609 rates
3609 of 3970: Village of Blanchester, Ohio (Utility Company) has 3610 rates
3610 of 3970: Village of Bloomdale, Ohio (Utility Company) has 3611 rates
3611 of 3970: Village of Boonville, New York (Utility Company) has 3612 rates
3612 of 3970: Village of Bradner, Ohio (Utility Company) has 3613 rates
3613 of 3970: Village of Bradshaw, Nebraska (Utility Company) has 3614 rates
3614 of 3970: Village of Brainard, Nebraska (Utility Company) has 3615 rates
3615 of 3970: Village of Brewster, Ohio (Utility Company) has 3616 rates
3616 of 3970: Village of Brocton, New York (Utility Company) has 3617 rates
3617 of 3970: Village of Cadott, Wisconsin (Utility Company) has 3618 rates
3618 of 3970: Village of Callaway, Nebraska (Utility Company) has 3619 rates
3619 of 3970: Village of Campbell, Nebraska (Utility Company) has 3620 rates
3620 of 3970: Village of Carey, Ohio (Utility Company) has 3621 rates
3621 of 3970: Village of Cashton, Wisconsin (Utility Company) has 3622 rates
3622 of 3970: Village of Castile, New York (Utility Company) has 3623 rates
3623 of 3970: Village of Centuria, Wisconsin (Utility Company) has 3624 rates
3624 of 3970: Village of Chatham, Illinois (Utility Company) has 3625 rates
3625 of 3970: Village of Chelsea, Michigan (Utility Company) has 3626 rates
3626 of 3970: Village of Chester, Nebraska (Utility Company) has 3627 rates
3627 of 3970: Village of Churchville, New York (Utility Company) has 3628 rates
3628 of 3970: Village of Clinton, Michigan (Utility Company) has 3629 rates
3629 of 3970: Village of Cygnet, Ohio (Utility Company) has 3630 rates
3630 of 3970: Village of Daggett, Michigan (Utility Company) has 3631 rates
3631 of 3970: Village of Davenport, Nebraska (Utility Company) has 3632 rates
3632 of 3970: Village of De Witt, Nebraska (Utility Company) has 3633 rates
3633 of 3970: Village of Decatur, Nebraska (Utility Company) has 3634 rates
3634 of 3970: Village of Deshler, Ohio (Utility Company) has 3635 rates
3635 of 3970: Village of Dorchester, Nebraska (Utility Company) has 3636 rates
3636 of 3970: Village of Edgerton, Ohio (Utility Company) has 3637 rates
3637 of 3970: Village of Eldorado, Ohio (Utility Company) has 3638 rates
3638 of 3970: Village of Elk Creek, Nebraska (Utility Company) has 3639 rates
3639 of 3970: Village of Elmore, Ohio (Utility Company) has 3640 rates
3640 of 3970: Village of Endicott, Nebraska (Utility Company) has 3641 rates
3641 of 3970: Village of Endicott, New York (Utility Company) has 3642 rates
3642 of 3970: Village of Enosburg Falls, Vermont (Utility Company) has 3643 rates
3643 of 3970: Village of Fairmont, Nebraska (Utility Company) has 3644 rates
3644 of 3970: Village of Fairport, New York (Utility Company) has 3645 rates
3645 of 3970: Village of Frankfort, New York (Utility Company) has 3646 rates
3646 of 3970: Village of Freeburg, Illinois (Utility Company) has 3647 rates
3647 of 3970: Village of Freeport, New York (Utility Company) has 3648 rates
3648 of 3970: Village of Genoa, Ohio (Utility Company) has 3649 rates
3649 of 3970: Village of Georgetown, Ohio (Utility Company) has 3650 rates
3650 of 3970: Village of Glouster, Ohio (Utility Company) has 3651 rates
3651 of 3970: Village of Grafton, Ohio (Utility Company) has 3652 rates
3652 of 3970: Village of Green Island, New York (Utility Company) has 3653 rates
3653 of 3970: Village of Greene, New York (Utility Company) has 3654 rates
3654 of 3970: Village of Greenport, New York (Utility Company) has 3655 rates
3655 of 3970: Village of Greenup, Illinois (Utility Company) has 3656 rates
3656 of 3970: Village of Greenwich, Ohio (Utility Company) has 3657 rates
3657 of 3970: Village of Greenwood, Nebraska (Utility Company) has 3658 rates
3658 of 3970: Village of Gresham, Wisconsin (Utility Company) has 3659 rates
3659 of 3970: Village of Groton, New York (Utility Company) has 3660 rates
3660 of 3970: Village of Hamersville, Ohio (Utility Company) has 3661 rates
3661 of 3970: Village of Hamilton, New York (Utility Company) has 3662 rates
3662 of 3970: Village of Hampton, Nebraska (Utility Company) has 3663 rates
3663 of 3970: Village of Haskins, Ohio (Utility Company) has 3664 rates
3664 of 3970: Village of Hazel Green, Wisconsin (Utility Company) has 3665 rates
3665 of 3970: Village of Hemingford, Nebraska (Utility Company) has 3666 rates
3666 of 3970: Village of Hildreth, Nebraska (Utility Company) has 3667 rates
3667 of 3970: Village of Hilton, New York (Utility Company) has 3668 rates
3668 of 3970: Village of Holbrook, Nebraska (Utility Company) has 3669 rates
3669 of 3970: Village of Holley, New York (Utility Company) has 3670 rates
3670 of 3970: Village of Hyde Park, Vermont (Utility Company) has 3671 rates
3671 of 3970: Village of Ilion, New York (Utility Company) has 3672 rates
3672 of 3970: Village of Jackson Center, Ohio (Utility Company) has 3673 rates
3673 of 3970: Village of Jacksonville, Vermont (Utility Company) has 3674 rates
3674 of 3970: Village of Johnson, Vermont (Utility Company) has 3675 rates
3675 of 3970: Village of L'Anse, Michigan (Utility Company) has 3676 rates
3676 of 3970: Village of Ladd, Illinois (Utility Company) has 3677 rates
3677 of 3970: Village of Lakeview, Ohio (Utility Company) has 3678 rates
3678 of 3970: Village of Leigh, Nebraska (Utility Company) has 3679 rates
3679 of 3970: Village of Little Valley, New York (Utility Company) has 3680 rates
3680 of 3970: Village of Lodi, Ohio (Utility Company) has 3681 rates
3681 of 3970: Village of Lucas, Ohio (Utility Company) has 3682 rates
3682 of 3970: Village of Ludlow, Vermont (Utility Company) has 3683 rates
3683 of 3970: Village of Lyman, Nebraska (Utility Company) has 3684 rates
3684 of 3970: Village of Lyndonville, Vermont (Utility Company) has 3685 rates
3685 of 3970: Village of Marathon, New York (Utility Company) has 3686 rates
3686 of 3970: Village of Marshallville, Ohio (Utility Company) has 3687 rates
3687 of 3970: Village of Mayville, New York (Utility Company) has 3688 rates
3688 of 3970: Village of Mazomanie, Wisconsin (Utility Company) has 3689 rates
3689 of 3970: Village of Merrillan, Wisconsin (Utility Company) has 3690 rates
3690 of 3970: Village of Milan, Ohio (Utility Company) has 3691 rates
3691 of 3970: Village of Minster, Ohio (Utility Company) has 3692 rates
3692 of 3970: Village of Monroeville, Ohio (Utility Company) has 3693 rates
3693 of 3970: Village of Montpelier, Ohio (Utility Company) has 3694 rates
3694 of 3970: Village of Morrill, Nebraska (Utility Company) has 3695 rates
3695 of 3970: Village of Morrisville, Vermont (Utility Company) has 3696 rates
3696 of 3970: Village of Mt Horeb, Wisconsin (Utility Company) has 3697 rates
3697 of 3970: Village of Mullen, Nebraska (Utility Company) has 3698 rates
3698 of 3970: Village of Muscoda, Wisconsin (Utility Company) has 3699 rates
3699 of 3970: Village of New Bremen, Ohio (Utility Company) has 3700 rates
3700 of 3970: Village of New Glarus, Wisconsin (Utility Company) has 3701 rates
3701 of 3970: Village of New Knoxville, Ohio (Utility Company) has 3702 rates
3702 of 3970: Village of Northfield, Vermont (Utility Company) has 3703 rates
3703 of 3970: Village of Oak Harbor, Ohio (Utility Company) has 3704 rates
3704 of 3970: Village of Obetz, Ohio (Utility Company) has 3705 rates
3705 of 3970: Village of Ohio City, Ohio (Utility Company) has 3706 rates
3706 of 3970: Village of Orleans, Vermont (Utility Company) has 3707 rates
3707 of 3970: Village of Oxford, Nebraska (Utility Company) has 3708 rates
3708 of 3970: Village of Pardeeville, Wisconsin (Utility Company) has 3709 rates
3709 of 3970: Village of Paw Paw, Michigan (Utility Company) has 3710 rates
3710 of 3970: Village of Pemberville, Ohio (Utility Company) has 3711 rates
3711 of 3970: Village of Penn Yan, New York (Utility Company) has 3712 rates
3712 of 3970: Village of Philadelphia, New York (Utility Company) has 3713 rates
3713 of 3970: Village of Pioneer, Ohio (Utility Company) has 3714 rates
3714 of 3970: Village of Plymouth, Ohio (Utility Company) has 3715 rates
3715 of 3970: Village of Polk, Nebraska (Utility Company) has 3716 rates
3716 of 3970: Village of Prague, Nebraska (Utility Company) has 3717 rates
3717 of 3970: Village of Prairie Du Sac, Wisconsin (Utility Company) has 3718 rates
3718 of 3970: Village of Rantoul, Illinois (Utility Company) has 3719 rates
3719 of 3970: Village of Republic, Ohio (Utility Company) has 3720 rates
3720 of 3970: Village of Reynolds, Nebraska (Utility Company) has 3721 rates
3721 of 3970: Village of Richmondville, New York (Utility Company) has 3722 rates
3722 of 3970: Village of Ripley, Ohio (Utility Company) has 3723 rates
3723 of 3970: Village of Riverton, Illinois (Utility Company) has 3724 rates
3724 of 3970: Village of Rockville Centre, New York (Utility Company) has 3725 rates
3725 of 3970: Village of Rouses Point, New York (Utility Company) has 3726 rates
3726 of 3970: Village of Sauk City, Wisconsin (Utility Company) has 3727 rates
3727 of 3970: Village of Sherburne, New York (Utility Company) has 3728 rates
3728 of 3970: Village of Shickley, Nebraska (Utility Company) has 3729 rates
3729 of 3970: Village of Shiloh, Ohio (Utility Company) has 3730 rates
3730 of 3970: Village of Silver Springs, New York (Utility Company) has 3731 rates
3731 of 3970: Village of Skaneateles, New York (Utility Company) has 3732 rates
3732 of 3970: Village of Solvay, New York (Utility Company) has 3733 rates
3733 of 3970: Village of Spalding, Nebraska (Utility Company) has 3734 rates
3734 of 3970: Village of Spencerport, New York (Utility Company) has 3735 rates
3735 of 3970: Village of Springville, New York (Utility Company) has 3736 rates
3736 of 3970: Village of Stratford, Wisconsin (Utility Company) has 3737 rates
3737 of 3970: Village of Swanton, Vermont (Utility Company) has 3738 rates
3738 of 3970: Village of Sycamore, Ohio (Utility Company) has 3739 rates
3739 of 3970: Village of Talmage, Nebraska (Utility Company) has 3740 rates
3740 of 3970: Village of Theresa, New York (Utility Company) has 3741 rates
3741 of 3970: Village of Tontogany, Ohio (Utility Company) has 3742 rates
3742 of 3970: Village of Trempealeau, Wisconsin (Utility Company) has 3743 rates
3743 of 3970: Village of Tupper Lake, New York (Utility Company) has 3744 rates
3744 of 3970: Village of Union City, Michigan (Utility Company) has 3745 rates
3745 of 3970: Village of Versailles, Ohio (Utility Company) has 3746 rates
3746 of 3970: Village of Viola, Wisconsin (Utility Company) has 3747 rates
3747 of 3970: Village of Walthill, Nebraska (Utility Company) has 3748 rates
3748 of 3970: Village of Watkins Glen, New York (Utility Company) has 3749 rates
3749 of 3970: Village of Waunakee, Wisconsin (Utility Company) has 3750 rates
3750 of 3970: Village of Wauneta, Nebraska (Utility Company) has 3751 rates
3751 of 3970: Village of Waynesfield, Ohio (Utility Company) has 3752 rates
3752 of 3970: Village of Wellington, Ohio (Utility Company) has 3753 rates
3753 of 3970: Village of Wellsville, New York (Utility Company) has 3754 rates
3754 of 3970: Village of Westfield, New York (Utility Company) has 3755 rates
3755 of 3970: Village of Wharton, Ohio (Utility Company) has 3756 rates
3756 of 3970: Village of Wilcox, Nebraska (Utility Company) has 3757 rates
3757 of 3970: Village of Winnetka, Illinois (Utility Company) has 3758 rates
3758 of 3970: Village of Winside, Nebraska (Utility Company) has 3759 rates
3759 of 3970: Village of Woodville, Ohio (Utility Company) has 3760 rates
3760 of 3970: Village of Yellow Springs, Ohio (Utility Company) has 3761 rates
3761 of 3970: Vinton Public Power Auth has 3762 rates
3762 of 3970: Virgin Islands Wtr&Pwr Auth has 3763 rates
3763 of 3970: Virginia Electric & Power Co has 3764 rates
3764 of 3970: Virginia Electric & Power Co (North Carolina) has 3765 rates
3765 of 3970: Virginia Mun Elec Assn No 1 has 3766 rates
3766 of 3970: Virginia Tech Electric Service has 3767 rates
3767 of 3970: Volunteer Electric Coop has 3768 rates
3768 of 3970: Wabash County Rural E M C has 3769 rates
3769 of 3970: Wabash Valley Power Assn, Inc has 3770 rates
3770 of 3970: Wagoner Public Works Authority has 3771 rates
3771 of 3970: Wake Electric Membership Corp has 3772 rates
3772 of 3970: Walters Public Works Authority has 3773 rates
3773 of 3970: Walton Electric Member Corp has 3774 rates
3774 of 3970: Walton EMC has 3775 rates
3775 of 3970: Warren County Rural E M C has 3776 rates
3776 of 3970: Warren Electric Coop Inc has 3777 rates
3777 of 3970: Warren Rural Elec Coop Corp has 3778 rates
3778 of 3970: Wasco Electric Coop, Inc has 3779 rates
3779 of 3970: Washington Elec Member Corp has 3780 rates
3780 of 3970: Washington Electric Coop Inc has 3781 rates
3781 of 3970: Washington Electric Coop, Inc has 3782 rates
3782 of 3970: Washington Gas Energy Services has 3783 rates
3783 of 3970: Washington Gas Energy Services (Delaware) has 3784 rates
3784 of 3970: Washington Gas Energy Services (District of Columbia) has 3785 rates
3785 of 3970: Washington Gas Energy Services (Maryland) has 3786 rates
3786 of 3970: Washington Gas Energy Services (Pennsylvania) has 3787 rates
3787 of 3970: Washington Island El Coop, Inc has 3788 rates
3788 of 3970: Washington-St Tammany E C, Inc has 3789 rates
3789 of 3970: Waterloo Light & Water Comm has 3790 rates
3790 of 3970: Watertown Municipal Utilities has 3791 rates
3791 of 3970: Waupun Utilities has 3792 rates
3792 of 3970: Waverly Municipal Elec Utility has 3793 rates
3793 of 3970: Wayne-White Counties Elec Coop has 3794 rates
3794 of 3970: We energies has 3795 rates
3795 of 3970: Weakley County Mun Elec Sys has 3796 rates
3796 of 3970: Weatherford Mun Utility System has 3797 rates
3797 of 3970: Webster Electric Coop has 3798 rates
3798 of 3970: Wellesley Municipal Light Plant has 3799 rates
3799 of 3970: Wells Rural Electric Co has 3800 rates
3800 of 3970: Wells Rural Electric Co (Utah) has 3801 rates
3801 of 3970: Wellsborough Electric Co has 3802 rates
3802 of 3970: Wellton-Mohawk Irr & Drain Dist has 3803 rates
3803 of 3970: West Central Electric Coop Inc has 3804 rates
3804 of 3970: West Central Electric Coop Inc (South Dakota) has 3805 rates
3805 of 3970: West Florida El Coop Assn, Inc has 3806 rates
3806 of 3970: West Kentucky Rural E C C has 3807 rates
3807 of 3970: West Oregon Electric Coop Inc has 3808 rates
3808 of 3970: West Penn Power Co has 3809 rates
3809 of 3970: West Plains Electric Coop Inc has 3810 rates
3810 of 3970: West Point Utility System has 3811 rates
3811 of 3970: West River Electric Assn Inc has 3812 rates
3812 of 3970: Westar Energy Inc has 3813 rates
3813 of 3970: Western Area Power Administration has 3814 rates
3814 of 3970: Western Coop Electric Assn Inc has 3815 rates
3815 of 3970: Western Farmers Elec Coop, Inc has 3816 rates
3816 of 3970: Western Illinois Elec Coop has 3817 rates
3817 of 3970: Western Indiana Energy REMC has 3818 rates
3818 of 3970: Western Iowa Power Coop has 3819 rates
3819 of 3970: Western Massachusetts Elec Co has 3820 rates
3820 of 3970: Western Minnesota Mun Pwr Agny has 3821 rates
3821 of 3970: Westfield Electric Co has 3822 rates
3822 of 3970: WGES has 3823 rates
3823 of 3970: Wharton County Elec Coop, Inc has 3824 rates
3824 of 3970: Wheat Belt Public Power Dist has 3825 rates
3825 of 3970: Wheatland Electric Coop, Inc has 3826 rates
3826 of 3970: Wheatland Electric Coop, Inc (Colorado) has 3827 rates
3827 of 3970: Wheatland Rural Elec Assn, Inc has 3828 rates
3828 of 3970: Wheeling Power Co has 3829 rates
3829 of 3970: Whetstone Valley Elec Coop Inc has 3830 rates
3830 of 3970: White County Rural E M C has 3831 rates
3831 of 3970: White River Electric Assn, Inc has 3832 rates
3832 of 3970: White River Valley El Coop Inc has 3833 rates
3833 of 3970: Whitehall Electric Utility has 3834 rates
3834 of 3970: Whitewater Valley Rural EMC has 3835 rates
3835 of 3970: Wild Rice Electric Coop, Inc has 3836 rates
3836 of 3970: Williamstown Utility Comm has 3837 rates
3837 of 3970: Willmar Municipal Utilities has 3838 rates
3838 of 3970: Willwood Light & Power Company has 3839 rates
3839 of 3970: Winner Municipal Utility has 3840 rates
3840 of 3970: Wiregrass Electric Coop, Inc has 3841 rates
3841 of 3970: Wisconsin Dells Electric Util has 3842 rates
3842 of 3970: Wisconsin Electric Power Co has 3843 rates
3843 of 3970: Wisconsin Electric Power Co (Michigan) has 3844 rates
3844 of 3970: Wisconsin Power & Light Co has 3845 rates
3845 of 3970: Wisconsin Public Service Corp has 3846 rates
3846 of 3970: Wisconsin Public Service Corp (Michigan) has 3847 rates
3847 of 3970: Wisconsin Rapids W W & L Comm has 3848 rates
3848 of 3970: Wisconsin River Power Company has 3849 rates
3849 of 3970: Wise Electric Coop Inc has 3850 rates
3850 of 3970: Withlacoochee River Elec Coop has 3851 rates
3851 of 3970: Wolverine Power Marketing Coop has 3852 rates
3852 of 3970: Wolverine Pwr Supply Coop, Inc has 3853 rates
3853 of 3970: Wonewoc Electric & Water Util has 3854 rates
3854 of 3970: Wood County Electric Coop, Inc has 3855 rates
3855 of 3970: Woodbury County Rural E C A has 3856 rates
3856 of 3970: Woodruff Electric Coop Corp has 3857 rates
3857 of 3970: WPPI Energy has 3858 rates
3858 of 3970: Wright-Hennepin Coop Elec Assn has 3859 rates
3859 of 3970: WTU Energy, LP has 3860 rates
3860 of 3970: Wyandotte Municipal Serv Comm has 3861 rates
3861 of 3970: Wyoming Municipal Power Agency has 3862 rates
3862 of 3970: Wyrulec Company has 3863 rates
3863 of 3970: Xcel Energy Michigan has 3864 rates
3864 of 3970: Xcel Energy New Mexico has 3865 rates
3865 of 3970: Xcel Energy North Dakota has 3866 rates
3866 of 3970: Xcel Energy of Colorado has 3867 rates
3867 of 3970: Xcel Energy of Minnesota has 3868 rates
3868 of 3970: Xcel Energy of North Dakota has 3869 rates
3869 of 3970: Xcel Energy of South Dakota has 3870 rates
3870 of 3970: Xcel Energy South Dakota has 3871 rates
3871 of 3970: Xcel Energy Texas has 3872 rates
3872 of 3970: Xcel Energy Wisconsin has 3873 rates
3873 of 3970: Y-W Electric Assn Inc has 3874 rates
3874 of 3970: Y-W Electric Assn Inc (Nebraska) has 3875 rates
3875 of 3970: Yakutat Power Inc has 3876 rates
3876 of 3970: Yampa Valley Electric Assn Inc has 3877 rates
3877 of 3970: Yampa Valley Electric Assn Inc (Wyoming) has 3878 rates
3878 of 3970: Yazoo Valley Elec Power Assn has 3879 rates
3879 of 3970: Yellowstone Valley Elec Co-op Inc. has 3880 rates
3880 of 3970: York Electric Coop Inc has 3881 rates
3881 of 3970: Young Energy, LLC has 3882 rates
3882 of 3970: Yuba County Water Agency has 3883 rates
3883 of 3970: Air-e has 3884 rates
3884 of 3970: Alaska Power Telephone Company has 3885 rates
3885 of 3970: Alliant Energy has 3886 rates
3886 of 3970: Ameren Transmission Company has 3887 rates
3887 of 3970: Ameren Transmission Company of Illinois has 3888 rates
3888 of 3970: American Electric Power Company has 3889 rates
3889 of 3970: Arizona Corporation Commission has 3890 rates
3890 of 3970: Ashburnham Municipal Light Plant has 3891 rates
3891 of 3970: ATCO Electric has 3892 rates
3892 of 3970: ATCO Electric Yukon has 3893 rates
3893 of 3970: BACH KHOA INVESTMENT AND DEVELOPMENT OF SOLAR ENERGY CORPORATION has 3894 rates
3894 of 3970: Baltimore Gas and Electric has 3895 rates
3895 of 3970: Basin Electric Power Cooperative has 3896 rates
3896 of 3970: BC Hydro has 3897 rates
3897 of 3970: Belize Electricity Limited has 3898 rates
3898 of 3970: Black Hills Energy has 3899 rates
3899 of 3970: Bounce Energy, Inc. has 3900 rates
3900 of 3970: Central Maine Power has 3901 rates
3901 of 3970: City of Homestead Florida has 3902 rates
3902 of 3970: City of New Smyrna Beach Florida has 3903 rates
3903 of 3970: City of Summerside, Prince Edward Island has 3904 rates
3904 of 3970: City of Tallahassee Florida has 3905 rates
3905 of 3970: CLECO has 3906 rates
3906 of 3970: Comision Federal de Electricidad has 3907 rates
3907 of 3970: Dominion Energy (Virginia) has 3908 rates
3908 of 3970: Dominion North Carolina Power has 3909 rates
3909 of 3970: Duke Energy Company has 3910 rates
3910 of 3970: Duke Energy Progress, LLC has 3911 rates
3911 of 3970: Earth Power Resources Inc has 3912 rates
3912 of 3970: East River Electric Cooperative has 3913 rates
3913 of 3970: Eastern Maine Electric Cooperative has 3914 rates
3914 of 3970: El Paso Water has 3915 rates
3915 of 3970: Electricite de France has 3916 rates
3916 of 3970: Emera Inc has 3917 rates
3917 of 3970: Empresas Publicas de Medellin has 3918 rates
3918 of 3970: Empresas Públicas de Medellín has 3919 rates
3919 of 3970: Enel-Codensa has 3920 rates
3920 of 3970: Energie NB Power has 3921 rates
3921 of 3970: Engie has 3922 rates
3922 of 3970: Enmax Power Corporation has 3923 rates
3923 of 3970: Entergy Louisiana has 3924 rates
3924 of 3970: EPCOR Distribution and Transmission Inc has 3925 rates
3925 of 3970: FortisAlberta has 3926 rates
3926 of 3970: FortisBC has 3927 rates
3927 of 3970: Georgia Power Company has 3928 rates
3928 of 3970: GridZone has 3929 rates
3929 of 3970: Groton Utilities has 3930 rates
3930 of 3970: Gulf Power Company has 3931 rates
3931 of 3970: Hydro One Networks Inc has 3932 rates
3932 of 3970: Hydro Quebec has 3933 rates
3933 of 3970: Illinois Municipal Electric Agency has 3934 rates
3934 of 3970: Iraq Ministry of Electricity has 3935 rates
3935 of 3970: ISU 3 has 3936 rates
3936 of 3970: Liberty Utilities has 3937 rates
3937 of 3970: Manitoba Hydro has 3938 rates
3938 of 3970: Maritime Electric Company Limited has 3939 rates
3939 of 3970: Mississippi Power Company has 3940 rates
3940 of 3970: Moulton Niguel Water District has 3941 rates
3941 of 3970: National Grid has 3942 rates
3942 of 3970: New Brunswick Power Corporation has 3943 rates
3943 of 3970: Newfoundland and Labrador Hydro has 3944 rates
3944 of 3970: Newfoundland Power Inc has 3945 rates
3945 of 3970: Northland Utilities (Yellowknife) Ltd has 3946 rates
3946 of 3970: Norwich Public Utilities has 3947 rates
3947 of 3970: Nova Scotia Power has 3948 rates
3948 of 3970: NYSEG has 3949 rates
3949 of 3970: Oncor has 3950 rates
3950 of 3970: Otter Tail Power Company has 3951 rates
3951 of 3970: Pacific Power and Light has 3952 rates
3952 of 3970: Panhandle Rural Electric Membership Association has 3953 rates
3953 of 3970: Potomac Electric Power Company has 3954 rates
3954 of 3970: Public Utility District No 1 of Snohomish County has 3955 rates
3955 of 3970: Rushmore Electric Power Cooperative has 3956 rates
3956 of 3970: Saskatchewan Power Corporation has 3957 rates
3957 of 3970: Saskatoon Light And Power has 3958 rates
3958 of 3970: Seminole Electric Cooperative has 3959 rates
3959 of 3970: South Carolina Public Service Authority, Santee Cooper has 3960 rates
3960 of 3970: South Norwalk Electric Works has 3961 rates
3961 of 3970: Southern Illinois Power Cooperative has 3962 rates
3962 of 3970: Southwestern Electric Power Company has 3963 rates
3963 of 3970: Tampa Electric Company has 3964 rates
3964 of 3970: Tianjin Anson International Co. Ltd has 3965 rates
3965 of 3970: Toronto Hydro Electric System Ltd has 3966 rates
3966 of 3970: Utility Rate Database/Data has 3967 rates
3967 of 3970: Village of Igiugig has 3968 rates
3968 of 3970: WSSC Water has 3969 rates
3969 of 3970: Xcel Energy has 3970 rates
ok
Elapsed time: 4563.0 seconds.

**Review by cpaulgilman — APPROVED** [review]
Thank you for handling the optional 'sector' field and testing remaining utilities.

**Review by brtietz — APPROVED** [review]
Thanks for fixing and testing!

**Review by kmk142789 — APPROVED** [review]
